elasticsearch.image=${elasticsearch.image}
opensearch.image=${opensearch.image}
postgres.image=${postgres.image}
postgis.image=${postgis.image}
pgvector.image=${pgvector.image}
mariadb.image=${mariadb.image}
db2.image=${db2.image}
mssql.image=${mssql.image}
mysql.image=${mysql.image}
oracle.image=${oracle.image}
mongo.image=${mongo.image}
keycloak.docker.image=${keycloak.docker.image}
pulsar.image=${pulsar.image}
rabbitmq.image=${rabbitmq.image}
redis.image=${redis.image}
mailpit.image=${mailpit.image}