quarkus.datasource.db-kind=postgresql

# Reactive config
quarkus.datasource.reactive=true


quarkus.security.users.embedded.enabled=true
quarkus.security.users.embedded.users.scott=jb0ss
quarkus.security.users.embedded.plain-text=true
quarkus.security.users.embedded.roles.scott=Admin,admin,Tester,user


# Trace @Transactional support
quarkus.hibernate-orm.log.sql=true
quarkus.log.min-level=TRACE
quarkus.log.category."io.quarkus.reactive.transaction.TransactionalInterceptorBase".level=TRACE
quarkus.log.category."io.quarkus.reactive.transaction.TransactionalContextConnection.TransactionalContextConnection".level=TRACE
quarkus.log.category."io.quarkus.hibernate.reactive.runtime.customized".level=TRACE
#quarkus.log.category."org.hibernate.reactive".level=TRACE
quarkus.log.console.level=TRACE
