package io.quarkus.cyclonedx.endpoint.deployment;

import java.util.Optional;

import io.quarkus.cyclonedx.deployment.spi.EmbeddedSbomMetadataBuildItem;
import io.quarkus.cyclonedx.deployment.spi.EmbeddedSbomRequestBuildItem;
import io.quarkus.cyclonedx.endpoint.runtime.CycloneDxEndpointRecorder;
import io.quarkus.deployment.annotations.BuildProducer;
import io.quarkus.deployment.annotations.BuildStep;
import io.quarkus.deployment.annotations.ExecutionTime;
import io.quarkus.deployment.annotations.Record;
import io.quarkus.deployment.builditem.nativeimage.NativeImageResourceBuildItem;
import io.quarkus.vertx.http.deployment.spi.RouteBuildItem;
import io.quarkus.vertx.http.runtime.management.ManagementInterfaceBuildTimeConfig;

/**
 * Build processor that exposes an embedded CycloneDX SBOM via an HTTP endpoint.
 * <p>
 * When enabled, this processor requests an embedded SBOM to be generated at build time
 * and registers a Vert.x route that serves the SBOM content. The endpoint is registered
 * on the management interface when management is enabled, otherwise as an absolute route.
 */
public class CycloneDxEndpointProcessor {

    /**
     * Signals that an embedded SBOM should be generated by producing
     * an {@link EmbeddedSbomRequestBuildItem} when the endpoint is enabled.
     */
    @BuildStep
    void requestEmbeddedSbom(CycloneDxEndpointConfig config,
            BuildProducer<EmbeddedSbomRequestBuildItem> producer) {
        if (config.enabled()) {
            producer.produce(new EmbeddedSbomRequestBuildItem());
        }
    }

    /**
     * Registers a Vert.x route that serves the embedded CycloneDX SBOM.
     * <p>
     * The content type is derived from the SBOM resource name (XML or JSON).
     * The route is placed on the management interface when management is enabled,
     * otherwise it is registered as an absolute route.
     *
     * @return the route build item, or {@code null} if the endpoint is disabled
     *         or no embedded SBOM is available
     */
    @BuildStep
    @Record(ExecutionTime.RUNTIME_INIT)
    RouteBuildItem registerSbomEndpoint(CycloneDxEndpointRecorder recorder,
            CycloneDxEndpointConfig endpointConfig,
            ManagementInterfaceBuildTimeConfig managementConfig,
            Optional<EmbeddedSbomMetadataBuildItem> embeddedSbomMetadata) {
        if (!endpointConfig.enabled() || embeddedSbomMetadata.isEmpty()) {
            return null;
        }

        final EmbeddedSbomMetadataBuildItem metadata = embeddedSbomMetadata.get();
        String resourceName = metadata.getResourceName();
        String path = endpointConfig.path();
        // derive content type from the base resource name (without .gz suffix)
        String baseName = resourceName.endsWith(".gz")
                ? resourceName.substring(0, resourceName.length() - 3)
                : resourceName;
        String contentType = baseName.endsWith(".xml")
                ? "application/vnd.cyclonedx+xml"
                : "application/vnd.cyclonedx+json";

        var builder = managementConfig.enabled()
                ? RouteBuildItem.newManagementRoute(path)
                : RouteBuildItem.newAbsoluteRoute(path);
        return builder
                .withRoutePathConfigKey("quarkus.cyclonedx.endpoint.path")
                .withRequestHandler(recorder.handler(resourceName, contentType, metadata.isCompressed()))
                .displayOnNotFoundPage("CycloneDX SBOM")
                .build();
    }

    /**
     * Ensures the SBOM resource is included in native images.
     */
    @BuildStep
    public void nativeResource(BuildProducer<NativeImageResourceBuildItem> nativeImageResourceProducer,
            CycloneDxEndpointConfig endpointConfig,
            Optional<EmbeddedSbomMetadataBuildItem> embeddedSbomMetadata) {
        if (endpointConfig.enabled() && embeddedSbomMetadata.isPresent()) {
            nativeImageResourceProducer.produce(new NativeImageResourceBuildItem(embeddedSbomMetadata.get().getResourceName()));
        }
    }
}
