{#include Dockerfile-jar-header type='legacy-jar' cmd=buildtool.cmd.package-legacy-jar /}
{#include Dockerfile-jar-from /}
{#include Dockerfile-jar-env /}
{#include Dockerfile-jar-copy type='legacy-jar' /}
{#include Dockerfile-jar-entrypoint /}