{#include Dockerfile-jar-header type='jvm' cmd=buildtool.cmd.package /}
{#include Dockerfile-jar-from /}
{#include Dockerfile-jar-env /}
{#include Dockerfile-jar-copy type='jvm' /}
{#include Dockerfile-jar-entrypoint /}

