{#include Dockerfile-layout type='legacy-jar'}
    {#quarkusbuild}{buildtool.cli} {buildtool.cmd.package-legacy-jar}{/quarkusbuild}
    {#image}{dockerfile.legacy-jar.from} {/image}
    {#args}
ARG JAVA_PACKAGE=java-{java.version}-openjdk-headless
ARG RUN_JAVA_VERSION={dockerfile.legacy-jar.run-java-version}
    {/args}
    {#copy}
COPY {buildtool.build-dir}/lib/* /deployments/lib/
COPY {buildtool.build-dir}/*-runner.jar /deployments/app.jar
    {/copy}
{/include}
