package io.quarkus.grpc.server;

import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.RegisterExtension;

import com.google.protobuf.Descriptors;

import io.grpc.BindableService;
import io.grpc.ServerServiceDefinition;
import io.grpc.ServiceDescriptor;
import io.grpc.protobuf.ProtoServiceDescriptorSupplier;
import io.quarkus.grpc.GrpcService;
import io.quarkus.grpc.MutinyGrpc;
import io.quarkus.test.QuarkusExtensionTest;
import io.vertx.grpc.transcoding.TranscodingServiceMethod;

public class TranscodingBuildStepTest {

    @RegisterExtension
    static final QuarkusExtensionTest config = new QuarkusExtensionTest()
            .withApplicationRoot(jar -> jar
                    .addClasses(FakeMutinyGrpcWithTranscoding.class, FakeGrpcService.class))
            .withConfigurationResource("grpc-server-no-health-configuration.properties");

    @Test
    void applicationStartsWithTranscodingClasses() {
        // If we reach this point the build step ran successfully over a MutinyGrpc
        // class that has TranscodingServiceMethod fields.
    }

    // Simulates a MutinyXxxGrpc class generated by the protoc plugin
    // when google.api.http annotations are present.
    static class FakeMutinyGrpcWithTranscoding implements MutinyGrpc {
        @SuppressWarnings("rawtypes")
        public static final TranscodingServiceMethod getSinglePath = null;
    }

    // Independent BindableService bean — needed so the gRPC extension is satisfied.
    @GrpcService
    static class FakeGrpcService implements BindableService {

        @Override
        public ServerServiceDefinition bindService() {
            var mock = mock(ServerServiceDefinition.class);
            var sd = mock(ServiceDescriptor.class);
            when(sd.getName()).thenReturn("fake-transcoding-service");
            when(sd.getSchemaDescriptor()).thenReturn(new ProtoServiceDescriptorSupplier() {
                @Override
                public Descriptors.ServiceDescriptor getServiceDescriptor() {
                    return mock(Descriptors.ServiceDescriptor.class);
                }

                @Override
                public Descriptors.FileDescriptor getFileDescriptor() {
                    return mock(Descriptors.FileDescriptor.class);
                }
            });
            when(mock.getServiceDescriptor()).thenReturn(sd);
            return mock;
        }
    }
}
