= {project-name} - Community

== An Open Project

{project-name} is an Open Source project licensed under the https://www.apache.org/licenses/LICENSE-2.0[Apache License version 2.0].

First and foremost, it is an open community where contributions, ideas and discussions are done in the open and welcome contributors.

Let's join forces in building the future of Java applications.

== Code and issue tracker

The source code is hosted on {quarkus-base-url}[GitHub].

If you need to report a bug or request a new feature, look for a similar one on our {quarkus-issues-url}[github issues tracker]. If you don’t find any, create a new issue. 

== Getting help

=== Documentation

We have a lot of documentation for getting started with {project-name}, be sure to {quarkus-site-getting-started}[check it out]!

=== https://stackoverflow.com[Stack Overflow]

After the documentation, probably the best place to look for answers. We actively monitor the following tags:

- https://stackoverflow.com/questions/tagged/quarkus

=== Chat

If you prefer live chat with the developers, we have a Zulip chat where we all hang out, don't hesitate to {quarkus-chat-url}[ask your questions there].

== Contributing

There are a lot of ways to contribute to {project-name} development:

 * Writing documentation and quickstarts,
 * {quarkus-issues-url}[Fixing bugs or even just opening an issue],
 * Writing new extensions.

If you are an extension developer or want to contribute to {project-name} development, join our mailing list either:

- by emailing {quarkus-mailing-list-subscription-email}
- by visiting the Google Groups page {quarkus-mailing-list-index}

Make sure you visit our extensive {quarkus-site-extension-authors-guide}[extension developer guide].