= {project-name} - Live Coding

One of the major productivity problems that face most Java developers is traditional Java
development workflow. For most web developers this will generally be:

_Write Code_ -> _Compile_ -> _Deploy_ -> _Refresh Browser_ -> _Repeat_

This can be a major drain on productivity, as the compile + redeploy cycle can often take
up to a minute or more. {project-name} aims to solve this problem with its _Live Coding_
feature. When running in development mode the workflow is simply:

_Write Code_ -> _Refresh Browser_ -> _Repeat_

This will work out of the box, with no special setup required. This works for Java file, application config,
and static resources.

== How it works

When you run `mvn compile quarkus:dev` {project-name} will launch in development mode. When
it receives a HTTP request it will hold the request, and check to see if any application source
files have been changed. If they have it will transparently compile the changed files, redeploy
the application with the changed files, and then the HTTP request will continue to the redeployed
application. {project-name} redeploys are much faster than a traditional app server, so for all but the largest
applications this should take well under a second.