quarkus.grpc.clients.hello.host=hello-service
quarkus.grpc.clients.hello.name-resolver=stork

quarkus.stork."hello-service".service-discovery.type=static
quarkus.stork."hello-service".service-discovery.address-list=${quarkus.http.host}:8444
quarkus.stork."hello-service".load-balancer.type=round-robin

quarkus.grpc.clients.hello.tls.enabled=true
quarkus.grpc.clients.hello.tls.trust-certificate-pem.certs=tls/ca.pem
quarkus.grpc.clients.hello.tls.key-certificate-pem.certs=tls/client.pem
quarkus.grpc.clients.hello.tls.key-certificate-pem.keys=tls/client.key
quarkus.grpc.clients.hello.tls.verify-hostname=false

quarkus.http.insecure-requests=disabled
quarkus.http.ssl.certificate.files=tls/server.pem
quarkus.http.ssl.certificate.key-files=tls/server.key
quarkus.http.ssl.certificate.trust-store-file=tls/ca.jks
quarkus.http.ssl.certificate.trust-store-password=123456
quarkus.http.ssl.client-auth=required

quarkus.grpc.clients.hello.port=8444

quarkus.http.auth.certificate-role-properties=role-mappings.txt
quarkus.native.additional-build-args=-H:IncludeResources=.*\\.txt
