quarkus.hibernate-orm.statistics=true
quarkus.hibernate-orm.cache."com.example.EntityA".memory.object-count=200
quarkus.hibernate-orm.cache."com.example.EntityB".expiration.max-idle=86400
quarkus.hibernate-orm.cache."io.quarkus.it.hibernate.orm.cache.DataBlob".memory.maximum-weight=50000
quarkus.hibernate-orm.cache."io.quarkus.it.hibernate.orm.cache.DataBlob".memory.weigher-class=io.quarkus.it.hibernate.orm.cache.DataBlobWeigher
#quarkus.log.level=TRACE
#quarkus.log.file.level=TRACE
