# Configuration file
# key = value
example.message=Hello from App
app-only=App only
%test.test-only=Test only

# do not propagate, it will fail if the properties are propagated
%prod.quarkus.http.tls-configuration-name=https
%prod.quarkus.tls.https.key-store.pem.0.cert=/app/certificates/tls.crt
%prod.quarkus.tls.https.key-store.pem.0.key=/app/certificates/tls.key
