quarkus.tls.key-store.p12.path=target/certs/http3-test-keystore.p12
quarkus.tls.key-store.p12.password=secret

quarkus.tls.client.trust-store.p12.path=target/certs/http3-test-truststore.p12
quarkus.tls.client.trust-store.p12.password=secret

quarkus.rest-client.h3-client.url=https://localhost:${quarkus.http.test-ssl-port}
quarkus.rest-client.h3-client.http3=true
quarkus.rest-client.tls-configuration-name=client
