package io.quarkus.builder;

/**
 * A single atomic unit of build work. A build step either succeeds or it does not, with no intermediate states
 * possible. Build steps should be as fine-grained as possible.
 *
 * @author <a href="mailto:david.lloyd@redhat.com">David M. Lloyd</a>
 */
@FunctionalInterface
public interface BuildStep {
    /**
     * Execute a build step.
     *
     * @param context the context of the build operation (not {@code null})
     */
    void execute(BuildContext context);

    /**
     * Get the identifier for this build step.
     * The identifier should be unique within a build chain, and must be deterministic
     * (i.e. the same step must produce the same identifier across separate builds)
     * because the identifier may be embedded in generated bytecode.
     * <p>
     * The default implementation returns the implementation class name, which is
     * sufficient when at most one instance of a given class is added to a chain.
     * If multiple instances of the same class may be added to a single chain, the
     * implementation should override this method to include a distinguishing suffix
     * (for example, appending a constructor parameter or sequence number).
     *
     * @return the identifier (must not be {@code null})
     */
    default String getId() {
        return getClass().getName();
    }

    /**
     * The empty build step, which immediately succeeds.
     */
    BuildStep EMPTY = context -> {
    };
}
