package io.quarkus.maven;

import java.io.FileInputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.atomic.AtomicReference;

import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugin.MojoFailureException;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.ResolutionScope;

import io.quarkus.bootstrap.app.AugmentAction;
import io.quarkus.bootstrap.app.CuratedApplication;
import io.quarkus.deployment.cmd.BuildAotEnhancedCustomizerProducer;
import io.quarkus.deployment.cmd.BuildEnhancedAotContainerImageCommandHandler;
import io.quarkus.deployment.pkg.builditem.BuildAotOptimizedContainerImageResultBuildItem;

/**
 * Takes the AOT file generated by the ITs and builds a container image that includes it
 */
@Mojo(name = "build-aot-enhanced-container-image", defaultPhase = LifecyclePhase.POST_INTEGRATION_TEST, requiresDependencyResolution = ResolutionScope.COMPILE_PLUS_RUNTIME, threadSafe = true)
public class BuildAotEnhancedImageMojo extends QuarkusBootstrapMojo {

    private final AtomicReference<Map<String, Object>> contextHolder = new AtomicReference<>();

    @Override
    protected boolean beforeExecute() throws MojoExecutionException, MojoFailureException {
        // Only execute build if `quarkus-container-it.properties` exists and has an AOT file configured
        String outputDirectory = mavenProject().getBuild().getDirectory();
        Path metadataFilePath = Paths.get(outputDirectory).resolve("quarkus-container-it.properties");
        if (Files.exists(metadataFilePath)) {
            Properties properties = new Properties();
            try (var fis = new FileInputStream(metadataFilePath.toFile())) {
                properties.load(fis);
                String aotFileValue = properties.getProperty("aot-file");
                if (aotFileValue != null) {
                    Path aotFilePath = Path.of(aotFileValue);
                    if (Files.exists(aotFilePath)) {
                        getLog().debug(String.format("Found AOT file '%s'; proceeding to build AOT enhanced container image",
                                aotFilePath));
                        contextHolder.set(Map.of(
                                "original-container-image", properties.getProperty("original-container-image"),
                                "container-working-directory", properties.getProperty("container-working-directory"),
                                "aot-file", aotFilePath));
                        return true;
                    } else {
                        getLog().warn(String.format("AOT file '%s' not found", aotFilePath));
                    }
                } else {
                    getLog().debug("`aot-file` property not set in `quarkus-container-it.properties`");
                }
            } catch (IOException e) {
                getLog().warn(String.format("Failed to load %s", metadataFilePath.toAbsolutePath()), e);
            }
        }

        getLog().debug("Skipping AOT enhanced image build");
        return false;
    }

    @Override
    protected void doExecute() throws MojoExecutionException {
        try {
            try (CuratedApplication curatedApplication = bootstrapApplication()) {
                AugmentAction action = curatedApplication.createAugmentor(BuildAotEnhancedCustomizerProducer.class.getName(),
                        contextHolder.get());
                action.performCustomBuild(BuildEnhancedAotContainerImageCommandHandler.class.getName(), null,
                        BuildAotOptimizedContainerImageResultBuildItem.class.getName());
            }
        } catch (Exception e) {
            throw new MojoExecutionException("Failed to build quarkus application", e);
        }
    }
}
