package io.quarkus.maven;

import java.io.FileInputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.atomic.AtomicReference;

import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugin.MojoFailureException;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.ResolutionScope;

import io.quarkus.bootstrap.app.AugmentAction;
import io.quarkus.bootstrap.app.CuratedApplication;
import io.quarkus.deployment.cmd.BuildAotEnhancedCustomizerProducer;
import io.quarkus.deployment.cmd.BuildEnhancedAotContainerImageCommandHandler;
import io.quarkus.deployment.cmd.BuildPgoEnhancedCustomizerProducer;
import io.quarkus.deployment.cmd.BuildPgoOptimizedNativeCommandHandler;
import io.quarkus.deployment.pkg.builditem.BuildAotOptimizedContainerImageResultBuildItem;
import io.quarkus.deployment.pkg.builditem.BuildPgoOptimizedNativeResultBuildItem;

/**
 * Builds enhanced artifacts from data generated by integration tests.
 * Supports:
 * <ul>
 * <li>AOT-enhanced container images (from Leyden AOT training)</li>
 * <li>PGO-optimized native images (from GraalVM PGO profiling)</li>
 * </ul>
 */
@Mojo(name = "build-enhanced-artifact", defaultPhase = LifecyclePhase.POST_INTEGRATION_TEST, requiresDependencyResolution = ResolutionScope.COMPILE_PLUS_RUNTIME, threadSafe = true)
public class BuildEnhancedArtifactMojo extends QuarkusBootstrapMojo {

    private static final String PGO_PROFILE_NAME = "default.iprof";

    private enum EnhancementType {
        AOT_CONTAINER_IMAGE,
        PGO_NATIVE_IMAGE
    }

    private final AtomicReference<Map<String, Object>> contextHolder = new AtomicReference<>();
    private EnhancementType enhancementType;

    @Override
    protected boolean beforeExecute() throws MojoExecutionException, MojoFailureException {
        String outputDirectory = mavenProject().getBuild().getDirectory();

        // Check for PGO profile
        Path pgoProfile = Paths.get(outputDirectory).resolve(PGO_PROFILE_NAME);
        if (Files.exists(pgoProfile) && Files.isRegularFile(pgoProfile)) {
            getLog().debug(String.format("Found PGO profile '%s'; proceeding to build PGO-optimized native image",
                    pgoProfile));
            contextHolder.set(Map.of("pgo-profile", pgoProfile));
            enhancementType = EnhancementType.PGO_NATIVE_IMAGE;
        }

        // Check for AOT container image metadata
        Path metadataFilePath = Paths.get(outputDirectory).resolve("quarkus-container-it.properties");
        if (Files.exists(metadataFilePath)) {
            Properties properties = new Properties();
            try (var fis = new FileInputStream(metadataFilePath.toFile())) {
                properties.load(fis);
                String aotFileValue = properties.getProperty("aot-file");
                if (aotFileValue != null) {
                    Path aotFilePath = Path.of(aotFileValue);
                    if (Files.exists(aotFilePath) && Files.isRegularFile(aotFilePath)) {
                        if (enhancementType != null) {
                            getLog().debug("AOT file skipped because existing enhancement type " + enhancementType
                                    + " was previously set");
                        } else {
                            getLog().debug(String.format(
                                    "Found AOT file '%s'; proceeding to build AOT enhanced container image",
                                    aotFilePath));
                            contextHolder.set(Map.of(
                                    "original-container-image", properties.getProperty("original-container-image"),
                                    "container-working-directory", properties.getProperty("container-working-directory"),
                                    "aot-file", aotFilePath));
                            enhancementType = EnhancementType.AOT_CONTAINER_IMAGE;
                        }
                    } else {
                        getLog().warn(String.format("AOT file '%s' not found", aotFilePath));
                    }
                } else {
                    getLog().debug("`aot-file` property not set in `quarkus-container-it.properties`");
                }
            } catch (IOException e) {
                getLog().warn(String.format("Failed to load %s", metadataFilePath.toAbsolutePath()), e);
            }
        }

        if (enhancementType == null) {
            getLog().debug("Skipping enhanced artifact build (no PGO profile or AOT metadata found)");
        }
        return enhancementType != null;
    }

    @Override
    protected void doExecute() throws MojoExecutionException {
        try {
            try (CuratedApplication curatedApplication = bootstrapApplication()) {
                AugmentAction action;
                if (enhancementType == EnhancementType.AOT_CONTAINER_IMAGE) {
                    action = curatedApplication.createAugmentor(
                            BuildAotEnhancedCustomizerProducer.class.getName(),
                            contextHolder.get());
                    action.performCustomBuild(BuildEnhancedAotContainerImageCommandHandler.class.getName(), null,
                            BuildAotOptimizedContainerImageResultBuildItem.class.getName());
                } else if (enhancementType == EnhancementType.PGO_NATIVE_IMAGE) {
                    action = curatedApplication.createAugmentor(
                            BuildPgoEnhancedCustomizerProducer.class.getName(),
                            contextHolder.get());
                    action.performCustomBuild(BuildPgoOptimizedNativeCommandHandler.class.getName(), null,
                            BuildPgoOptimizedNativeResultBuildItem.class.getName());
                }
            }
        } catch (Exception e) {
            throw new MojoExecutionException("Failed to build enhanced artifact", e);
        }
    }
}
