version = 999-SNAPSHOT

# Enable the Gradle build cache
org.gradle.caching=true
# Enable Gradle parallel builds
org.gradle.parallel=true
# Configure only necessary Gradle tasks
org.gradle.configureondemand=true
# Explicitly disable the configuration cache.
# The configuration cache can be used explicitly using the `--configuration-cache` option.
# But enabling the configuration cache by default can be risky, especially in CI environments,
# because credentials in environment variable, system properties or Gradle properties _may_
# be persisted to disk and become unintentionally accessible.
org.gradle.configuration-cache=false
#org.gradle.configuration-cache-problems=warn
org.gradle.warning.mode=all
