package org.jboss.resteasy.reactive.server.processor.scanning;

import java.io.File;
import java.io.InputStream;
import java.nio.file.Path;
import java.util.Collection;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.function.BiFunction;

import jakarta.ws.rs.BadRequestException;
import jakarta.ws.rs.NotFoundException;
import jakarta.ws.rs.WebApplicationException;
import jakarta.ws.rs.core.MediaType;

import org.jboss.jandex.AnnotationInstance;
import org.jboss.jandex.ClassInfo;
import org.jboss.jandex.FieldInfo;
import org.jboss.jandex.IndexView;
import org.jboss.jandex.PrimitiveType.Primitive;
import org.jboss.jandex.RecordComponentInfo;
import org.jboss.jandex.Type;
import org.jboss.jandex.Type.Kind;
import org.jboss.resteasy.reactive.common.model.ParameterType;
import org.jboss.resteasy.reactive.common.processor.AsmUtil;
import org.jboss.resteasy.reactive.common.processor.ResteasyReactiveDotNames;
import org.jboss.resteasy.reactive.common.processor.TypeArgMapper;
import org.jboss.resteasy.reactive.common.util.DeploymentUtils;
import org.jboss.resteasy.reactive.common.util.types.TypeSignatureParser;
import org.jboss.resteasy.reactive.multipart.FileUpload;
import org.jboss.resteasy.reactive.server.core.Deployment;
import org.jboss.resteasy.reactive.server.core.ResteasyReactiveRequestContext;
import org.jboss.resteasy.reactive.server.core.multipart.DefaultFileUpload;
import org.jboss.resteasy.reactive.server.core.multipart.MultipartSupport;
import org.jboss.resteasy.reactive.server.core.parameters.MultipartFormParamExtractor;
import org.jboss.resteasy.reactive.server.core.parameters.converters.ArrayConverter;
import org.jboss.resteasy.reactive.server.core.parameters.converters.DelegatingParameterConverterSupplier;
import org.jboss.resteasy.reactive.server.core.parameters.converters.ParameterConverter;
import org.jboss.resteasy.reactive.server.core.parameters.converters.ParameterConverterSupplier;
import org.jboss.resteasy.reactive.server.core.parameters.converters.ParameterConverterSupport;
import org.jboss.resteasy.reactive.server.core.parameters.converters.RuntimeResolvedConverter;
import org.jboss.resteasy.reactive.server.injection.ResteasyReactiveInjectionContext;
import org.jboss.resteasy.reactive.server.injection.ResteasyReactiveInjectionTarget;
import org.jboss.resteasy.reactive.server.processor.ServerIndexedParameter;
import org.objectweb.asm.ClassVisitor;
import org.objectweb.asm.Opcodes;

import io.quarkus.gizmo.AssignableResultHandle;
import io.quarkus.gizmo.BranchResult;
import io.quarkus.gizmo.BytecodeCreator;
import io.quarkus.gizmo.CatchBlockCreator;
import io.quarkus.gizmo.ClassTransformer;
import io.quarkus.gizmo.FieldDescriptor;
import io.quarkus.gizmo.MethodCreator;
import io.quarkus.gizmo.MethodDescriptor;
import io.quarkus.gizmo.ResultHandle;
import io.quarkus.gizmo.TryBlock;

/**
 * The code that is generated by this transformer is described in detail at
 * https://github.com/quarkusio/quarkus/wiki/RESTEasy-Reactive-(Server)
 * DO NOT modify the generated code without updating the wiki.
 */
public class ClassInjectorTransformer implements BiFunction<String, ClassVisitor, ClassVisitor> {

    public static final String INIT_CONVERTER_METHOD_NAME = "__quarkus_init_converter__";
    private static final String INIT_CONVERTER_FIELD_NAME = "__quarkus_converter__";
    private static final String INJECT_METHOD_NAME = "__quarkus_rest_inject";

    private final LinkedHashMap<FieldInfo, ServerIndexedParameter> fieldExtractors;
    private final boolean superTypeIsInjectable;
    private final boolean requireCreateBeanParams;
    private final IndexView indexView;

    public ClassInjectorTransformer(LinkedHashMap<FieldInfo, ServerIndexedParameter> fieldExtractors,
            boolean superTypeIsInjectable,
            boolean requireCreateBeanParams, IndexView indexView) {
        this.fieldExtractors = fieldExtractors;
        this.superTypeIsInjectable = superTypeIsInjectable;
        this.requireCreateBeanParams = requireCreateBeanParams;
        this.indexView = indexView;
    }

    @Override
    public ClassVisitor apply(String className, ClassVisitor outputClassVisitor) {
        ClassTransformer transformer = new ClassTransformer(className);

        // Make the class public so we can call its static init converters from other packages
        transformer.removeModifiers(Opcodes.ACC_PRIVATE | Opcodes.ACC_PROTECTED);
        transformer.addModifiers(Opcodes.ACC_PUBLIC);

        // Get ClassInfo
        ClassInfo classInfo = indexView.getClassByName(className.replace('/', '.'));
        if (classInfo == null) {
            throw new RuntimeException("ClassInfo not found for " + className);
        }

        // Collect part types for multipart PartType parameters
        LinkedHashMap<FieldInfo, ServerIndexedParameter> partTypes = new LinkedHashMap<>();
        for (Entry<FieldInfo, ServerIndexedParameter> entry : fieldExtractors.entrySet()) {
            FieldInfo fieldInfo = entry.getKey();
            ServerIndexedParameter extractor = entry.getValue();
            if (extractor.getType() == ParameterType.FORM) {
                MultipartFormParamExtractor.Type multipartFormType = getMultipartFormType(extractor);
                if (multipartFormType == MultipartFormParamExtractor.Type.PartType) {
                    partTypes.put(fieldInfo, extractor);
                }
            }
        }

        // Add interface
        if (!superTypeIsInjectable) {
            transformer.addInterface(ResteasyReactiveInjectionTarget.class);
        }

        // Add multipart static fields
        for (Entry<FieldInfo, ServerIndexedParameter> entry : partTypes.entrySet()) {
            String fieldName = entry.getKey().name();
            transformer.addField(FieldDescriptor.of(className, fieldName + "_type", Class.class))
                    .setModifiers(Opcodes.ACC_STATIC | Opcodes.ACC_PRIVATE);
            transformer.addField(FieldDescriptor.of(className, fieldName + "_genericType", java.lang.reflect.Type.class))
                    .setModifiers(Opcodes.ACC_STATIC | Opcodes.ACC_PRIVATE);
            transformer.addField(FieldDescriptor.of(className, fieldName + "_mediaType", MediaType.class))
                    .setModifiers(Opcodes.ACC_STATIC | Opcodes.ACC_PRIVATE);
        }

        // Add converter fields
        for (Entry<FieldInfo, ServerIndexedParameter> entry : fieldExtractors.entrySet()) {
            FieldInfo fieldInfo = entry.getKey();
            ServerIndexedParameter extractor = entry.getValue();
            ParameterType paramType = extractor.getType();

            if (paramType == ParameterType.FORM || paramType == ParameterType.HEADER ||
                    paramType == ParameterType.MATRIX || paramType == ParameterType.COOKIE ||
                    paramType == ParameterType.PATH || paramType == ParameterType.QUERY) {

                ParameterConverterSupplier converter = extractor.getConverter();
                if (converter != null) {
                    String converterFieldName = INIT_CONVERTER_FIELD_NAME + fieldInfo.name();
                    transformer.addField(FieldDescriptor.of(className, converterFieldName, ParameterConverter.class))
                            .setModifiers(Opcodes.ACC_PRIVATE | Opcodes.ACC_STATIC);
                }
            }
        }

        // Add static initializer for multipart fields
        if (!partTypes.isEmpty()) {
            MethodCreator clinit = transformer.addMethod(MethodDescriptor.ofMethod(className, "<clinit>", void.class))
                    .setModifiers(Opcodes.ACC_STATIC);

            for (Entry<FieldInfo, ServerIndexedParameter> entry : partTypes.entrySet()) {
                generateMultipartFormStaticInit(clinit, className, entry.getKey(), entry.getValue());
            }

            clinit.returnValue(null);
        }

        // Add converter initialization methods
        for (Entry<FieldInfo, ServerIndexedParameter> entry : fieldExtractors.entrySet()) {
            FieldInfo fieldInfo = entry.getKey();
            ServerIndexedParameter extractor = entry.getValue();
            ParameterType paramType = extractor.getType();

            if (paramType == ParameterType.FORM || paramType == ParameterType.HEADER ||
                    paramType == ParameterType.MATRIX || paramType == ParameterType.COOKIE ||
                    paramType == ParameterType.PATH || paramType == ParameterType.QUERY) {

                ParameterConverterSupplier converter = extractor.getConverter();
                if (converter != null) {
                    generateConverterInitMethod(transformer, className, fieldInfo, converter, extractor.isSingle());
                }
            }
        }

        // Add inject method
        boolean isRecord = classInfo.isRecord();
        String superTypeName = classInfo.superName().toString().replace('.', '/');
        addInjectMethod(transformer, className, superTypeName, classInfo, isRecord, partTypes);

        return transformer.applyTo(outputClassVisitor);
    }

    private void addInjectMethod(ClassTransformer transformer, String className, String superTypeName,
            ClassInfo classInfo, boolean isRecord,
            Map<FieldInfo, ServerIndexedParameter> partTypes) {
        // Determine method descriptor
        MethodDescriptor injectDescriptor;
        String dottedClassName = className.replace('/', '.');
        if (isRecord) {
            injectDescriptor = MethodDescriptor.ofMethod(dottedClassName, INJECT_METHOD_NAME,
                    dottedClassName, ResteasyReactiveInjectionContext.class);
        } else {
            injectDescriptor = MethodDescriptor.ofMethod(dottedClassName, INJECT_METHOD_NAME,
                    void.class, ResteasyReactiveInjectionContext.class);
        }

        MethodCreator inject = transformer.addMethod(injectDescriptor)
                .setModifiers(Opcodes.ACC_PUBLIC | Opcodes.ACC_SYNTHETIC | (isRecord ? Opcodes.ACC_STATIC : 0));

        // Call super inject if needed (only for non-records)
        if (superTypeIsInjectable && !isRecord) {
            ResultHandle thisRef = inject.getThis();
            ResultHandle ctxParam = inject.getMethodParam(0);
            inject.invokeSpecialMethod(
                    MethodDescriptor.ofMethod(superTypeName, INJECT_METHOD_NAME,
                            void.class, ResteasyReactiveInjectionContext.class),
                    thisRef, ctxParam);
        }

        // For records, create local variables for each field
        Map<String, AssignableResultHandle> recordVars = null;
        if (isRecord) {
            recordVars = new HashMap<>();
            for (Entry<FieldInfo, ServerIndexedParameter> entry : fieldExtractors.entrySet()) {
                FieldInfo fieldInfo = entry.getKey();
                Type fieldType = fieldInfo.type();

                // Create variable and initialize with default value
                String descriptor = fieldType.descriptor();
                AssignableResultHandle var = inject.createVariable(descriptor);

                // Must initialize all variables - JVM bytecode verifier requires it
                ResultHandle defaultValue = fieldType.kind() == Kind.PRIMITIVE
                        ? getDefaultPrimitiveValue(inject, fieldType.asPrimitiveType().primitive())
                        : inject.loadNull();
                inject.assign(var, defaultValue);

                recordVars.put(fieldInfo.name(), var);
            }
        }

        // Inject each field
        for (Entry<FieldInfo, ServerIndexedParameter> entry : fieldExtractors.entrySet()) {
            injectField(inject, className, entry.getKey(), entry.getValue(), recordVars, isRecord, partTypes);
        }

        // For records, create instance and return it
        if (isRecord) {
            List<RecordComponentInfo> components = classInfo.unsortedRecordComponents();
            ResultHandle[] args = new ResultHandle[components.size()];
            String[] paramTypes = new String[components.size()];

            for (int i = 0; i < components.size(); i++) {
                RecordComponentInfo component = components.get(i);
                args[i] = recordVars.get(component.name());
                paramTypes[i] = component.type().name().toString();
            }

            ResultHandle recordInstance = inject.newInstance(
                    MethodDescriptor.ofConstructor(dottedClassName, paramTypes),
                    args);
            inject.returnValue(recordInstance);
        } else {
            inject.returnValue(null);
        }
    }

    private void injectField(MethodCreator inject, String className, FieldInfo fieldInfo,
            ServerIndexedParameter param, Map<String, AssignableResultHandle> recordVars, boolean isRecord,
            Map<FieldInfo, ServerIndexedParameter> partTypes) {
        ParameterType paramType = param.getType();

        switch (paramType) {
            case CONTEXT:
                injectContextParameter(inject, className, fieldInfo, param, recordVars, isRecord);
                break;
            case PATH:
            case QUERY:
            case HEADER:
            case COOKIE:
            case MATRIX:
                injectParameterWithConverter(inject, className, fieldInfo, param, recordVars, isRecord, paramType);
                break;
            case FORM:
                injectFormParameter(inject, className, fieldInfo, param, recordVars, isRecord, partTypes);
                break;
            case BEAN:
                injectBeanParameter(inject, className, fieldInfo, param, recordVars, isRecord);
                break;
            default:
                throw new RuntimeException("Unknown parameter type: " + paramType);
        }
    }

    private void injectBeanParameter(MethodCreator inject, String className, FieldInfo fieldInfo,
            ServerIndexedParameter param, Map<String, AssignableResultHandle> recordVars, boolean isRecord) {
        ResultHandle ctx = inject.getMethodParam(0);
        String fieldTypeName = fieldInfo.type().name().toString();
        String fieldTypeBinaryName = fieldTypeName.replace('.', '/');

        ClassInfo memberBeanClassInfo = indexView.getClassByName(fieldInfo.type().name());
        boolean memberBeanIsRecord = memberBeanClassInfo.isRecord();

        if (!memberBeanIsRecord) {
            // Non-record bean parameter
            if (isRecord) {
                // Parent is a record, so we need to get the bean from CDI and inject it
                ResultHandle paramClass = inject.loadClass(fieldTypeName);
                ResultHandle beanValue = inject.invokeInterfaceMethod(
                        MethodDescriptor.ofMethod(ResteasyReactiveInjectionContext.class, "getBeanParameter",
                                Object.class, Class.class),
                        ctx, paramClass);
                ResultHandle castedBean = inject.checkCast(beanValue, fieldTypeName);

                // Store in record variable
                AssignableResultHandle var = recordVars.get(fieldInfo.name());
                inject.assign(var, castedBean);

                // Call inject method on the bean to populate its @BeanParam fields
                inject.invokeInterfaceMethod(
                        MethodDescriptor.ofMethod(ResteasyReactiveInjectionTarget.class, INJECT_METHOD_NAME,
                                void.class, ResteasyReactiveInjectionContext.class),
                        castedBean, ctx);
            } else if (requireCreateBeanParams) {
                // Create new instance and inject it
                ResultHandle thisRef = inject.getThis();
                ResultHandle newBean = inject.newInstance(MethodDescriptor.ofConstructor(fieldTypeName));

                // Store in field
                inject.writeInstanceField(
                        FieldDescriptor.of(className.replace('/', '.'), fieldInfo.name(), fieldTypeName),
                        thisRef, newBean);

                // Call inject method on the bean
                inject.invokeVirtualMethod(
                        MethodDescriptor.ofMethod(fieldTypeBinaryName, INJECT_METHOD_NAME,
                                void.class, ResteasyReactiveInjectionContext.class),
                        newBean, ctx);
            } else {
                // Use existing field and call inject method
                ResultHandle thisRef = inject.getThis();
                ResultHandle bean = inject.readInstanceField(
                        FieldDescriptor.of(className.replace('/', '.'), fieldInfo.name(), fieldTypeName),
                        thisRef);

                inject.invokeVirtualMethod(
                        MethodDescriptor.ofMethod(fieldTypeBinaryName, INJECT_METHOD_NAME,
                                void.class, ResteasyReactiveInjectionContext.class),
                        bean, ctx);
            }
        } else {
            // Member bean is a record - call its static inject method
            String recordInjectSignature = "L" + fieldTypeBinaryName + ";";
            ResultHandle recordInstance = inject.invokeStaticMethod(
                    MethodDescriptor.ofMethod(fieldTypeBinaryName, INJECT_METHOD_NAME,
                            recordInjectSignature, ResteasyReactiveInjectionContext.class),
                    ctx);

            if (isRecord) {
                // Store in record variable
                AssignableResultHandle var = recordVars.get(fieldInfo.name());
                inject.assign(var, recordInstance);
            } else {
                // Store in field
                ResultHandle thisRef = inject.getThis();
                inject.writeInstanceField(
                        FieldDescriptor.of(className.replace('/', '.'), fieldInfo.name(), fieldTypeName),
                        thisRef, recordInstance);
            }
        }
    }

    private void injectContextParameter(MethodCreator inject, String className, FieldInfo fieldInfo,
            ServerIndexedParameter param, Map<String, AssignableResultHandle> recordVars, boolean isRecord) {
        // For non-records, context is already set by CDI, so skip
        if (!isRecord) {
            return;
        }

        ResultHandle ctx = inject.getMethodParam(0);
        String paramClassName = fieldInfo.type().name().toString();
        ResultHandle paramClass = inject.loadClass(paramClassName);

        ResultHandle value = inject.invokeInterfaceMethod(
                MethodDescriptor.ofMethod(ResteasyReactiveInjectionContext.class, "getContextParameter",
                        Object.class, Class.class),
                ctx, paramClass);

        AssignableResultHandle var = recordVars.get(fieldInfo.name());
        inject.assign(var, value);
    }

    private void generateMultipartFormStaticInit(MethodCreator clinit, String className, FieldInfo fieldInfo,
            ServerIndexedParameter extractor) {
        Type type = fieldInfo.type();
        // Extract the component type if not single
        if (!extractor.isSingle()) {
            boolean isArray = type.kind() == Type.Kind.ARRAY;
            // it's T[] or List<T>
            type = isArray ? type.asArrayType().constituent()
                    : type.asParameterizedType().arguments().get(0);
        }

        String fieldName = fieldInfo.name();

        // type field
        ResultHandle typeName = clinit.load(type.name().toString());
        ResultHandle typeClass = clinit.invokeStaticMethod(
                MethodDescriptor.ofMethod(DeploymentUtils.class, "loadClass",
                        Class.class, String.class),
                typeName);
        clinit.writeStaticField(FieldDescriptor.of(className, fieldName + "_type", Class.class), typeClass);

        // generic type field
        if ((type.kind() != Type.Kind.CLASS) && (type.kind() != Type.Kind.PRIMITIVE)) {
            TypeArgMapper typeArgMapper = new TypeArgMapper(fieldInfo.declaringClass(), indexView);
            String signature = AsmUtil.getSignature(type, typeArgMapper);
            ResultHandle signatureStr = clinit.load(signature);
            ResultHandle genericType = clinit.invokeStaticMethod(
                    MethodDescriptor.ofMethod(TypeSignatureParser.class, "parse",
                            java.lang.reflect.Type.class, String.class),
                    signatureStr);
            clinit.writeStaticField(FieldDescriptor.of(className, fieldName + "_genericType", java.lang.reflect.Type.class),
                    genericType);
        } else {
            // Read back the _type field we just wrote (avoids keeping loadClass result on stack)
            ResultHandle typeFromField = clinit.readStaticField(
                    FieldDescriptor.of(className, fieldName + "_type", Class.class));
            clinit.writeStaticField(FieldDescriptor.of(className, fieldName + "_genericType", java.lang.reflect.Type.class),
                    typeFromField);
        }

        // media type field
        String mediaType = extractor.getAnns().get(ResteasyReactiveDotNames.PART_TYPE_NAME).value().asString();
        ResultHandle mediaTypeStr = clinit.load(mediaType);
        ResultHandle mediaTypeObj = clinit.invokeStaticMethod(
                MethodDescriptor.ofMethod(MediaType.class, "valueOf",
                        MediaType.class, String.class),
                mediaTypeStr);
        clinit.writeStaticField(FieldDescriptor.of(className, fieldName + "_mediaType", MediaType.class), mediaTypeObj);
    }

    private void generateConverterInitMethod(ClassTransformer transformer, String className, FieldInfo fieldInfo,
            ParameterConverterSupplier converter, boolean single) {
        String converterFieldName = INIT_CONVERTER_FIELD_NAME + fieldInfo.name();
        String methodName = INIT_CONVERTER_METHOD_NAME + fieldInfo.name();

        // Remove runtime resolved converter delegate
        converter = removeRuntimeResolvedConverterDelegate(converter);

        String delegateBinaryName = null;
        if (converter instanceof DelegatingParameterConverterSupplier) {
            ParameterConverterSupplier delegate = removeRuntimeResolvedConverterDelegate(
                    ((DelegatingParameterConverterSupplier) converter).getDelegate());
            if (delegate != null)
                delegateBinaryName = delegate.getClassName();
        } else {
            delegateBinaryName = converter.getClassName();
        }

        MethodCreator initConverter = transformer.addMethod(
                MethodDescriptor.ofMethod(className, methodName, void.class, Deployment.class))
                .setModifiers(Opcodes.ACC_PUBLIC | Opcodes.ACC_STATIC);

        ResultHandle deployment = initConverter.getMethodParam(0);
        ResultHandle thisClass = initConverter.loadClass(className.replace('/', '.'));
        ResultHandle paramName = initConverter.load(fieldInfo.name());
        ResultHandle singleParam = initConverter.load(single);

        AssignableResultHandle runtimeConverter = initConverter.createVariable(ParameterConverter.class);
        ResultHandle converterValue = initConverter.invokeVirtualMethod(
                MethodDescriptor.ofMethod(Deployment.class, "getRuntimeParamConverter",
                        ParameterConverter.class, Class.class, String.class, boolean.class),
                deployment, thisClass, paramName, singleParam);
        initConverter.assign(runtimeConverter, converterValue);

        // Check if we have a delegate
        if (delegateBinaryName != null) {
            BranchResult notNull = initConverter.ifNotNull(runtimeConverter);
            BytecodeCreator nullBranch = notNull.falseBranch();
            ResultHandle delegateClassName = nullBranch.load(delegateBinaryName);
            ResultHandle fallback = nullBranch.invokeStaticMethod(
                    MethodDescriptor.ofMethod(ParameterConverterSupport.class, "create",
                            ParameterConverter.class, String.class),
                    delegateClassName);
            nullBranch.assign(runtimeConverter, fallback);
        }

        // Handle delegating converters (List/Set/SortedSet/Array)
        if (converter instanceof DelegatingParameterConverterSupplier) {
            String delegatorBinaryName = converter.getClassName();

            // Array converter needs the component type
            if (converter instanceof ArrayConverter.ArraySupplier) {
                Type componentType = fieldInfo.type().asArrayType().constituent();
                ResultHandle componentTypeName = initConverter.load(componentType.name().toString());
                ResultHandle delegatorInstance = initConverter.newInstance(
                        MethodDescriptor.ofConstructor(delegatorBinaryName, ParameterConverter.class, String.class),
                        runtimeConverter, componentTypeName);
                initConverter.assign(runtimeConverter, delegatorInstance);
            } else {
                ResultHandle delegatorInstance = initConverter.newInstance(
                        MethodDescriptor.ofConstructor(delegatorBinaryName, ParameterConverter.class),
                        runtimeConverter);
                initConverter.assign(runtimeConverter, delegatorInstance);
            }
        }

        // Store in static field
        initConverter.writeStaticField(
                FieldDescriptor.of(className, converterFieldName, ParameterConverter.class),
                runtimeConverter);

        initConverter.returnValue(null);
    }

    private static ParameterConverterSupplier removeRuntimeResolvedConverterDelegate(ParameterConverterSupplier converter) {
        if (converter instanceof RuntimeResolvedConverter.Supplier) {
            ParameterConverterSupplier delegate = ((RuntimeResolvedConverter.Supplier) converter).getDelegate();
            if (delegate != null) {
                return delegate;
            }
        }
        return converter;
    }

    private void injectParameterWithConverter(MethodCreator inject, String className, FieldInfo fieldInfo,
            ServerIndexedParameter param, Map<String, AssignableResultHandle> recordVars, boolean isRecord,
            ParameterType paramType) {
        // Determine exception type based on parameter type
        Class<?> exceptionType;
        switch (paramType) {
            case MATRIX:
            case QUERY:
            case PATH:
                exceptionType = NotFoundException.class;
                break;
            case HEADER:
            case COOKIE:
            case FORM:
                exceptionType = BadRequestException.class;
                break;
            default:
                throw new IllegalStateException("Unexpected parameter type for converter: " + paramType);
        }

        // Get context parameter and this reference before try block
        ResultHandle ctx = inject.getMethodParam(0);
        ResultHandle thisRef = isRecord ? null : inject.getThis();

        // Set up try-catch block
        TryBlock tryBlock = inject.tryBlock();

        // Load the parameter value (handles both regular and multipart parameters)
        ResultHandle value = loadParameter(tryBlock, ctx, fieldInfo, param, paramType, className);

        // For non-optional parameters, skip conversion/cast/store if value is null
        BytecodeCreator processBranch = tryBlock;
        if (!param.isOptional()) {
            BranchResult nullCheck = tryBlock.ifNull(value);
            processBranch = nullCheck.falseBranch();
        }

        // Convert parameter (only executed if value is not null for non-optional params)
        ResultHandle converted = convertParameter(processBranch, value, param, fieldInfo);

        // Store - Gizmo handles casting/unboxing automatically during assignment
        storeValue(processBranch, className, fieldInfo, converted, thisRef, recordVars, isRecord);

        // Add WebApplicationException catch block (rethrow as-is)
        CatchBlockCreator webAppCatch = tryBlock.addCatch(WebApplicationException.class);
        webAppCatch.throwException(webAppCatch.getCaughtException());

        // Add Throwable catch block (wrap in appropriate exception)
        CatchBlockCreator throwableCatch = tryBlock.addCatch(Throwable.class);
        ResultHandle exception = throwableCatch.getCaughtException();
        ResultHandle wrappedException = throwableCatch.newInstance(
                MethodDescriptor.ofConstructor(exceptionType, Throwable.class),
                exception);
        throwableCatch.throwException(wrappedException);
    }

    private void injectFormParameter(MethodCreator inject, String className, FieldInfo fieldInfo,
            ServerIndexedParameter param, Map<String, AssignableResultHandle> recordVars, boolean isRecord,
            Map<FieldInfo, ServerIndexedParameter> partTypes) {
        // Both multipart and regular form parameters go through the same path with try-catch, optional handling, etc.
        injectParameterWithConverter(inject, className, fieldInfo, param, recordVars, isRecord, ParameterType.FORM);
    }

    private ResultHandle loadMultipartParameter(BytecodeCreator method, ResultHandle requestCtx,
            ResultHandle paramName, FieldInfo fieldInfo, ServerIndexedParameter param,
            MultipartFormParamExtractor.Type multipartType, String className) {
        ResultHandle value;
        switch (multipartType) {
            case String:
                value = invokeMultipartSupport(method, requestCtx, paramName, param.isSingle(),
                        "getString", String.class);
                break;
            case ByteArray:
                value = invokeMultipartSupport(method, requestCtx, paramName, param.isSingle(),
                        "getByteArray", byte[].class);
                break;
            case InputStream:
                value = invokeMultipartSupport(method, requestCtx, paramName, param.isSingle(),
                        "getInputStream", InputStream.class);
                break;
            case FileUpload:
                if (param.getName().equals(FileUpload.ALL)) {
                    // Special case: FileUpload.ALL returns all uploads
                    value = method.invokeStaticMethod(
                            MethodDescriptor.ofMethod(MultipartSupport.class, "getFileUploads",
                                    List.class, ResteasyReactiveRequestContext.class),
                            requestCtx);
                } else {
                    value = invokeMultipartSupport(method, requestCtx, paramName, param.isSingle(),
                            "getFileUpload", DefaultFileUpload.class);
                }
                break;
            case File:
                value = loadMultipartFile(method, requestCtx, paramName, param.isSingle());
                break;
            case Path:
                value = loadMultipartPath(method, requestCtx, paramName, param.isSingle());
                break;
            case PartType:
                value = loadMultipartPartType(method, className, fieldInfo, param, requestCtx, paramName);
                break;
            default:
                throw new RuntimeException("Unknown multipart type: " + multipartType);
        }
        return value;
    }

    private ResultHandle loadMultipartFile(BytecodeCreator method, ResultHandle requestCtx,
            ResultHandle paramName, boolean single) {
        if (single) {
            // Get FileUpload, then convert to File if not null
            ResultHandle upload = method.invokeStaticMethod(
                    MethodDescriptor.ofMethod(MultipartSupport.class, "getFileUpload",
                            DefaultFileUpload.class, String.class, ResteasyReactiveRequestContext.class),
                    paramName, requestCtx);

            // Create result variable
            AssignableResultHandle result = method.createVariable(File.class);

            // Check if null
            BranchResult nullCheck = method.ifNotNull(upload);
            BytecodeCreator notNullBranch = nullCheck.trueBranch();
            BytecodeCreator nullBranch = nullCheck.falseBranch();

            // If not null: upload.uploadedFile().toFile()
            ResultHandle uploadedFile = notNullBranch.invokeVirtualMethod(
                    MethodDescriptor.ofMethod(DefaultFileUpload.class, "uploadedFile", Path.class),
                    upload);
            ResultHandle file = notNullBranch.invokeInterfaceMethod(
                    MethodDescriptor.ofMethod(Path.class, "toFile", File.class),
                    uploadedFile);
            notNullBranch.assign(result, file);

            // If null: assign null
            nullBranch.assign(result, nullBranch.loadNull());

            return result;
        } else {
            return method.invokeStaticMethod(
                    MethodDescriptor.ofMethod(MultipartSupport.class, "getJavaIOFileUploads",
                            List.class, String.class, ResteasyReactiveRequestContext.class),
                    paramName, requestCtx);
        }
    }

    private ResultHandle loadMultipartPath(BytecodeCreator method, ResultHandle requestCtx,
            ResultHandle paramName, boolean single) {
        if (single) {
            // Get FileUpload, then get path if not null
            ResultHandle upload = method.invokeStaticMethod(
                    MethodDescriptor.ofMethod(MultipartSupport.class, "getFileUpload",
                            DefaultFileUpload.class, String.class, ResteasyReactiveRequestContext.class),
                    paramName, requestCtx);

            // Create result variable
            AssignableResultHandle result = method.createVariable(Path.class);

            // Check if null
            BranchResult nullCheck = method.ifNotNull(upload);
            BytecodeCreator notNullBranch = nullCheck.trueBranch();
            BytecodeCreator nullBranch = nullCheck.falseBranch();

            // If not null: upload.uploadedFile()
            ResultHandle uploadedFile = notNullBranch.invokeVirtualMethod(
                    MethodDescriptor.ofMethod(DefaultFileUpload.class, "uploadedFile", Path.class),
                    upload);
            notNullBranch.assign(result, uploadedFile);

            // If null: assign null
            nullBranch.assign(result, nullBranch.loadNull());

            return result;
        } else {
            return method.invokeStaticMethod(
                    MethodDescriptor.ofMethod(MultipartSupport.class, "getJavaPathFileUploads",
                            List.class, String.class, ResteasyReactiveRequestContext.class),
                    paramName, requestCtx);
        }
    }

    private ResultHandle loadMultipartPartType(BytecodeCreator method, String className, FieldInfo fieldInfo,
            ServerIndexedParameter param, ResultHandle requestCtx, ResultHandle paramName) {
        // Read static fields for type, genericType, and mediaType
        String fieldName = fieldInfo.name();
        ResultHandle typeClass = method.readStaticField(
                FieldDescriptor.of(className.replace('/', '.'), fieldName + "_type", Class.class));
        ResultHandle genericType = method.readStaticField(
                FieldDescriptor.of(className.replace('/', '.'), fieldName + "_genericType", java.lang.reflect.Type.class));
        ResultHandle mediaType = method.readStaticField(
                FieldDescriptor.of(className.replace('/', '.'), fieldName + "_mediaType", MediaType.class));

        if (param.isSingle()) {
            return method.invokeStaticMethod(
                    MethodDescriptor.ofMethod(MultipartSupport.class, "getConvertedFormAttribute",
                            Object.class, String.class, Class.class, java.lang.reflect.Type.class,
                            MediaType.class, ResteasyReactiveRequestContext.class),
                    paramName, typeClass, genericType, mediaType, requestCtx);
        } else {
            return method.invokeStaticMethod(
                    MethodDescriptor.ofMethod(MultipartSupport.class, "getConvertedFormAttributes",
                            List.class, String.class, Class.class, java.lang.reflect.Type.class,
                            MediaType.class, ResteasyReactiveRequestContext.class),
                    paramName, typeClass, genericType, mediaType, requestCtx);
        }
    }

    private ResultHandle invokeMultipartSupport(BytecodeCreator method, ResultHandle requestCtx,
            ResultHandle paramName, boolean single, String methodBaseName, Class<?> returnType) {
        if (single) {
            return method.invokeStaticMethod(
                    MethodDescriptor.ofMethod(MultipartSupport.class, methodBaseName,
                            returnType, String.class, ResteasyReactiveRequestContext.class),
                    paramName, requestCtx);
        } else {
            return method.invokeStaticMethod(
                    MethodDescriptor.ofMethod(MultipartSupport.class, methodBaseName + "s",
                            List.class, String.class, ResteasyReactiveRequestContext.class),
                    paramName, requestCtx);
        }
    }

    // Static utility methods (kept from original)
    private static MultipartFormParamExtractor.Type getMultipartFormType(ServerIndexedParameter param) {
        if (param.getType() != ParameterType.FORM) {
            return null;
        }
        AnnotationInstance partType = param.getAnns().get(ResteasyReactiveDotNames.PART_TYPE_NAME);
        String mimeType = null;
        if (partType != null && partType.value() != null) {
            mimeType = partType.value().asString();
            if (MediaType.TEXT_PLAIN.equals(mimeType)) {
                mimeType = null;
            }
        }
        if (param.getElementType().equals(FileUpload.class.getName())) {
            return MultipartFormParamExtractor.Type.FileUpload;
        } else if (param.getElementType().equals(File.class.getName())) {
            return MultipartFormParamExtractor.Type.File;
        } else if (param.getElementType().equals(Path.class.getName())) {
            return MultipartFormParamExtractor.Type.Path;
        } else if (param.getElementType().equals(String.class.getName())) {
            return MultipartFormParamExtractor.Type.String;
        } else if (param.getElementType().equals(InputStream.class.getName())) {
            return MultipartFormParamExtractor.Type.InputStream;
        } else if (param.getParamType().kind() == Kind.ARRAY
                && param.getParamType().asArrayType().constituent().kind() == Kind.PRIMITIVE
                && param.getParamType().asArrayType().constituent().asPrimitiveType().primitive() == Primitive.BYTE) {
            return MultipartFormParamExtractor.Type.ByteArray;
        } else if (mimeType != null && !mimeType.equals(MediaType.TEXT_PLAIN)) {
            return MultipartFormParamExtractor.Type.PartType;
        } else {
            return null;
        }
    }

    private ResultHandle convertParameter(BytecodeCreator method, ResultHandle value, ServerIndexedParameter param,
            FieldInfo fieldInfo) {
        ParameterConverterSupplier converter = param.getConverter();
        if (converter != null) {
            String converterFieldName = INIT_CONVERTER_FIELD_NAME + fieldInfo.name();
            String className = fieldInfo.declaringClass().name().toString().replace('.', '/');
            ResultHandle converterHandle = method.readStaticField(
                    FieldDescriptor.of(className, converterFieldName, ParameterConverter.class));
            return method.invokeInterfaceMethod(
                    MethodDescriptor.ofMethod(ParameterConverter.class, "convert", Object.class, Object.class),
                    converterHandle, value);
        }
        return value;
    }

    private ResultHandle loadParameter(BytecodeCreator method, ResultHandle ctx, FieldInfo fieldInfo,
            ServerIndexedParameter param, ParameterType paramType, String className) {
        ResultHandle paramName = method.load(param.getName());

        // Determine method name and parameters based on type
        String methodName;
        MethodDescriptor methodDesc;
        boolean encoded = fieldInfo.hasAnnotation(ResteasyReactiveDotNames.ENCODED);

        ResultHandle value;
        switch (paramType) {
            case FORM:
                // Check if this is a multipart parameter
                MultipartFormParamExtractor.Type multipartType = getMultipartFormType(param);
                if (multipartType != null) {
                    // Handle multipart parameter loading
                    ResultHandle requestCtx = method.checkCast(ctx, ResteasyReactiveRequestContext.class);
                    value = loadMultipartParameter(method, requestCtx, paramName, fieldInfo, param, multipartType, className);
                } else {
                    // Handle regular form parameter
                    methodDesc = MethodDescriptor.ofMethod(ResteasyReactiveInjectionContext.class, "getFormParameter",
                            Object.class, String.class, boolean.class, boolean.class);
                    value = method.invokeInterfaceMethod(methodDesc, ctx, paramName,
                            method.load(param.isSingle()), method.load(encoded));
                }
                break;
            case HEADER:
                methodDesc = MethodDescriptor.ofMethod(ResteasyReactiveInjectionContext.class, "getHeader",
                        Object.class, String.class, boolean.class);
                value = method.invokeInterfaceMethod(methodDesc, ctx, paramName, method.load(param.isSingle()));
                break;
            case MATRIX:
                methodDesc = MethodDescriptor.ofMethod(ResteasyReactiveInjectionContext.class, "getMatrixParameter",
                        Object.class, String.class, boolean.class, boolean.class);
                value = method.invokeInterfaceMethod(methodDesc, ctx, paramName,
                        method.load(param.isSingle()), method.load(encoded));
                break;
            case COOKIE:
                methodDesc = MethodDescriptor.ofMethod(ResteasyReactiveInjectionContext.class, "getCookieParameter",
                        String.class, String.class);
                value = method.invokeInterfaceMethod(methodDesc, ctx, paramName);
                break;
            case PATH:
                methodDesc = MethodDescriptor.ofMethod(ResteasyReactiveInjectionContext.class, "getPathParameter",
                        String.class, String.class, boolean.class);
                value = method.invokeInterfaceMethod(methodDesc, ctx, paramName, method.load(encoded));
                break;
            case QUERY:
                ResultHandle separator = param.getSeparator() != null ? method.load(param.getSeparator()) : method.loadNull();
                methodDesc = MethodDescriptor.ofMethod(ResteasyReactiveInjectionContext.class, "getQueryParameter",
                        Object.class, String.class, boolean.class, boolean.class, String.class);
                value = method.invokeInterfaceMethod(methodDesc, ctx, paramName,
                        method.load(param.isSingle()), method.load(encoded), separator);
                break;
            default:
                throw new IllegalStateException("Unexpected parameter type: " + paramType);
        }

        // Handle default value
        if (param.getDefaultValue() != null) {
            AssignableResultHandle result = method.createVariable(Object.class);

            // Check if value is null
            BranchResult nullCheck = method.ifNull(value);
            BytecodeCreator nullBranch = nullCheck.trueBranch();
            BytecodeCreator notNullBranch = nullCheck.falseBranch();

            // If null, use default value
            nullBranch.assign(result, nullBranch.load(param.getDefaultValue()));

            // If not null, check if it's an empty collection (for collection types)
            if (param.isObtainedAsCollection()) {
                ResultHandle collection = notNullBranch.checkCast(value, Collection.class);
                ResultHandle isEmpty = notNullBranch.invokeInterfaceMethod(
                        MethodDescriptor.ofMethod(Collection.class, "isEmpty", boolean.class),
                        collection);

                BranchResult emptyCheck = notNullBranch.ifNonZero(isEmpty);
                BytecodeCreator emptyBranch = emptyCheck.trueBranch();
                BytecodeCreator nonEmptyBranch = emptyCheck.falseBranch();

                // If empty, use default value
                emptyBranch.assign(result, emptyBranch.load(param.getDefaultValue()));
                // If not empty, use the value
                nonEmptyBranch.assign(result, value);
            } else {
                // Not a collection, just use the value
                notNullBranch.assign(result, value);
            }

            return result;
        }

        return value;
    }

    private void storeValue(BytecodeCreator method, String className, FieldInfo fieldInfo, ResultHandle value,
            ResultHandle thisRef, Map<String, AssignableResultHandle> recordVars, boolean isRecord) {
        String fieldTypeName = fieldInfo.type().name().toString();
        if (isRecord) {
            AssignableResultHandle var = recordVars.get(fieldInfo.name());
            method.assign(var, value);
        } else {
            method.writeInstanceField(
                    FieldDescriptor.of(className.replace('/', '.'), fieldInfo.name(), fieldTypeName),
                    thisRef, value);
        }
    }

    private ResultHandle getDefaultPrimitiveValue(BytecodeCreator method, Primitive primitive) {
        return switch (primitive) {
            case BOOLEAN -> method.load(false);
            case BYTE -> method.load((byte) 0);
            case CHAR -> method.load('\0');
            case DOUBLE -> method.load(0.0);
            case FLOAT -> method.load(0.0f);
            case INT -> method.load(0);
            case LONG -> method.load(0L);
            case SHORT -> method.load((short) 0);
        };
    }

}
