package org.jboss.resteasy.reactive;

/**
 * Marker interface that is used to indicate that an exception was generated by the client.
 *
 * This stops the server treating it as a WebApplicationException, so that client errors are not
 * interpreted as server responses.
 */
public interface ResteasyReactiveClientProblem {
}
