= Short title

* Status: [ pre:proposed | proposed | accepted | deprecated - reason: ... | superseded by [0005](0005-example.md)]
* Date: [YYYY-MM-DD when the decision was last updated]

== Context and Problem Statement

Considering the sophisticated ruleset `eclipse-format.xml`, there is a clear intent on how the code should look and feel.

However, there is often a misalignment if these guidelines are not suggested or enforced, as seen with tools like ESLint and Ktlint.
These tools address recurring patterns, and sometimes the rules and conventions are not just for cosmetic issues but rather for enabling smooth Git operations across multiple systems. 
For example, ensuring consistent line endings (`line-endings=lf`) or avoiding `unused/wildcard` imports, which are highly preferred to be avoided to enable precompile optimization.
This is one of the main goals of the project: to prioritize performance at all costs.

This high promise and expectation comes with a price, and as everything is interrelated, it impacts the entire workflow.
The most common solution is to introduce some kind of linter framework—in this case, Checkstyle, as it is highly used and well-established.

This approach would adhere to the `convention-over-configuration` principle and improve the onboarding of new developers, as well as reduce the recurring costs of mentioning coding guidelines or explaining how the plugin needs to be configured.

A simple example is `AvoidStarImport` and `UnusedImports`, as both address simple cases that should be avoided.
It is really hard to check imports manually without the computer's assistance. From these rules, we could build up and migrate from an optional formatting approach to ensuring the desired format is consistently applied.

https://github.com/quarkusio/quarkus/blob/main/independent-projects/ide-config/src/main/resources/eclipse-format.xml

== Decision Drivers (optional)

* driver 1
* driver 2

== Scenarios (optional)

intoroduce checkstyl/orther linter framework mininmal invasive only ensuing whats posible and then stp by step build the clean code ilands as well known from the best practed. big bang operations are imporsisble.

== Considered options (optional)

List of the considered options, if any.

== Decision

What is the change that we're proposing and/or doing?

* Reduce friction and effort in PR reviews by automating the enforcement of coding guidelines.
* Ensure a certain level of code quality.
* Avoid recurring issues from the past.

== Consequences

* **Build Time**: Slightly increased build time due to linting checks.
* **Human Interaction**: Reduced time spent communicating, applying, and observing guidelines manually.
* **Ease of Development**: Easier to maintain consistent code quality and onboard new developers. No initial setup is required, as Checkstyle works out of the box and will run with the build. There is also a CLI mode to apply fixes for misaligned coding, and easy-to-fix issues are resolved by automation, which helps reduce costs further.
