= Rename Reactive extensions

* Status: proposed
* Date: 2023-10-17 by @geoand
* Revised: 2024-01-12 by @gsmet, @cescoffier, @geoand, @maxandersen

== Context and Problem Statement

RESTEasy Reactive is the preferred REST stack in Quarkus, however in the almost 3 years since its release, we have seen
folks of all experience misunderstand its capabilities and being led to believe that it forces reactive programming on them.

With the advent of Virtual Threads in Java 19+, the problem becomes larger since in the minds of users, Reactive and Virtual Threads
are two different worlds.

The same problem applies to other extensions as well:

* Reactive Messaging
* Reactive Routes
* REST Client Reactive

The common theme here is that these extensions can work equally well with reactive and blocking code, but their name confuses users.

We have tried to clarify the situation with blog posts, talks and on the various communication channels, but there seems to be
no escaping the fact that "reactive" in the name primes people in a non-desirable way.

What we would like to do is to only use of the word "reactive" in extensions that are forcing (or preferring) a reactive programming model. This does not mean that all reactive extensions is affected by this change, only the ones that are not forcing a reactive programming model.

Examples of good and bad names are:

[%header,format="csv"]
|===
Extension, Good/Bad
quarkus-hibernate-reactive, Good
quarkus-resteasy-reactive, Bad
smallrye-reactive-messaging, Bad 
reactive-mysql-client, Good
|===


== Considered options

=== Do nothing

We can continue with the current situation, but that feels less than ideal given the recurrence of the problem.

=== Break users

We could simply rename the extensions without providing any backward compatibility with the old maven modules. This would likely cause a lot of pain - even in the presence of the Quarkus CLI update process, a lot of users won't use it.

=== Maintain compatibility

We can come up with new names for the Quarkus extensions while also providing Maven relocations for the existing artifacts.
This way users will be able to adapt to the new names at their own pace.

Another option would be to create new extensions that simply include the existing ones, but this does not seem to provide
any real benefit over relocations.

==== REST Client

The Reactive REST Client is a special case, because although clearly the best name to use is `quarkus-rest-client`, unfortunately that name is already taken by the legacy REST Client implemented in RESTEasy Classic. Thus the best option is if we could come up with a name base name for `quarkus-rest`, i.e. `quarkus-restless` or similar but thus far we have not been able to come up with a good name, that is better or as acceptable as `quarkus-rest`.



== Decision

The decision is that we MUST do something about removing the word "reactive" from the names of the extensions that are not forcing a reactive programming model. 

At a highlevel that means we will do the following:

* Rename current `smallrye-messaging` to `quarkus-messaging`
* Rename current `resteasy-reactive` to `quarkus-rest`
* Keep `reactive-routes` as it is primarily pushing reactive.
* Rename current `rest-client` to `quarkus-resteasy-client`
* Rename `rest-client-reactive` to `rest-client`
* TODO: rename all renmaing bits??


=== `smallrye-reactive-messaging` -> `quarkus-messaging`

[%header,format="csv"]
|===
Old, New
*smallrye-reactive*-messaging-kafka,*quarkus*-messaging-kafka
*smallrye-reactive*-messaging-mqtt,*quarkus*-messaging-mqtt
*smallrye-reactive*-messaging,*quarkus*-messsaging
*smallrye-reactive*-messaging-pulsar,*quarkus*-messaging-pulsar
*smallrye-reactive*-messaging-rabbitmq,*quarkus*-messaging-rabbitmq
*smallrye-reactive-messaging-amqp*,*quarkus*-messaging-amqp
|===

== `resteasy-reactive` -> `quarkus-rest`

[%header,format="csv"]
|===
Old, New
quarkus-*resteasy-reactive*,quarkus-*rest*
quarkus-*resteasy-reactive*-kotlin-serialization-common,quarkus-*rest*-kotlin-serialization-common
quarkus-*resteasy-reactive*-servlet,			quarkus-*rest*-servlet
quarkus-*resteasy-reactive*-jsonb-common,*quarkus-rest*-jsonb-common
quarkus-*resteasy-reactive*-kotlin,*quarkus-rest*-kotlin
rest-client-reactive-kotlin-serialization,*quarkus-rest*-client-kotlin-serialization
*resteasy-reactive*/jaxrs-client-reactive,*quarkus-rest*-client-jaxrs
quarkus-*resteasy-reactive*-jaxb,*quarkus-rest*-jaxb
quarkus-*resteasy-reactive*-jackson-common,*quarkus-rest*-jackson-common
quarkus-*resteasy-reactive*-links,*quarkus-rest*-links
quarkus-*resteasy-reactive*-qute,*quarkus-rest*-qute
quarkus-*resteasy-reactive*-kotlin-serialization,*quarkus-rest*-kotlin-serialization
quarkus-*resteasy-reactive*-jsonb,*quarkus-rest*-jsonb
quarkus-*resteasy-reactive*,*quarkus-rest*
quarkus-*resteasy-reactive*-common,*quarkus-rest*-common
quarkus-*resteasy-reactive*-jackson,*quarkus-rest*-jackson

*rest-client-reactive*-jsonb,*quarkus-rest-client*-jsonb (REUSE)
*rest-client-reactive*,*quarkus-rest-client* (REUSE)
*rest-client-reactive*-jackson,*quarkus-rest-clietn*-jackson (REUSE)
*rest-client-reactive*-jaxb,*quarkus-rest-client*-jaxb (REUSE)

|===

== `rest-client` -> `quarkus-resteasy-client`

[%header,format="csv"]
|===
Old, New
*rest*-client,		*quarkus-resteasy*-client
*rest*-client-config,		rest-client-config
*rest*-client-jackson,		*quarkus-resteasy*-client-jackson
*rest*-client-jaxb,		*quarkus-resteasy*-client-jaxb 
*rest*-client-jsonb,		*quarkus-resteasy*-client-jsonb 
*rest*-client-mutiny,		*quarkus-resteasy*-client-mutiny 
|===

== Related cleanup

[%header,format="csv"]
|===
Old, New
csrf-*reactive*,*quarkus-rest*-csrf
oidc-token-propagation-*reactive*,*quarkus-rest*-oidc-token-propagation
oidc-*client-reactive*-filter,*quarkus-rest-client*-filter-oidc
*quarkus*-oidc-*client*,*quarkus-resteasy-client*-oidc-filter
oidc-*client-reactive*-filter,*quarkus-rest-client*-oidc-filter
keycloak-admin-client-*reactive*,*quarkus*-keycloak-admin-*rest-client*
|===

* Rename all `quarkus-resteasy-reactive*` maven modules to `quarkus-rest*`
* Rename all `quarkus-rest-client-reactive*` maven modules to `quarkus-restful-client*`
** Also rename the extensions that rely on the REST Clients (like Keycloak Admin Client extensions)
* Rename all `quarkus-smallrye-reactive-messaging-` maven modules to `quarkus-messaging-`
* Rename all `quarkus-reactive-routes-` maven modules to `quarkus-http-routes-`
* No Java code changes should be made - all code should continue to reside in the same packages
* Introduce Maven relocations to allow for users not updating their poms
* Introduce a recipe that the Quarkus CLI can use during update
* Update quickstarts
* Update codestarts
* Update tooling to indicate proper older / newer relationship
* Write a new blog post explaining why we made the change
* Update old blog posts to mention the new name
* Update prominent Quarkus demo application and workshops
* Update GitHub labels
* Update bot configuration

== Consequences

* On the plus side, conveying the actual capabilities (blocking, non-blocking, Virtual Threads) of our stack should become easier.
** Furthermore, the new name aligns quite nicely with Java EE's Jakarta REST
* On the minus side, renaming is always confusing for users.
