= Phasing out legacy config classes

* Status: proposed
* Date: 2025-02-06
* Authors: @gsmet @radcortez

== Context and Problem Statement

We currently have two competing implementations to handle configuration properties in Quarkus extensions:

- The legacy config class approach: it uses **classes** annotated with `@io.quarkus.runtime.annotations.ConfigRoot` and **fields** annotated with `@io.quarkus.runtime.annotations.ConfigItem` for the properties.
- The new config interface approach: it uses **interfaces** annotated with `@io.smallrye.config.ConfigMapping` and `@io.quarkus.runtime.annotations.ConfigRoot` (for the config phase) and **methods** for the properties.

The latter approach is what we have been recommending for quite some time now (it actually requires a special flag for the extension annotation processor to use the legacy config class approach).

The old mechanism had a few issues that we wanted to fix, namely:

- Classes were mutable, whereas Quarkus configuration is immutable, causing hard-to-debug problems and unexpected behaviours.
- It only worked for extensions and in the context of Quarkus.

SmallRye Config provides the currently recommended mechanism which can be used in any context (even without Quarkus). Using an interface instead of class makes it clear that the Config cannot be changed.
On top of that, many of the new features were more straightforward to implement in this new model.

There has been a massive effort to migrate from the former approach to the latter and we are happy to announce we migrated all the Core configuration to the `@ConfigMapping` approach.
There are a few legacy classes left but they are there for compatibility purposes, for some config properties massively consumed outside of Quarkus that we didn't want to break (yet!).

At this stage, it is time to start planning phasing out the legacy approach so that:

- We avoid maintaining this code forever. It is complex and the bandwidth of the person maintaining it is limited.
- We avoid some bugs that were never fixed in the config class approach due to either limited bandwidth or high complexity.
- We reduce our startup footprint.

By phasing out, we mean that the code won't be there anymore and that the approach with `@ConfigRoot` annotated **classes** won't be functional anymore, including for external extensions.

The good thing is by migrating the Core configuration, we have loads of examples we can point people to and we are also very confident in the solidity of the `@ConfigMapping` code in SmallRye Config.

Roberto has also led an effort to improve the performances of the new approach and allow it to scale better and results are promising (and still improving).

The main goal of this ADR is to propose an approach for the transition that reduces friction.


== Potential difficulties

=== Transitioning

Transitioning to config interfaces is a well known and straightforward process.
It can be a bit tedious though for extensions with massive configuration or projects with a lot of extensions (Camel Quarkus comes to mind).

The main difficulty we identified is that in some extensions, we actually mutate the configuration, which was possible (but definitely not recommended!) for public fields and is not possible with the new interface/method approach.
It should concern very few extensions though and we need to stay away from this bad practice anyway.

=== Ecosystem

The Quarkus extension ecosystem is broad and diverse: some extensions are very well maintained and following the progress of Quarkus, some are lagging and adjusted when time permits.

If we phase out the legacy approach, we need the extension ecosystem to be ready for it.

For Quarkiverse extensions, the Quarkus community can be proactive as we can push changes there if needed.
Things become a bit more blurry for extensions hosted outside of the Quarkiverse for which we will need the maintainers to be doing the work.

=== Compatibility classes

During the migration, for a few key extensions, we decided to keep small and targeted config classes around to maintain the compatibility for all the extensions that consume this configuration (either as a CDI bean at runtime or during build time).
This is for instance the case of the HTTP configuration coming from Vert.x HTTP.

When we phase out the legacy approach, these classes will have to go: we need to make sure the extension ecosystem has moved to the new interfaces (or to a proper API if we put one in place).

== Proposed approach

Given all the items presented above, the key for this transition to be a success is communication and planning.
Here is the approach we recommend:

- Step 1 - Communicate first about where we introduced compatibility config classes and that people should consume the new config interface ASAP
- Step 2 - Communicate early about this upcoming transition
  - Blog post + post on quarkus-dev
  - Post in the Quarkiverse community discussions
  - Prepare a guide on how to do it. Make sure we add useful pointers with example pull requests.
  - Make sure we provide points of contact in the community for people having difficulties (or who just don't have the time to do it and want someone else to handle it)
  - Make sure we identify difficulties with potential solutions
  - Announce specific versions and dates for the tentative phase out so that people can schedule their work
- Step 3 - In version X.Y (with at least two months between previous communication and release), throw an error in the extension annotation processor when legacy `@ConfigRoot` classes are detected
  - It will allow us to detect the overall status in Ecosystem CI (at least for public extensions)
  - Maybe provide a way to forcefully override this error for one version, and drop it in the next version
  - Keep the support for legacy `@ConfigRoot` classes in quarkus-core though as we want the extensions to still work until they are updated
  - Announce it via blog post + post on quarkus-dev
- Step 4 - In version X.(Y + 2), if we are satisfied with the state of the Ecosystem, drop the legacy `@ConfigRoot` classes support from Quarkus entirely

== Proposed schedule

Given we were able to get everything ready for 3.19 and 3.20 LTS, here is the schedule we would suggest:

- Step 1 - For the 3.19 release on February 26th
- Step 2 - For the 3.19 release - and we should amplify the message when 3.20 LTS gets out
- Step 3 - For the 3.22 release on April 30th
- Step 4 - For the 3.24 release on June 25th
