# Keycloak Dev Services with SPIFFE feature enabled
quarkus.keycloak.devservices.features=spiffe
quarkus.keycloak.devservices.realm-name=quarkus-spiffe
quarkus.keycloak.devservices.create-realm=false
quarkus.keycloak.devservices.host-accessible-ports=${quarkus.spiffe-client.devservices.http-port}

# OIDC tenant (code flow) with SPIFFE JWT-SVID
quarkus.oidc.application-type=web-app
quarkus.oidc.credentials.jwt.source=spiffe-jwt
quarkus.oidc.authentication.redirect-path=/spiffe/code-flow
quarkus.oidc.client-id=quarkus-app-spiffe

# Named tenant for bearer token validation
quarkus.oidc.bearer.auth-server-url=${quarkus.oidc.auth-server-url}
quarkus.oidc.bearer.client-id=quarkus-app-spiffe
quarkus.oidc.bearer.tenant-paths=/spiffe/bearer

quarkus.log.category."org.htmlunit.css".level=ERROR

# OIDC client — client_credentials grant with SPIFFE JWT-SVID
quarkus.oidc-client.auth-server-url=${quarkus.oidc.auth-server-url}
quarkus.oidc-client.client-id=quarkus-app-spiffe
quarkus.oidc-client.credentials.jwt.source=spiffe-jwt
quarkus.oidc-client.grant.type=client
