package io.quarkus.rest.client.reactive.runtime;

import jakarta.ws.rs.ext.ContextResolver;

/**
 * This interface is implemented by autogenerated code to provide and register generic services in the client contexts.
 */
public interface ResteasyReactiveContextResolver<T> extends ContextResolver<T> {
}
