////
This document is maintained in the main Quarkus repository
and pull requests should be submitted there:
https://github.com/quarkusio/quarkus/tree/main/docs/src/main/asciidoc
////
////
TODO: See Quarkus documentation reference for details
- Finish a sentence like: "Create a ...", "How to ..." 
- ID should start with 'tutorial-'
- choose appropriate categories 
////
[id="tutorial-..."]
= Title using sentence capitalization
include::_attributes.adoc[]
:categories: ...
////
:extension-status: preview
TODO: uncomment the above for for an experimental or tech-preview content. 
The document header ends at the first blank line.
////

Describe what the learner will accomplish (examples: build, create, construct, deploy; not: “you will learn...”).
This short summary should help a reader determine if they want to engage with the content.

////
TODO: If this is a tutorial for an experimental or tech-preview extension, uncomment the following (otherwise delete)
include::{includes}/extension-status.adoc[]
////

== Prerequisites

////
TODO: If this tutorial will use dev tools, use the following common include:
include::{includes}/devtools/prerequisites.adoc[]
This file offers a few different variables that can be used to tweak what is shown.
////

- Materials, software, ...
- Whatever they should already have in hand to complete this set of steps

:sectnums:
:sectnumlevels: 3
== Outline steps

- xref:{doc-guides}/doc-create-tutorial.adoc[Tutorial: Create a tutorial]
- xref:{doc-guides}/doc-concepts.adoc#tutorial[Documentation concepts: Tutorials]
- xref:{doc-guides}/doc-reference.adoc[Quarkus documentation reference]

Each step should conclude with a comprehensible/observable result.

== Use the right language

- Give your learner plenty of clues to help confirm they are on the right track and orient themselves.
    - "Notice that...", "Remember that..."

- Provide minimal explanation of actions in the most basic language possible.
Link to more detailed explanation.
    - "We must always do x before we do y because… (see Explanation for more details)."

:sectnums!:
== Summary

In closing, describe (and admire, in a mild way) what your learner has accomplished (not: “you have learned…”).
