quarkus.grpc.clients.hello.host=localhost
quarkus.grpc.clients.hello.port=8444
quarkus.grpc.clients.hello.tls.enabled=true
quarkus.grpc.clients.hello.tls.trust-certificate-pem.certs=target/certs/grpc-tls-ca.crt
quarkus.grpc.clients.hello.tls.verify-hostname=false

quarkus.http.ssl.certificate.files=target/certs/grpc-tls.crt
quarkus.http.ssl.certificate.key-files=target/certs/grpc-tls.key
quarkus.http.insecure-requests=disabled
