package io.quarkus.grpc.deployment;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.List;

import org.jboss.jandex.Index;
import org.jboss.jandex.Indexer;
import org.junit.jupiter.api.Test;

import com.google.protobuf.DescriptorProtos;
import com.google.protobuf.Descriptors;
import com.google.protobuf.util.JsonFormat;

import io.quarkus.grpc.MutinyGrpc;
import io.vertx.core.buffer.Buffer;
import io.vertx.grpc.transcoding.TranscodingServiceMethod;
import io.vertx.grpc.transcoding.impl.MessageWeaver;
import io.vertx.grpc.transcoding.impl.config.HttpVariableBinding;

public class TranscodingMethodCollectionTest {

    @Test
    void nonEmptyWhenMutinyClassHasTranscodingFields() throws Exception {
        Indexer indexer = new Indexer();
        indexer.indexClass(WithTranscoding.class);
        indexer.indexClass(WithoutTranscoding.class);
        Index index = indexer.complete();

        assertThat(GrpcServerProcessor
                .collectTranscodingClassesHelper(index.getAllKnownImplementors("io.quarkus.grpc.MutinyGrpc")))
                .containsExactly(WithTranscoding.class.getName())
                .doesNotContain(WithoutTranscoding.class.getName());
    }

    // Simulates a MutinyXxxGrpc class generated by the protoc plugin when
    // google.api.http annotations are present.
    static class WithTranscoding implements MutinyGrpc {
        @SuppressWarnings("rawtypes")
        public static final TranscodingServiceMethod getSinglePath = null;
        @SuppressWarnings("rawtypes")
        public static final TranscodingServiceMethod getMultiPath = null;
    }

    // Simulates a MutinyXxxGrpc class with no transcoding annotations.
    static class WithoutTranscoding implements MutinyGrpc {

    }

    // --- MessageWeaver body mapping tests ---

    /**
     * Builds a minimal Descriptors.Descriptor for a message that has an
     * item_id (string) and an item (nested message with name/description),
     * without requiring proto file compilation.
     */
    private static Descriptors.Descriptor buildBodyRequestDescriptor() throws Exception {
        // ItemData: { name: string, description: string }
        DescriptorProtos.DescriptorProto itemDataProto = DescriptorProtos.DescriptorProto.newBuilder()
                .setName("ItemData")
                .addField(DescriptorProtos.FieldDescriptorProto.newBuilder()
                        .setName("name").setNumber(1).setType(DescriptorProtos.FieldDescriptorProto.Type.TYPE_STRING)
                        .setLabel(DescriptorProtos.FieldDescriptorProto.Label.LABEL_OPTIONAL))
                .addField(DescriptorProtos.FieldDescriptorProto.newBuilder()
                        .setName("description").setNumber(2).setType(DescriptorProtos.FieldDescriptorProto.Type.TYPE_STRING)
                        .setLabel(DescriptorProtos.FieldDescriptorProto.Label.LABEL_OPTIONAL))
                .build();

        // BodyRequest: { item_id: string, item: ItemData }
        DescriptorProtos.DescriptorProto bodyRequestProto = DescriptorProtos.DescriptorProto.newBuilder()
                .setName("BodyRequest")
                .addField(DescriptorProtos.FieldDescriptorProto.newBuilder()
                        .setName("item_id").setNumber(1).setType(DescriptorProtos.FieldDescriptorProto.Type.TYPE_STRING)
                        .setLabel(DescriptorProtos.FieldDescriptorProto.Label.LABEL_OPTIONAL))
                .addField(DescriptorProtos.FieldDescriptorProto.newBuilder()
                        .setName("item").setNumber(2).setType(DescriptorProtos.FieldDescriptorProto.Type.TYPE_MESSAGE)
                        .setLabel(DescriptorProtos.FieldDescriptorProto.Label.LABEL_OPTIONAL)
                        .setTypeName(".test.ItemData"))
                .build();

        DescriptorProtos.FileDescriptorProto fileProto = DescriptorProtos.FileDescriptorProto.newBuilder()
                .setName("test.proto")
                .setPackage("test")
                .setSyntax("proto3")
                .addMessageType(itemDataProto)
                .addMessageType(bodyRequestProto)
                .build();

        Descriptors.FileDescriptor fileDescriptor = Descriptors.FileDescriptor.buildFrom(fileProto,
                new Descriptors.FileDescriptor[0]);
        return fileDescriptor.findMessageTypeByName("BodyRequest");
    }

    @Test
    void bodyFieldIsWrappedUnderItemKey() throws Exception {
        Descriptors.Descriptor descriptor = buildBodyRequestDescriptor();
        Buffer rawBody = Buffer.buffer("{\"name\":\"Widget\",\"description\":\"A nice widget\"}");
        HttpVariableBinding itemIdBinding = new HttpVariableBinding(List.of("item_id"), "item-123");

        Buffer woven = MessageWeaver.weaveRequestMessage(rawBody, List.of(itemIdBinding), "item", descriptor);
        String json = woven.toString();

        // The body should be wrapped under "item", not at the top level
        assertThat(json).contains("\"item\"");
        assertThat(json).contains("\"item_id\"");
        assertThat(json).contains("item-123");
        assertThat(json).contains("Widget");

        // Must parse back cleanly as the full message
        com.google.protobuf.DynamicMessage.Builder builder = com.google.protobuf.DynamicMessage.newBuilder(descriptor);
        JsonFormat.parser().merge(json, builder);
        com.google.protobuf.DynamicMessage msg = builder.build();
        assertThat(msg.getField(descriptor.findFieldByName("item_id"))).isEqualTo("item-123");

        Descriptors.FieldDescriptor itemField = descriptor.findFieldByName("item");
        com.google.protobuf.DynamicMessage itemMsg = (com.google.protobuf.DynamicMessage) msg.getField(itemField);
        assertThat(itemMsg.getField(itemMsg.getDescriptorForType().findFieldByName("name"))).isEqualTo("Widget");
    }

    // --- Path matching tests: verifies bodyFieldPath and variable bindings are correct ---

    private static io.vertx.grpc.transcoding.impl.PathMatcher buildMatcher(
            io.vertx.grpc.transcoding.MethodTranscodingOptions options) {
        io.vertx.grpc.transcoding.impl.PathMatcherBuilder pmb = new io.vertx.grpc.transcoding.impl.PathMatcherBuilder();
        io.vertx.grpc.transcoding.impl.PathMatcherUtility.registerByHttpRule(pmb, options, "test.Service/Method");
        return pmb.build();
    }

    @Test
    void postWithBodyFieldPathIsPreservedInLookup() {
        io.vertx.grpc.transcoding.MethodTranscodingOptions options = new io.vertx.grpc.transcoding.MethodTranscodingOptions()
                .setHttpMethod(io.vertx.core.http.HttpMethod.POST)
                .setPath("/v1/items/{item_id}")
                .setBody("item");

        io.vertx.grpc.transcoding.impl.PathMatcherLookupResult result = buildMatcher(options).lookup("POST",
                "/v1/items/item-123", null);

        assertThat(result).isNotNull();
        assertThat(result.getBodyFieldPath()).isEqualTo("item");
        assertThat(result.getVariableBindings())
                .anyMatch(b -> b.getFieldPath().equals(List.of("item_id")) && b.getValue().equals("item-123"));
    }

    @Test
    void getWithNoBodyHasEmptyBodyFieldPath() {
        io.vertx.grpc.transcoding.MethodTranscodingOptions options = new io.vertx.grpc.transcoding.MethodTranscodingOptions()
                .setHttpMethod(io.vertx.core.http.HttpMethod.GET)
                .setPath("/v1/items/{item_id}");

        io.vertx.grpc.transcoding.impl.PathMatcherLookupResult result = buildMatcher(options).lookup("GET",
                "/v1/items/item-123", null);

        assertThat(result).isNotNull();
        assertThat(result.getBodyFieldPath()).isNullOrEmpty();
        assertThat(result.getVariableBindings())
                .anyMatch(b -> b.getFieldPath().equals(List.of("item_id")) && b.getValue().equals("item-123"));
    }

    @Test
    void wrongHttpMethodReturnsNoMatch() {
        io.vertx.grpc.transcoding.MethodTranscodingOptions options = new io.vertx.grpc.transcoding.MethodTranscodingOptions()
                .setHttpMethod(io.vertx.core.http.HttpMethod.GET)
                .setPath("/v1/items/{item_id}");

        io.vertx.grpc.transcoding.impl.PathMatcherLookupResult result = buildMatcher(options).lookup("POST",
                "/v1/items/item-123", null);

        assertThat(result).isNull();
    }

    // --- BridgeMessageDecoder tests: verifies the decoder handles woven JSON correctly ---

    /**
     * A PrototypeMarshaller backed by DynamicMessage so we can test
     * BridgeMessageDecoder without a compiled proto class.
     */
    private static class DynamicMarshaller
            implements io.grpc.MethodDescriptor.PrototypeMarshaller<com.google.protobuf.DynamicMessage> {
        private final com.google.protobuf.DynamicMessage prototype;

        DynamicMarshaller(Descriptors.Descriptor descriptor) {
            this.prototype = com.google.protobuf.DynamicMessage.getDefaultInstance(descriptor);
        }

        @Override
        public com.google.protobuf.DynamicMessage getMessagePrototype() {
            return prototype;
        }

        @Override
        public Class<com.google.protobuf.DynamicMessage> getMessageClass() {
            return com.google.protobuf.DynamicMessage.class;
        }

        @Override
        public com.google.protobuf.DynamicMessage parse(java.io.InputStream in) {
            try {
                return com.google.protobuf.DynamicMessage.newBuilder(prototype.getDescriptorForType())
                        .mergeFrom(in).build();
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        }

        @Override
        public java.io.InputStream stream(com.google.protobuf.DynamicMessage value) {
            return value.toByteString().newInput();
        }
    }

    @Test
    void bridgeDecoderFailsOnRawBodyWithBodyFieldMapping() throws Exception {
        Descriptors.Descriptor descriptor = buildBodyRequestDescriptor();
        io.vertx.grpcio.common.impl.BridgeMessageDecoder<com.google.protobuf.DynamicMessage> decoder = new io.vertx.grpcio.common.impl.BridgeMessageDecoder<>(
                new DynamicMarshaller(descriptor), null);

        // Raw body without body mapping applied: "name" is not a top-level field of BodyRequest
        io.vertx.grpc.common.GrpcMessage rawMsg = io.vertx.grpc.common.GrpcMessage.message(
                "identity", io.vertx.grpc.common.WireFormat.JSON,
                Buffer.buffer("{\"name\":\"Widget\",\"description\":\"A nice widget\"}"));

        org.junit.jupiter.api.Assertions.assertThrows(Exception.class, () -> decoder.decode(rawMsg),
                "BridgeMessageDecoder should reject raw body when body field mapping is expected");
    }

    @Test
    void bridgeDecoderSucceedsOnWovenBody() throws Exception {
        Descriptors.Descriptor descriptor = buildBodyRequestDescriptor();
        io.vertx.grpcio.common.impl.BridgeMessageDecoder<com.google.protobuf.DynamicMessage> decoder = new io.vertx.grpcio.common.impl.BridgeMessageDecoder<>(
                new DynamicMarshaller(descriptor), null);

        // Simulate MessageWeaver output: body wrapped under "item" + path binding applied
        HttpVariableBinding itemIdBinding = new HttpVariableBinding(List.of("item_id"), "item-123");
        Buffer woven = MessageWeaver.weaveRequestMessage(
                Buffer.buffer("{\"name\":\"Widget\",\"description\":\"A nice widget\"}"),
                List.of(itemIdBinding), "item", descriptor);

        io.vertx.grpc.common.GrpcMessage wovenMsg = io.vertx.grpc.common.GrpcMessage.message(
                "identity", io.vertx.grpc.common.WireFormat.JSON, woven);

        com.google.protobuf.DynamicMessage result = decoder.decode(wovenMsg);

        assertThat(result.getField(descriptor.findFieldByName("item_id"))).isEqualTo("item-123");
        Descriptors.FieldDescriptor itemField = descriptor.findFieldByName("item");
        com.google.protobuf.DynamicMessage item = (com.google.protobuf.DynamicMessage) result.getField(itemField);
        assertThat(item.getField(item.getDescriptorForType().findFieldByName("name"))).isEqualTo("Widget");
    }

    @Test
    void bridgeDecoderAcceptsJsonFormat() {
        // BridgeMessageDecoder.accepts() returns false for JSON — but ReadStreamAdapter
        // calls decode() unconditionally. Verify the decoder CAN handle JSON wire format.
        Descriptors.Descriptor descriptor = null;
        try {
            descriptor = buildBodyRequestDescriptor();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        io.vertx.grpcio.common.impl.BridgeMessageDecoder<com.google.protobuf.DynamicMessage> decoder = new io.vertx.grpcio.common.impl.BridgeMessageDecoder<>(
                new DynamicMarshaller(descriptor), null);

        // BridgeMessageDecoder.accepts() returns false for JSON, but decode() handles it
        assertThat(decoder.accepts(io.vertx.grpc.common.WireFormat.JSON)).isFalse();

        // Yet decode() itself CAN handle JSON if the payload is correctly structured
        Buffer woven = Buffer.buffer("{\"item_id\":\"item-123\",\"item\":{\"name\":\"Widget\"}}");
        io.vertx.grpc.common.GrpcMessage msg = io.vertx.grpc.common.GrpcMessage.message(
                "identity", io.vertx.grpc.common.WireFormat.JSON, woven);
        com.google.protobuf.DynamicMessage result = decoder.decode(msg);
        assertThat(result.getField(descriptor.findFieldByName("item_id"))).isEqualTo("item-123");
    }

    @Test
    void starBodyPassesFieldsToTopLevel() throws Exception {
        Descriptors.Descriptor descriptor = buildBodyRequestDescriptor();
        Buffer rawBody = Buffer.buffer("{\"item_id\":\"item-123\",\"name\":\"Widget\"}");
        HttpVariableBinding itemIdBinding = new HttpVariableBinding(List.of("item_id"), "item-123");

        // body: "*" means merge body fields directly into the message
        Buffer woven = MessageWeaver.weaveRequestMessage(rawBody, List.of(itemIdBinding), "*", descriptor);
        assertThat(woven.toString()).contains("item-123");
    }
}
