package io.quarkus.deployment.builditem;

import io.quarkus.builder.item.SimpleBuildItem;

/**
 * Marker build item for augmentation runs that only compare generated bytecode for reproducibility.
 */
public final class ReproducibilityCheckBuildItem extends SimpleBuildItem {
}
