quarkus.security.security-providers=BCFIPSJSSE

quarkus.http.ssl.client-auth=REQUIRED

quarkus.tls.key-store.other.type=BCFKS
quarkus.tls.key-store.other.provider=BCFIPS
quarkus.tls.key-store.other.path=server-keystore.jks
quarkus.tls.key-store.other.password=password
quarkus.tls.trust-store.other.type=BCFKS
quarkus.tls.trust-store.other.provider=BCFIPS
quarkus.tls.trust-store.other.path=server-truststore.jks
quarkus.tls.trust-store.other.password=password
quarkus.native.additional-build-args=-H:IncludeResources=.*\\.jks

quarkus.log.category."org.bouncycastle.jsse".min-level=TRACE
quarkus.log.category."org.bouncycastle.jsse".level=TRACE
quarkus.log.file.enabled=true
quarkus.log.file.format=%C - %s%n

#quarkus.native.additional-build-args=--trace-object-instantiation=org.bouncycastle.crypto.fips.FipsSecureRandom\\,java.security.SecureRandom
