quarkus.generate-code.grpc.scan-for-imports=com.google.protobuf:protobuf-java,com.google.api.grpc:proto-google-common-protos
quarkus.grpc.clients.transcoding-service.host=localhost
quarkus.grpc.clients.transcoding-service.port=9000
