package io.quarkus.avro.deployment;

import java.util.List;
import java.util.Optional;

import io.quarkus.runtime.annotations.ConfigPhase;
import io.quarkus.runtime.annotations.ConfigRoot;
import io.smallrye.config.ConfigMapping;

@ConfigMapping(prefix = "quarkus.avro")
@ConfigRoot(phase = ConfigPhase.BUILD_TIME)
public interface AvroBuildTimeConfig {

    /**
     * Fully qualified names of additional classes that are trusted for Avro deserialization.
     * <p>
     * Since Avro 1.12.2, classes are validated against a global security validator before they are deserialized.
     * Classes generated by Avro (annotated with {@code @org.apache.avro.specific.AvroGenerated}) are always trusted
     * and do not need to be listed here. Use this property to trust additional, non-generated classes.
     */
    Optional<List<String>> trustedClasses();

    /**
     * Package names whose classes are trusted for Avro deserialization.
     * <p>
     * Since Avro 1.12.2, classes are validated against a global security validator before they are deserialized.
     * Matching respects package boundaries: a value of {@code org.acme} trusts {@code org.acme.Foo} and classes in
     * any sub-package such as {@code org.acme.sub.Bar}, but does not trust {@code org.acme2.Foo}.
     * <p>
     * Classes generated by Avro (annotated with {@code @org.apache.avro.specific.AvroGenerated}) are always trusted
     * and do not need to be listed here.
     */
    Optional<List<String>> trustedPackages();
}
