quarkus.log.category.kafka.level=WARN
quarkus.log.category.\"org.apache.kafka\".level=WARN
quarkus.log.category.\"org.apache.zookeeper\".level=WARN

# enable health check
quarkus.kafka.health.enabled=true

kafka.auto.offset.reset=earliest

mp.messaging.outgoing.fruits-out.topic=fruits
mp.messaging.incoming.fruits-in.topic=fruits

mp.messaging.outgoing.people-out.topic=people
mp.messaging.outgoing.people-out.enable.idempotence=true
mp.messaging.outgoing.people-out.acks=all

quarkus.datasource.devservices.enabled=true
quarkus.hibernate-orm.packages=io.quarkus.it.kafka.fruit,io.quarkus.it.kafka.pet

quarkus.datasource."people".devservices.enabled=true
quarkus.hibernate-orm."people".datasource=people
quarkus.hibernate-orm."people".packages=io.quarkus.it.kafka.people

mp.messaging.incoming.pets-in.topic=pets
mp.messaging.incoming.pets-in.read-committed=true

###### Exactly-once transactional processing test
mp.messaging.outgoing.exactly-once-fruit-source.topic=exactly-once-fruit-in
mp.messaging.incoming.exactly-once-fruit-in.topic=exactly-once-fruit-in
mp.messaging.incoming.exactly-once-fruit-in.failure-strategy=ignore
mp.messaging.incoming.exactly-once-fruit-in.commit-strategy=ignore
mp.messaging.incoming.exactly-once-fruit-in.group.id=exactly-once-fruit-consumer
mp.messaging.outgoing.exactly-once-fruit-out.topic=exactly-once-fruit-out
mp.messaging.incoming.exactly-once-fruit-result.topic=exactly-once-fruit-out
mp.messaging.incoming.exactly-once-fruit-result.group.id=exactly-once-fruit-result-consumer
