#quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.data-management.init-script=import.sql
quarkus.hibernate-orm.data-management.strategy=create

quarkus.default-locale=en_US
quarkus.locales=en_US