quarkus.locales=en,hr-HR,en-US,fr-FR

quarkus.hibernate-orm.schema-management.strategy=drop-and-create

io.quarkus.it.hibernate.validator.injection.pattern=[^0-9]++

config-validation.not-validated.value=not-validated-value
config-validation.root-validated.value=root-validated-value
config-validation.nested-validated.value=nested-value
config-validation.nested-validated.nested.value=nested-level1-value
config-validation.nested-validated.nested.deeper.value=nested-level2-value
