# REST client - trust-all variant
quarkus.rest-client.h3-trust-all.url=https://localhost:${quarkus.http.test-ssl-port}
quarkus.rest-client.h3-trust-all.http3=true
quarkus.rest-client.h3-trust-all.tls-configuration-name=trust-all-tls
quarkus.tls.trust-all-tls.trust-all=true

# REST client - trust-store variant
quarkus.rest-client.h3-trust-store.url=https://localhost:${quarkus.http.test-ssl-port}
quarkus.rest-client.h3-trust-store.http3=true
quarkus.rest-client.h3-trust-store.tls-configuration-name=trust-store-tls
quarkus.tls.trust-store-tls.trust-store.p12.path=target/http3-dev-cert/http3-dev-truststore.p12
quarkus.tls.trust-store-tls.trust-store.p12.password=http3-dev-password
