quarkus.datasource.db-kind=oracle

# Reactive config
quarkus.datasource.reactive=true
# When this profile is set (opt-in), we will use an external DB instead of dev services (the default).
%external-db.quarkus.datasource.reactive.url=${oracle.reactive.url}
%external-db.quarkus.datasource.username=${oracle.username}
%external-db.quarkus.datasource.password=${oracle.password}
%external-db.quarkus.hibernate-orm.schema-management.strategy=drop-and-create

quarkus.security.users.embedded.enabled=true
quarkus.security.users.embedded.users.scott=jb0ss
quarkus.security.users.embedded.plain-text=true
quarkus.security.users.embedded.roles.scott=Admin,admin,Tester,user
