quarkus.datasource.db-kind=oracle
quarkus.datasource.jdbc.additional-jdbc-properties."oracle.jdbc.timezoneAsRegion"=false
# When this profile is set (opt-in), we will use an external DB instead of dev services (the default).
%external-db.quarkus.datasource.jdbc.url=${oracle.jdbc.url}
%external-db.quarkus.datasource.username=${oracle.username}
%external-db.quarkus.datasource.password=${oracle.password}
%external-db.quarkus.hibernate-orm.schema-management.strategy=drop-and-create

quarkus.datasource.ldap.db-kind=oracle
quarkus.datasource.ldap.username=SYSTEM
quarkus.datasource.ldap.password=hibernate_orm_test
quarkus.datasource.ldap.jdbc.url=jdbc:oracle:thin:@ldap://oid:5000/mydb1,cn=OracleContext,dc=myco,dc=com
quarkus.naming.enable-jndi=true
