// tag::quickly-install[]
The following will build all modules in the Quarkus repository except docs and test modules and install them in your local maven repository with the `999-SNAPSHOT` version:

[source,shell]
----
$ ./mvnw clean install -Dquickly \ #<1>
  -DskipTests \ # <2>
  -DskipITs \ # <3>
  -Dno-test-modules # <4>
----
<1> `-Dquickly` skips building documentation
<2> `-DskipTests` Skip maven surefire tests
<3> `-DskipITs` Skip maven failsafe integration tests
<4> `-Dno-test-modules` Do not build integration test modules
// end::quickly-install[]

// tag::quickly-install-docs[]
The following will build all modules in the Quarkus repository (except test modules) and install them in your local maven repository with the `999-SNAPSHOT` version:

[source,shell]
----
$ ./mvnw clean install -Dquickly \ #<1>
  -DskipTests \ # <2>
  -DskipITs \ # <3>
  -Dno-test-modules \ # <4>
  -DskipDocs=false # <5>
----
<1> `-Dquickly` skips building documentation
<2> `-DskipTests` Skip maven surefire tests
<3> `-DskipITs` Skip maven failsafe integration tests
<4> `-Dno-test-modules` Do not build integration test modules
<5> `-DskipDocs=false` re-enable the documentation build
// end::quickly-install-docs[]

