package io.quarkus.runtime.shutdown;

import java.util.List;
import java.util.Optional;

import io.quarkus.runtime.RuntimeValue;
import io.quarkus.runtime.annotations.Recorder;

/**
 * @deprecated Graceful shutdown is now handled by the service graph.
 *             Use {@link io.quarkus.core.StartContext#onGracefulPreShutdown(Runnable)} and
 *             {@link io.quarkus.core.StartContext#onGracefulShutdown(Runnable)} instead.
 */
@Deprecated(since = "4.0", forRemoval = true)
@Recorder
public class ShutdownRecorder {

    private static volatile List<ShutdownListener> shutdownListeners;
    private static volatile RuntimeValue<ShutdownConfig> shutdownConfig;
    private static volatile boolean delayEnabled;

    /**
     * @deprecated Use {@link io.quarkus.core.StartContext#onGracefulPreShutdown(Runnable)} and
     *             {@link io.quarkus.core.StartContext#onGracefulShutdown(Runnable)} instead.
     */
    @Deprecated(since = "4.0", forRemoval = true)
    public ShutdownRecorder(RuntimeValue<ShutdownConfig> shutdownConfig) {
        ShutdownRecorder.shutdownConfig = shutdownConfig;
    }

    /**
     * Store legacy shutdown listeners. Called from generated bytecode during runtime init.
     * The listeners are read by the service graph during shutdown.
     *
     * @deprecated Use {@link io.quarkus.core.StartContext#onGracefulPreShutdown(Runnable)} and
     *             {@link io.quarkus.core.StartContext#onGracefulShutdown(Runnable)} instead.
     */
    @Deprecated(since = "4.0", forRemoval = true)
    public void setListeners(List<ShutdownListener> listeners, boolean delayEnabled) {
        shutdownListeners = Optional.ofNullable(listeners).orElseGet(List::of);
        ShutdownRecorder.delayEnabled = delayEnabled;
    }

    /**
     * @deprecated No-op; graceful shutdown is now handled by the service graph.
     */
    @Deprecated(since = "4.0", forRemoval = true)
    public static void runShutdown() {
    }

    /**
     * Get the legacy shutdown listeners, or {@code null} if none were registered.
     * Used by the service graph to bridge legacy listeners into the new mechanism.
     *
     * @return the list of legacy listeners, or {@code null}
     */
    public static List<ShutdownListener> getLegacyListeners() {
        return shutdownListeners;
    }

    /**
     * Get the legacy shutdown config.
     *
     * @return the shutdown config runtime value, or {@code null}
     */
    public static ShutdownConfig getLegacyShutdownConfig() {
        RuntimeValue<ShutdownConfig> rv = shutdownConfig;
        return rv != null ? rv.getValue() : null;
    }

    /**
     * Get the legacy delay-enabled flag.
     *
     * @return whether the delay was enabled at build time
     */
    public static boolean isLegacyDelayEnabled() {
        return delayEnabled;
    }
}
