quarkus.log.category.kafka.level=WARN
quarkus.log.category.\"org.apache.kafka\".level=WARN
quarkus.log.category.\"org.apache.zookeeper\".level=WARN

# enable health check
quarkus.kafka.health.enabled=true

kafka.auto.offset.reset=earliest

mp.messaging.outgoing.fruits-out.topic=fruits
mp.messaging.incoming.fruits-in.topic=fruits

mp.messaging.outgoing.people-out.topic=people
mp.messaging.outgoing.people-out.enable.idempotence=true
mp.messaging.outgoing.people-out.acks=all

mp.messaging.incoming.pets-in.topic=pets
mp.messaging.incoming.pets-in.read-committed=true

###### Exactly-once reactive transactional processing test
mp.messaging.outgoing.exactly-once-fruit-source.topic=exactly-once-fruit-in
mp.messaging.incoming.exactly-once-fruit-in.topic=exactly-once-fruit-in
mp.messaging.incoming.exactly-once-fruit-in.group.id=exactly-once-fruit-consumer
mp.messaging.outgoing.exactly-once-fruit-out.topic=exactly-once-fruit-out
mp.messaging.incoming.exactly-once-fruit-result.topic=exactly-once-fruit-out
mp.messaging.incoming.exactly-once-fruit-result.group.id=exactly-once-fruit-result-consumer
