quarkus.log.level=WARN
quarkus.banner.enabled=false
quarkus.package.jar.type=uber-jar
quarkus.native.resources.includes=quarkus.properties
# Do not attempt to detect "unused removed beans" false positives during programmatic lookup
# at runtime to conserve some memory
# NTLMEngineImpl registration not needed GraalVM/Mandrel 25+
quarkus.native.additional-build-args=--initialize-at-run-time=\
org.apache.maven.wagon.shared.http.AbstractHttpClientWagon\\,\
org.apache.http.impl.auth.NTLMEngineImpl,\
-H:+UnlockExperimentalVMOptions,\
-H:ConfigurationResourceRoots=META-INF/native-image/\\,META-INF/native-image/io.quarkus/quarkus-cli/,\
-H:-UnlockExperimentalVMOptions
quarkus.arc.detect-unused-false-positives=false
quarkus.config.sources.system-only=true
# Needed to be able to download from the jbang catalog
quarkus.native.enable-https-url-handler=true
quarkus.log.category."io.quarkus.config".level=ERROR
