quarkus.datasource.db-kind=oracle
# When this profile is set (opt-in), we will use an external DB instead of dev services (the default).
%external-db.quarkus.datasource.reactive.url=${test.oracle.reactive.url}
%external-db.quarkus.datasource.username=${test.oracle.username}
%external-db.quarkus.datasource.password=${test.oracle.password}
%external-db.quarkus.datasource.db-version=${test.oracle.version}
%external-db.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
#Uncomment to connect over SSL/TLS
#quarkus.datasource.reactive.trust-all=true
#quarkus.datasource.reactive.mssql.ssl=true
