package org.jboss.shamrock.runtime;

/**
 * A task that is run on startup. Generally this will be provided by generated bytecode
 */
public interface StartupTask {

    void deploy(StartupContext context);

}
