package io.quarkus.test.config;

import org.eclipse.microprofile.config.spi.ConfigProviderResolver;
import org.junit.platform.launcher.LauncherSession;
import org.junit.platform.launcher.LauncherSessionListener;

import io.quarkus.deployment.dev.testing.TestConfigCustomizer;
import io.quarkus.runtime.LaunchMode;
import io.quarkus.runtime.configuration.ConfigUtils;
import io.smallrye.config.SmallRyeConfig;

/**
 * A JUnit {@link LauncherSessionListener}, used to register the initial test config. Test set up code can safely call
 * <code>ConfigProvider.getConfig()</code> to retrieve an instance of the Quarkus configuration.
 * <p>
 * The test config only contains sources known at bootstrap test time. For instance, config sources generated by
 * Quarkus are not available in the test config.
 */
public class ConfigLauncherSession implements LauncherSessionListener {
    @Override
    public void launcherSessionOpened(final LauncherSession session) {
        // Ideally the classloader would be correct when this is launched,
        // but for gradle, test class loading happens fairly shortly after this is called,
        // before the formal loading phase. To make that work, the TCCL may have been
        // set to the FCL by the time this is called, even though we want config to live on the app classloader
        ClassLoader old = Thread.currentThread().getContextClassLoader();
        Thread.currentThread().setContextClassLoader(this.getClass().getClassLoader());
        try {
            TestConfigProviderResolver resolver = new TestConfigProviderResolver(session.getStore());
            ConfigProviderResolver.setInstance(resolver);
            LaunchMode current = LaunchMode.current();
            LaunchMode.set(LaunchMode.TEST);
            SmallRyeConfig config = ConfigUtils.configBuilder()
                    .forClassLoader(Thread.currentThread().getContextClassLoader())
                    .withCustomizers(new TestConfigCustomizer(LaunchMode.TEST))
                    .withSources(new TestValueRegistryConfigSource(session.getStore()))
                    .build();
            LaunchMode.set(current);
            resolver.registerConfig(config, ClassLoader.getSystemClassLoader());
            if (ClassLoader.getSystemClassLoader() != Thread.currentThread().getContextClassLoader()) {
                resolver.registerConfig(config, Thread.currentThread().getContextClassLoader());
            }
            // Component Test registers a ClassLoader before this runs. This allows to also provide the Config in
            // that case as early as possible
            if (old != Thread.currentThread().getContextClassLoader()) {
                resolver.registerConfig(config, old);
            }
        } finally {
            Thread.currentThread().setContextClassLoader(old);
        }
    }

    @Override
    public void launcherSessionClosed(final LauncherSession session) {
        ConfigProviderResolver.setInstance(null);
    }
}
