package io.quarkus.dockerfiles.deployment;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.nio.charset.Charset;

public class DockerfileContent {

    public static String getJvmDockerfileContent(String from) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Generated by Quarkus\n");
        sb.append("FROM ").append(from).append("\n");
        sb.append(readResource("Dockerfile.jvm"));
        return sb.toString();
    }

    public static String getNativeDockerfileContent(String from) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Generated by Quarkus\n");
        sb.append("FROM ").append(from).append("\n");
        sb.append(readResource("Dockerfile.native"));
        return sb.toString();
    }

    private static String readResource(String resource) {
        try (InputStream in = DockerfileContent.class.getClassLoader().getResourceAsStream(resource)) {
            return new String(in.readAllBytes(), Charset.defaultCharset());
        } catch (IOException ioe) {
            throw new UncheckedIOException(ioe);
        }
    }
}
