quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:run-mode
quarkus.hibernate-orm.database.generation=none
quarkus.http.host=127.0.0.1
quarkus.http.port=0
quarkus.liquibase.migrate-at-start=false
