package io.quarkus.smallrye.openapi.deployment.spi;

import io.quarkus.builder.item.MultiBuildItem;
import io.quarkus.builder.item.SimpleBuildItem;
import io.smallrye.openapi.api.OpenApiDocument;
import io.smallrye.openapi.api.SmallRyeOpenAPI;

/**
 * The final OpenAPI Document as generated by the Extension. This only represents the default OpenAPI document, meaning the document with name matching {@link OpenAPISPIConstants#DEFAULT_DOCUMENT_NAME}. If you need access to the other named OpenAPI documents, see {@link OpenApiNamedDocumentBuildItem}.
 * @deprecated use {@link OpenApiNamedDocumentBuildItem} directly, which can represent all the configured OpenAPI documents of the application. You can use {@link OpenApiNamedDocumentBuildItem#isDefaultDocument()} to quickly figure out the default document.
 */
@Deprecated
public final class OpenApiDocumentBuildItem extends SimpleBuildItem {

    private final OpenApiDocument openApiDocument;
    private final SmallRyeOpenAPI smallRyeOpenAPI;

    public OpenApiDocumentBuildItem(OpenApiDocument openApiDocument, SmallRyeOpenAPI smallRyeOpenAPI) {
        this.openApiDocument = openApiDocument;
        this.smallRyeOpenAPI = smallRyeOpenAPI;
    }


    public OpenApiDocument getOpenApiDocument() {
        return openApiDocument;
    }

    public SmallRyeOpenAPI getSmallRyeOpenAPI() {
        return smallRyeOpenAPI;
    }
}
