package io.quarkus.smallrye.openapi.deployment.spi;

import io.quarkus.builder.item.MultiBuildItem;
import io.quarkus.builder.item.SimpleBuildItem;
import io.smallrye.openapi.api.OpenApiDocument;
import io.smallrye.openapi.api.SmallRyeOpenAPI;

/**
 * The final OpenAPI Documents as generated by the extension.
 */
public final class OpenApiNamedDocumentBuildItem extends MultiBuildItem {

    private final String documentName;
    private final SmallRyeOpenAPI smallRyeOpenAPI;

    public OpenApiNamedDocumentBuildItem(String documentName, SmallRyeOpenAPI smallRyeOpenAPI) {
        this.documentName = documentName;
        this.smallRyeOpenAPI = smallRyeOpenAPI;
    }

    public String getDocumentName() {
        return documentName;
    }

    public SmallRyeOpenAPI getSmallRyeOpenAPI() {
        return smallRyeOpenAPI;
    }

    public boolean isDefaultDocument() {
        return OpenAPISPIConstants.DEFAULT_DOCUMENT_NAME.equals(documentName);
    }
}
