package io.quarkus.core;

import java.lang.invoke.MethodHandles;

import io.smallrye.common.constraint.Assert;

/**
 * Constant bootstraps for Quarkus generated bytecode.
 */
public final class Bootstraps {
    private Bootstraps() {
    }

    /**
     * Load a class by its descriptor, even if it is not directly accessible from the caller.
     * The class must be visible to the caller's class loader.
     * In a modular Quarkus app, his usually means that the target type must be in a
     * package that is exported to the caller.
     * This method may be used to load primitive or array types as well.
     *
     * @param lookup the lookup of the caller (must not be {@code null})
     * @param descriptor the descriptor string of the class to load (must not be {@code null})
     * @param type always {@code Class.class}
     * @return the loaded class
     * @throws NoClassDefFoundError if the class could not be loaded
     * @throws IllegalArgumentException if {@code type} is the wrong type, {@code descriptor} is invalid,
     *         or a required argument was {@code null}
     */
    public static Class<?> loadClass(MethodHandles.Lookup lookup, String descriptor, Class<Class<?>> type) {
        Assert.checkNotNullParam("lookup", lookup);
        Assert.checkNotNullParam("descriptor", descriptor);
        Assert.checkNotNullParam("type", type);
        if (!Class.class.isAssignableFrom(type)) {
            throw new IllegalArgumentException("Invalid type for bootstrap");
        }
        ClassLoader cl = lookup.lookupClass().getClassLoader();
        return loadClassByDescriptor(cl, descriptor);
    }

    private static Class<?> loadClassByName(final String className, final ClassLoader cl) {
        try {
            return Class.forName(className, false, cl);
        } catch (ClassNotFoundException e) {
            NoClassDefFoundError error = new NoClassDefFoundError(e.getMessage());
            error.setStackTrace(e.getStackTrace());
            error.initCause(e.getCause());
            throw error;
        }
    }

    private static Class<?> loadClassByDescriptor(final ClassLoader cl, final String className) {
        return switch (className.charAt(0)) {
            case 'B' -> byte.class;
            case 'C' -> char.class;
            case 'D' -> double.class;
            case 'F' -> float.class;
            case 'I' -> int.class;
            case 'J' -> long.class;
            case 'S' -> short.class;
            case 'V' -> void.class;
            case 'Z' -> boolean.class;
            case '[' -> loadClassByDescriptor(cl, className.substring(1)).arrayType();
            case 'L' -> loadClassByName(className.substring(1, className.length() - 1).replace('/', '.'), cl);
            default -> throw new IllegalArgumentException("Invalid class name: " + className);
        };
    }
}
