package io.quarkus.hibernate.accessor.runtime;

import io.quarkus.runtime.annotations.ConfigPhase;
import io.quarkus.runtime.annotations.ConfigRoot;
import io.smallrye.config.ConfigMapping;
import io.smallrye.config.WithDefault;

/**
 * Build-time selection of the Hibernate accessor strategy.
 */
@ConfigMapping(prefix = "quarkus.hibernate-accessor")
@ConfigRoot(phase = ConfigPhase.BUILD_AND_RUN_TIME_FIXED)
public interface HibernateAccessorBuildTimeConfig {

    /**
     * The accessor strategy to use.
     *
     * - {@code reflection-free} (default): use generated bytecode accessors, throw on unrecognized members.
     * - {@code reflection-free-with-fallback}: use generated bytecode accessors, fall back to reflection for unrecognized
     * members.
     * - {@code reflection}: use pure reflection-based accessors, no bytecode generation.
     */
    @WithDefault("reflection-free")
    HibernateAccessorStrategy strategy();
}
