quarkus.application.name=observation-micrometer-opentelemetry-integration-test

# Speed up tests
quarkus.otel.bsp.schedule.delay=100
quarkus.otel.bsp.export.timeout=5s
quarkus.otel.metric.export.interval=100ms
quarkus.observation.print-out=true
quarkus.log.category."io.quarkus.opentelemetry.runtime.QuarkusContextStorage".level=DEBUG
quarkus.log.category."io.quarkus.opentelemetry.runtime.MDCEnabledContextStorage".level=DEBUG