quarkus.log.handler.open-telemetry.enabled=true
quarkus.otel.exporter.otlp.traces.endpoint=http://localhost:4317
quarkus.otel.exporter.otlp.logs.endpoint=http://localhost:4317
quarkus.otel.logs.exporter=otlp