////
This guide is maintained in the main Quarkus repository
and pull requests should be submitted there:
https://github.com/quarkusio/quarkus/tree/master/docs/src/main/asciidoc
////
= Quarkus - Amazon Lambda HTTP Applications 

include::./attributes.adoc[]


The `quarkus-amazon-lambda-http` extension allows you to write microservices with Resteasy (JAX-RS),
Undertow (servlet), or Vert.x Web and make these microservices deployable to Amazon AWS using
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/what-is-sam.html[Amazon's SAM] framework.

== Prerequisites

To complete this guide, you need:

* less than 15 minutes
* JDK 1.8 (Azure requires JDK 1.8)
* Apache Maven 3.5.3+
* https://aws.amazon.com[An Amazon AWS account]
* https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-reference.html#serverless-sam-cli[Amazon SAM CLI]

== Getting Started

This guide can be used on existing projects or new projects.  Whether the project is a new green field project or you're
attempting to migrate an existing application, this guide will walk you through the steps necessary to use Quarkus powered
applications on Amazon's infrastructure.

=== New Projects

The simplest scenario is when starting a completely new project.  Once you've <<getting-started-guide.adoc,generated>> a new
Quarkus project, you'll need to configure your application for deployment to Amazon.  The steps to achieve this are beyond
the scope of this document but you can find the full guide on
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-getting-started.html[Amazon's website].

For the purposes of this guide, we'll be using RESTEasy and maven.