////
This guide is maintained in the main Quarkus repository
and pull requests should be submitted there:
https://github.com/quarkusio/quarkus/tree/main/docs/src/main/asciidoc
////
= Azure Functions with RESTEasy Reactive, Undertow, or Reactive Routes
:extension-status: preview
include::_attributes.adoc[]
:categories: cloud
:summary: Deploy Vert.x Web, Servlet, or RESTEasy microservices as a Microsoft Azure Function.

The `quarkus-azure-functions-http` extension allows you to write microservices with RESTEasy Reactive (our Jakarta REST implementation),
Undertow (servlet), Reactive Routes, or xref:funqy-http.adoc[Funqy HTTP] and make these microservices deployable to the Azure Functions runtime.

One azure function deployment can represent any number of Jakarta REST, servlet, Reactive Routes, or xref:funqy-http.adoc[Funqy HTTP] endpoints.

include::{includes}/extension-status.adoc[]

NOTE: Only text based media types are supported at the moment as Azure Functions HTTP Trigger for Java does not support a binary format

== Prerequisites

include::{includes}/prerequisites.adoc[]
* https://azure.microsoft.com[An Azure Account].  Free accounts work.
* https://learn.microsoft.com/en-us/azure/azure-functions/functions-run-local#v2[Azure Functions Core Tools] version 4.x
* https://docs.microsoft.com/en-us/cli/azure/install-azure-cli[Azure CLI Installed]

== Solution

This guide walks you through running a maven project that can deploy a Resteasy Reactive endpoint to Azure Functions.
While only Jakarta REST is provided as an example, you can easily replace it with the HTTP framework of your choice.

== Creating the Maven Deployment Project

You can download the example code from Quarkus's application generator at https://code.quarkus.io/d?e=azure-functions-http&cn=code.quarkus.io[this link].

You can also generate this example with the Quarkus CLI:

[source,bash,subs=attributes+]
----
quarkus create app --extension=quarkus-azure-functions-http
----

== Login to Azure

If you don't log in to Azure you won't be able to deploy.

[source,bash,subs=attributes+]
----
az login
----

== Quarkus dev mode

Quarkus dev mode works by just running your application as a HTTP endpoint.

[source,bash,subs=attributes+]
----
./mvnw clean package quarkus:dev
----



== Run locally in Azure Functions simulated environment

If you want to try your app with a simulated local Azure Functions environment, you can
use this command

[source,bash,subs=attributes+]
----
./mvnw clean package azure-functions:run
----

Note that you must have the https://learn.microsoft.com/en-us/azure/azure-functions/functions-run-local#v2[Azure Functions Core Tools]
installed for this to work!

== Deploy to Azure

The `pom.xml` you generated in the previous step pulls in the `azure-functions-maven-plugin`.  Running maven package
generates config files and a staging directory required by the `azure-functions-maven-plugin`.  Here's
how to execute it.

[source,bash,subs=attributes+]
----
./mvnw clean package azure-functions:deploy
----

If deployment is a success, the azure plugin will tell you the base URL to access your function.

i.e.
[source]
----
[INFO] HTTP Trigger Urls:
[INFO] 	 QuarkusHttp : https://{appName}.azurewebsites.net/api/{*path}
----

The URL to access the service would be

https://{appName}.azurewebsites.net/api/hello

== Extension maven dependencies

You must include the `quarkus-azure-functions-http` extension as this is a generic bridge between the Azure Functions
runtime and the HTTP framework you are writing your microservices in.

== Azure Deployment Descriptors

Templates for Azure Functions deployment descriptors (`host.json`, `function.json`) are within
the base directory of the project. Edit them as you need to.  Rerun the build when you are ready.

[#config-azure-paths]
== Configuring Root Paths

The default route prefix for an Azure Function is `/api`.  All of your Jakarta REST, Servlet, Reactive Routes, and xref:funqy-http.adoc[Funqy HTTP] endpoints must
explicitly take this into account.  In the generated project this is handled by the
`quarkus.http.root-path` switch in `application.properties`

