////
This guide is maintained in the main Quarkus repository
and pull requests should be submitted there:
https://github.com/quarkusio/quarkus/tree/main/docs/src/main/asciidoc
////
= Azure Functions
:extension-status: preview
include::_attributes.adoc[]
:categories: cloud
:summary: Integrate Quarkus with the Microsoft Azure functions that you have written.
:topics: azure,serverless,function,cloud
:extensions: io.quarkus:quarkus-azure-functions

The `quarkus-azure-functions` extension is a simple integration point between Azure Functions
and Quarkus.  It interacts with Azure Functions runtime to bootstrap Quarkus and turns any
Azure Functions class you write into a CDI/ArC bean.

This allows you to inject any service or component initialized by Quarkus directly into your function
classes. You can also change the lifecycle of your function class from request scoped (the default)
to application scoped too if you want your function class to be a singleton.

include::{includes}/extension-status.adoc[]

[source, java]
----
import com.microsoft.azure.functions.ExecutionContext;
import com.microsoft.azure.functions.HttpMethod;
import com.microsoft.azure.functions.HttpRequestMessage;
import com.microsoft.azure.functions.HttpResponseMessage;
import com.microsoft.azure.functions.HttpStatus;
import com.microsoft.azure.functions.annotation.AuthorizationLevel;
import com.microsoft.azure.functions.annotation.FunctionName;
import com.microsoft.azure.functions.annotation.HttpTrigger;

import jakarta.inject.Inject;
import java.util.Optional;

public class Function {
    @Inject
    GreetingService service;

    @FunctionName("HttpExample")
    public HttpResponseMessage run(
            @HttpTrigger(
                name = "req",
                methods = {HttpMethod.GET, HttpMethod.POST},
                authLevel = AuthorizationLevel.ANONYMOUS)
                HttpRequestMessage<Optional<String>> request,
            final ExecutionContext context) {

        // Parse query parameter
        final String query = request.getQueryParameters().get("name");
        final String name = request.getBody().orElse(query);

        if (name == null) {
            return request.createResponseBuilder(HttpStatus.BAD_REQUEST).body("Please pass a name on the query string or in the request body").build();
        } else {
            return request.createResponseBuilder(HttpStatus.OK).body(service.greeting(name)).build();
        }
    }
}
----

== Prerequisites

include::{includes}/prerequisites.adoc[]
* https://azure.microsoft.com[An Azure Account].  Free accounts work.
* https://learn.microsoft.com/en-us/azure/azure-functions/functions-run-local#v2[Azure Functions Core Tools] version 4.x
* https://docs.microsoft.com/en-us/cli/azure/install-azure-cli[Azure CLI Installed]

== Solution

This guide walks you through running a Maven project that can deploy an HTTP Trigger Azure Function class.
This function class injects a CDI bean service that generates a greeting message that is passed back
to the client.

== Creating the Maven/Gradle Project

First, we need a new project. Create a new project with the following command:

:create-app-artifact-id: azure-functions-quickstart
:create-app-extensions: quarkus-azure-functions
:create-app-code:
include::{includes}/devtools/create-app.adoc[]

This command generates a project structure importing the Quarkus Azure Functions HTTP extension.
It includes an example.

== Examining the project

If you open the `pom.xml` or `build.gradle` build file of the generated project, you'll see that
the project is similar to any other Quarkus project.
The `quarkus-azure-functions` extension is the integration point between
Quarkus and Azure Functions. It registers callbacks with the Azure Functions runtime to bootstrap
Quarkus and to set up Quarkus/ArC as the function factory for your function classes.

The current implementation of the `quarkus-azure-functions` extension no longer requires the
`azure-functions-maven-plugin` or Gradle equivalent. Local development and Azure Functions packaging and
deployment is now all done by Quarkus.

Build configuration is now all within `application.properties`. The only required configuration switch
is `quarkus.azure-functions.app-name`.

== Azure Deployment Descriptors

The Azure Functions `host.json` deployment descriptor is automatically
generated, but if you need to override it, declare it in the root directory of the project and
rerun the build when you are ready.

== Quarkus dev mode

Quarkus dev mode does not work currently with Azure Functions.

== Run locally in Azure Functions local environment

If you want to try your app with a local Azure Functions environment, you can
use this command:

include::{includes}/devtools/run.adoc[]

[TIP]
====
Gradle is a bit quirky with process management, so you need the `--no-daemon` switch, or control-c will not
destroy the process cleanly, and you'll have open ports.
====

[NOTE]
====
You must have the https://learn.microsoft.com/en-us/azure/azure-functions/functions-run-local#v2[Azure Functions Core Tools]
installed for this to work.
====

The URL to access the example would be:

https://localhost:8081/HttpExample?name=Bill

== Quarkus Integration Testing

You can implement integration tests using `@QuarkusIntegrationTest` functionality.  When these
integration tests run, the local Azure Functions environment will be spun up for the duration of integration testing.

[source,bash,subs=attributes+,role="primary asciidoc-tabs-sync-maven"]
.Maven
----
./mvnw verify
----
[source,bash,subs=attributes+,role="secondary asciidoc-tabs-sync-gradle"]
.Gradle
----
./gradlew --info quarkusIntTest
----

[TIP]
====
Make sure any integration tests you execute with Maven use the `*IT.java` file pattern so that regular builds do not execute
the test.
====

[TIP]
====
Make sure any integration tests you execute with Gradle are located within `src/integrationTest/java`. Integration
tests that exist in `src/test` will run with normal build and fail.
====

== Login to Azure

To be able to deploy your application to Azure, log in to Azure:

[source,bash,subs=attributes+]
----
az login
----

== Deploy to Azure

The `quarkus-azure-functions` extension handles all the work to deploy to Azure. By default,
Quarkus will use the Azure CLI in the background to authenticate and deploy to Azure. If you have
multiple subscriptions associated with your account, you must set the `quarkus.azure-functions.subscription-id`
property in your `application.properties` file to the subscription you want to use.
For other authentication mechanisms and deployment options, see our config properties <<#configuration-reference>>.

To deploy your application, after you built your project, execute:

[source,bash,subs=attributes+,role="primary asciidoc-tabs-sync-maven"]
.Maven
----
./mvnw quarkus:deploy
----
[source,bash,subs=attributes+,role="secondary asciidoc-tabs-sync-gradle"]
.Gradle
----
./gradlew --info deploy
----

[TIP]
====
For Gradle, you must use the `--info` switch to see this output.
====

If deployment is a success, Quarkus will output the endpoint URL of the example function to the console:

[source]
----
[INFO] HTTP Trigger Urls:
[INFO] 	 HttpExample : https://{appName}.azurewebsites.net/api/httpexample
----

The URL to access the service would be: `https://{appName}.azurewebsites.net/api/HttpExample`

[[configuration-reference]]
== Azure Functions Configuration Reference

include::{generated-dir}/config/quarkus-azure-functions.adoc[leveloffset=+1, opts=optional]
