////
This document is maintained in the main Quarkus repository, and pull requests should be submitted there:
https://github.com/quarkusio/quarkus/tree/main/docs/src/main/asciidoc
////
[id="config-yaml"]
= Configure Quarkus applications by using a YAML file
include::_attributes.adoc[]
:diataxis-type: howto
:categories: core
:summary: Optionally, you can configure your application properties with an `application.yaml` file instead of the default `application.properties` file.

[id="overview"]
== Overview

This guide introduces the use of a YAML configuration file, `application.yaml`, as an alternative to the traditional `application.properties` file for application configuration. Functionality remains consistent across both formats.

[id="proc_enabling-yaml-configuration"]
== Enabling YAML configuration

To enable support for a `application.yaml` file, add the `quarkus-config-yaml` extension to the `pom.xml` or `build.gradle` file in your project.

.Prerequisites

include::{includes}/prerequisites.adoc[]
* A {project-name} Maven project.

.Procedure

. Add the `quarkus-config-yaml` extension to your project:
+
--
:add-extension-extensions: quarkus-config-yaml
include::{includes}/devtools/extension-add.adoc[]

Or, add the following dependency to your project:

[source,xml,role="primary asciidoc-tabs-target-sync-cli asciidoc-tabs-target-sync-maven"]
.pom.xml
----
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-config-yaml</artifactId>
</dependency>
----

[source,gradle,role="secondary asciidoc-tabs-target-sync-gradle"]
.build.gradle
----
implementation("io.quarkus:quarkus-config-yaml")
----
--
. Create the `src/main/resources/application.yaml` file.
+
TIP: You can use the `yml` or `yaml` file extension.

. To avoid potential confusion, remove the `src/main/resources/application.properties` file.
+
NOTE: If both files are present, the values of properties in `application.yaml` override any duplicate properties in `application.properties`.

[id="proc_using-object-configuration-with-yaml"]
== Using object configuration with YAML

In the YAML configuration file, you can define an element inside an existing element to set configuration properties for your {project-name} application.

.Prerequisites

include::{includes}/prerequisites.adoc[]
* A {project-name} Maven project.
* A PostgreSQL data source.
* The following extensions as dependencies in your project's `pom.xml` or `build.gradle` file:
** `quarkus-rest-client`
** `quarkus-jdbc-postgresql`
** `quarkus-config-yaml`

.Procedure

. Open the `src/main/resources/application.yaml` configuration file.

. Add configuration properties to your `application.yaml` file.
+
.Example configuration properties
[source,yaml]
----
# Properties that configure the JDBC data source driver of your PostgreSQL data source
quarkus:
  datasource:
    url: jdbc:postgresql://localhost:5432/some-database
    driver: org.postgresql.Driver
    username: quarkus
    password: quarkus

  hibernate-orm:
    database:
      generation: drop-and-create

  oidc:
    enabled: true
    auth-server-url: http://localhost:8180/auth/realms/quarkus
    client-id: app


app:
  frontend:
    oidc-realm: quarkus
    oidc-app: app
    oidc-server: http://localhost:8180/auth

# With configuration profiles
"%test":
   quarkus:
     oidc:
       enabled: false
     security:
        users:
            file:
              enabled: true
              realm-name: quarkus
              plain-text: true

# Property that configures the URL of the endpoint to which the rest client sends requests
org:
  acme:
    restclient:
      CountriesService/mp-rest/url: https://restcountries.eu/rest

# Property that configures the log message level for your application
quarkus:
  log:
    category:


# For configuration property names that use quotes, do not split the string inside the quotes
quarkus:
  log:
    category:
      "io.quarkus.category":
        level: INFO


# REST Client configuration property
quarkus:
  rest-client:
    url: https://stage.code.quarkus.io/api
    org.acme.rest.client.ExtensionsService:

----
+
You can use comments to describe configuration properties.
+
[NOTE]
====
Always use spaces to indent the properties in your YAML configuration file.
YAML does not support using tabs for indentation.
====

=== Additional examples of configuration properties

[source, yaml]
----
quarkus:
  datasource:
    url: jdbc:postgresql://localhost:5432/quarkus_test

  hibernate-orm:
    database:
      generation: drop-and-create

  oidc:
    enabled: true
    auth-server-url: http://localhost:8180/auth/realms/quarkus
    client-id: app


app:
  frontend:
    oidc-realm: quarkus
    oidc-app: app
    oidc-server: http://localhost:8180/auth

# With configuration profiles
"%test":
   quarkus:
     oidc:
       enabled: false
     security:
        users:
            file:
              enabled: true
              realm-name: quarkus
              plain-text: true
----

[id="proc_using-configuration-profiles-with-yaml"]
== Using configuration profiles with YAML

As you can see in the previous snippet, you can use xref:config-reference.adoc#profiles[profiles] in YAML. The profile
key requires double quotes: `"%test"`. This is because YAML does not support keys starting with `%`.

Everything under the `"%test"` key is only enabled when the `test` profile is active. For example, in the previous
snippet it disables OIDC (`quarkus.oidc.enabled: false`), whereas without the `test` profile, it would be enabled.

As for the Java Properties format, you can define your own profile:

[source, yaml]
----
quarkus:
  http:
    port: 8081

"%staging":
    quarkus:
        http:
          port: 8082
----

If you enable the `staging` profile, the HTTP port will be 8082, whereas it would be 8081 otherwise.

The YAML configuration also support profile aware files. In this case, properties for a specific profile may reside in
an `application-{profile}.yaml` named file. The previous example may be expressed as:

.application.yaml
[source, yaml]
----
quarkus:
  http:
    port: 8081
----

.application-staging.yaml
[source, yaml]
----
quarkus:
  http:
    port: 8082
----

[id="con_property-expressions"]
== Using property expressions in a YAML file

Property expressions are similar to variables: instead of hardcoding a property value, you can use a property expression.
The configuration system resolves the property expression when it gets the values from the configuration source in the application:

* If it reads the configuration property from your configuration at compile time, the property expression is also resolved at compile time.
* If the configuration property is overridden at run time, its value is resolved at run time.

You can use multiple sources to resolve property expressions.
You can use a property value from one source to expand an expression in another.

If the value of a property in an expression cannot be resolved, and you did not set a default value for the expression, your application encounters a `NoSuchElementException`.

.Procedure

Property expressions have the `${property_name}` format.

.Example property expressions in `application.yaml`

This section shows examples of using property expressions to achieve flexibility when configuring your {project-name} application.

.Example  file
[source,properties,options="nowrap"]
----
mach: 3
x:
  factor: 2.23694

display:
  mach: ${mach}
  unit:
    name: "mph"
    factor: ${x.factor}
----

[NOTE]
====
You can reference properties by using the `.` (dot) separator, as in `{x.factor}`.
====

.Additional resources

* For more information about property expressions, see xref:con_property-expressions[Property expressions].
// * For an example of property expressions using a properties file, see link:{URL_CONFIGURATION_QUARKUS}#ref_example-usage-of-property-expressions_quarkus-configuration-guide[Example usage of property expressions]. // TBD update and enable this ^ link later when this guide becomes available

[id="proc_configure-properties-at-run-time-external-yaml"]
== Configure properties at run time

To configure properties at run time, you can create an external configuration file by placing an `application.yaml` file in the `config` directory.

When you run the application, the values from the `config/application.yaml` file override those of identical properties in `resources/application.yaml` file.

.Prerequisites

include::{includes}/prerequisites.adoc[]
* The `quarkus-config-yaml` extension as a dependency in your project's `pom.xml` or `build.gradle` file.

.Procedure

. Add an `application.yaml` file to the `config` directory.

. Verify that the `config/application.yaml` file is in the root of the working directory relative to the {project-name} application runner, as shown in the following example:
+
[source,properties,options="nowrap"]
----
├── config
│    └── application.yaml
├── my-app-runner
----

.Additional resources

* xref:proc_enabling-yaml-configuration[Enabling YAML configuration].

[id="proc_managing-configuration-key-conflicts"]
== Managing configuration key conflicts

Structured formats such as YAML only support a subset of the possible configuration namespace.
The following procedure shows how to resolve a conflict between two configuration properties, `quarkus.http.cors` and `quarkus.http.cors.methods`, where one property is the prefix of another.

.Prerequisites

include::{includes}/prerequisites.adoc[]
* The `quarkus-config-yaml` extension as a dependency in your project's `pom.xml` or `build.gradle` file.

.Procedure

. Open your YAML configuration file.

. To define a YAML property as a prefix of another property, add a tilde (`~`) in the scope of the property as shown in the following example:
+
.Example of defining a YAML property as a prefix
[source,yaml]
----
quarkus:
  http:
    cors:
      ~: true
      methods: GET,PUT,POST
----
+
. To compile your {project-name} application in development mode, enter the following command from the project directory:
+
.Compile your {project-name} application
[source,bash]
----
./mvnw quarkus:dev
----
+
[NOTE]
====
You can use YAML keys for conflicting configuration keys at any level because they are not included in the assembly of the configuration property name.
====

// == Additional resources
//
// * link:{URL_CONFIGURATION_QUARKUS}[Configuring your {project-name} applications by using a properties file]  // TBD update link
// TBD update and enable this ^ link later when this guide becomes available
