////
This guide is maintained in the main Quarkus repository
and pull requests should be submitted there:
https://github.com/quarkusio/quarkus/tree/main/docs/src/main/asciidoc
////
[id="deploy-openshift"]
= Deploy a Quarkus application on OpenShift
include::_attributes.adoc[]
:diataxis-type: howto
:categories: cloud, native

You can deploy your Quarkus applications to OpenShift by using a single command.

This functionality is provided by the `quarkus-openshift` extension, which supports multiple deployment options.

The deployment option you choose depends on several considerations, such as the mode in which you are running your Quarkus application, the build strategy you want to use, and what you want to deploy on.

The information in this guide primarily describes how to deploy a Quarkus application running in JVM mode to OpenShift by using an OpenShift binary build.

== Prerequisites

:prerequisites-no-graalvm:
include::{includes}/prerequisites.adoc[]
* Access to an OpenShift cluster and the latest compatible version of the `oc` tool installed.
For more information, see xref:openshift-login-cluster-reference.adoc[OpenShift cluster login].
* Optional: Access to the link:https://docs.openshift.com/container-platform/4.9/cli_reference/openshift_cli/getting-started-cli.html[OpenShift CLI] (Optional as it is required only for manual deployment)
* Docker or Podman installed and configured appropriately

:sectnums:
:sectnumlevels: 3

== Create a new project and add the Quarkus Openshift extension

Build and deploy your applications as a container image that runs inside your OpenShift cluster by adding the Quarkus OpenShift extension as a dependency to your project.
Run the following command:

:create-app-artifact-id: openshift-quickstart
:create-app-extensions: resteasy-reactive,openshift
:create-app-code:
include::{includes}/devtools/create-app.adoc[]

By using Quarkus, you can automatically generate OpenShift resources based on sane defaults and user-supplied configuration.
The OpenShift extension is a wrapper extension that brings together the xref:deploying-to-kubernetes.adoc[kubernetes] and xref:container-image.adoc#openshift[container-image-openshift]
extensions with sensible defaults, which helps you to get started with Quarkus on OpenShift.

When you add the OpenShift extension, you add the following dependency to the `pom.xml` or `build.gradle` files.

[source,xml,role="primary asciidoc-tabs-target-sync-cli asciidoc-tabs-target-sync-maven"]
.pom.xml
----
<dependency>
   <groupId>io.quarkus</groupId>
   <artifactId>quarkus-openshift</artifactId>
</dependency>
----

[source,gradle,role="secondary asciidoc-tabs-target-sync-gradle"]
.build.gradle
----
implementation("io.quarkus:quarkus-openshift")
----

== Log in to the OpenShift cluster

For information about how to log in to an OpenShift cluster, see xref:openshift-login-cluster-reference.adoc[OpenShift cluster login].


== Choose how you want to build and deploy your Quarkus application

You can build and deploy your Quarkus application to OpenShift in a single step.
Alternatively, you can build the container image first and then configure the OpenShift application manually if you want more control over the deployment configuration.

To trigger a build and deployment in a single step, run the following command:

:build-additional-parameters: -Dquarkus.kubernetes.deploy=true
include::{includes}/devtools/build.adoc[]
:!build-additional-parameters:

[TIP]
====
If you want to test your application immediately, set the `quarkus.openshift.route.expose` config property to `true` to xref:deploying-to-openshift-reference#exposing_routes[expose the service automatically].
For example, add `-Dquarkus.openshift.route.expose=true` to the command previous command.
====

By running this command, you build your application locally, trigger a container image build, and automatically apply the generated OpenShift resources.
The generated resources use OpenShift's `DeploymentConfig` that is configured to automatically trigger a redeployment when a change in the `ImageStream` is noticed.
That is, any container image build after the initial deployment automatically triggers redeployment, without having to delete, update, or reapply the generated resources.

You can use the OpenShift web console to verify that the above command has created an image stream and a service resource and has deployed the application.
Alternatively, you can run the following OpenShift CLI commands:
[source,bash,subs=attributes+]
----
oc get is <1>
oc get pods <2>
oc get svc <3>
----
<1> List the image streams created.
<2> Get the list of pods.
<3> Get the list of Kubernetes services.

The service is not exposed to the outside world by default.
Therefore, unless you have used the `quarkus.openshift.route.expose` configuration property to expose the created service automatically, you must expose the service manually.

.Example: Expose the service by using the OpenShift CLI
[source,bash,subs=attributes+]
----
oc expose svc/openshift-quickstart <1>
oc get routes <2>
curl http://<route>/hello <3>
----
<1> Expose the service.
<2> Get the list of exposed routes.
<3> Access your application.

[[control_application_config]]
=== Option: Build image and configure the OpenShift application manually

If you want more control over the deployment configuration, you can build the container image first and then configure the OpenShift application manually.

To trigger a container image build, run the following command:

[source,bash,subs=attributes+]
----
./mvnw clean package -Dquarkus.container-image.build=true
----

An OpenShift binary build is performed.
The build input is the JAR file that was built locally.
The build output is an `ImageStream` that is configured to automatically trigger a deployment.
The base/builder image is specified using `base-jvm-image` and `base-native-image` for jvm and native mode respectively. An ImageStream for the image is automatically generated, unless these properties are used to reference an existing ImageStreamTag in the internal openshift registry. For example:

[source,properties]
----
quarkus.openshift.base-jvm-image=image-registry.openshift-image-registry.svc:5000/some-project/openjdk-11:17.1.16.
----

[NOTE]
====
During the build, you might find the `Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed` exception occurred due to a self-signed certificate.
To resolve this, add the following line to your `application.properties` file:

[source,properties]
----
quarkus.kubernetes-client.trust-certs=true
----

For more information, see the link:https://quarkus.io/guides/deploying-to-kubernetes#client-connection-configuration[Client connection configuraton] section of the "Kubernetes extension" guide.
====

When the build finishes, you can create a new application from the relevant `ImageStream`.
Run the following commands:

[source,bash,subs=attributes+]
----
oc get is <1>
oc new-app --name=greeting <project>/openshift-quickstart:1.0.0-SNAPSHOT <2>
oc get svc
oc expose svc/greeting <3>
oc get routes <4>
curl http://<route>/hello <5>
----
<1> Lists the image streams created.
The image stream of the application will be tagged as <project>/openshift-quickstart:1.0.0-SNAPSHOT.
<2> Create a new application from the image source.
<3> Expose the service to the outside world.
<4> Get the list of exposed routes.
<5> Access your application.

After this setup, the next time you build a container image, a deployment to OpenShift is triggered automatically and you do not have to repeat the above steps.

=== Option: Configure OpenShift application manually by using the Docker build

Build and deploy your Quarkus application to OpenShift by using the Docker build strategy.

. Set the Docker build strategy in your `application.properties` configuration file:
+
[source, properties]
----
quarkus.openshift.build-strategy=docker
----
. (Optional): Set the following properties in the `application.properties` file, as required by your environment:
.. If you are using an untrusted certificate, configure the `KubernetesClient`:
+
[source,properties]
----
quarkus.kubernetes-client.trust-certs=true
----
.. Expose the service to create an OpenShift route:
+
[source,properties]
----
quarkus.openshift.route.expose=true
----
.. Set the path to your custom Dockerfile:
+
[source,properties,subs="attributes+,+quotes"]
----
quarkus.openshift.jvm-dockerfile=<path_to_your_dockerfile>
----
The following example shows the path to the `Dockerfile.custom-jvm`:
+
[source,properties]
----
quarkus.openshift.jvm-dockerfile=src/main/resources/Dockerfile.custom-jvm
----
. Package and deploy your Quarkus application to the current OpenShift project:
+
[source,shell,subs="attributes+,+quotes"]
----
./mvnw clean package -Dquarkus.kubernetes.deploy=true
----
When the build finishes, verify your deployment.
Run the following commands:
+
[source,bash,subs=attributes+]
----
oc get pods <1>
oc logs -f <pod_name> <2>
oc get svc <3>
oc get routes <4>
curl http://<route>/hello <5>
----

<1> View a list of pods associated with your current OpenShift project.
<2> Retrieve the log output for your application’s pod, where <pod_name> is the name of the latest pod prefixed with the name of your application.
<3> Get the list of Kubernetes services.
<4> Get a URL to test your application.
<5> Access your application.

=== Option: Configure non-OpenShift container image build

As an out-of-the-box feature, the OpenShift extension is configured to use the `quarkus-container-image-openshift` extension to build the container image inside the OpenShift cluster.
For information about the OpenShift container image, see xref:container-image.adoc#openshift[container-image-openshift].

However, you can use other container image extensions.
For example:

- xref:container-image.adoc#docker[container-image-docker]
- xref:container-image.adoc#jib[container-image-jib]

When you use a non-OpenShift container image extension, an `ImageStream` is created that points to an external `dockerImageRepository`.
The image is built and pushed to the registry and the `ImageStream` populates the tags that are available in the `dockerImageRepository`.

Select the extension you want to use to build the image by choosing one of the following commands.

* To use the `quarkus-container-image-docker` extension, run the following command:
+
[source,properties]
----
quarkus.container-image.builder=docker
----

* To use the `quarkus-container-image-jib` extension, run the following command:
+
[source,properties]
----
quarkus.container-image.builder=jib
----

== Customize your deployment

For information about the different options for customizing your deployment, see xref:deploying-to-openshift-reference.adoc[Customization of Quarkus deployment on OpenShift].

:sectnums!:

== References

* xref:container-image.adoc[Container images]
* xref:cli-tooling.adoc[Building Quarkus Apps with Quarkus CLI]
* xref:openshift-login-cluster-reference.adoc[OpenShift cluster login]
* xref:deploying-to-openshift-reference.adoc[Customization of Quarkus deployment on OpenShift]