////
This guide is maintained in the main Quarkus repository
and pull requests should be submitted there:
https://github.com/quarkusio/quarkus/tree/master/docs/src/main/asciidoc
////

= Quarkus - Amazon DynamoDB Client

include::./attributes.adoc[]

DynamoDB is a scalable AWS managed *NoSQL* database.
It supports both key-value and document data models, that enables to have a flexible schema for your data.
This extension provides functionality that allows the client to communicate with the service when running in Quarkus.
You can find more information about DynamoDB at https://aws.amazon.com/dynamodb/[the Amazon DynamoDB website].

NOTE: The DynamoDB extension is based on https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/welcome.html[AWS Java SDK 2.x].
It's a major rewrite of the 1.x code base that offers two programming models (Blocking & Async).
Keep in mind it's actively developed and does not support yet all the features available in SDK 1.x such as https://github.com/aws/aws-sdk-java-v2/issues/36[Document APIs] or https://github.com/aws/aws-sdk-java-v2/issues/35[Object Mappers]

The Quarkus extension supports two programming models:

* Blocking access using the Apache HTTP Client
* https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/basics-async.html[Asynchronous programming] based on JDK's `CompletableFuture` objects and the Netty HTTP client.

In this guide, we see how you can get your REST services to use the DynamoDB locally and on AWS.

== Prerequisites

To complete this guide, you need:

* JDK 1.8+ installed with `JAVA_HOME` configured appropriately
* an IDE
* Apache Maven 3.5.3+
* An AWS Account to access the DynamoDB service
* Optionally, Docker for your system to run DynamoDB locally for testing purposes

=== Setup DynamoDB locally

The easiest way to start working with DynamoDB is to run a local instance as a container.

[source,shell,subs="verbatim,attributes"]
----
docker run --publish 8000:8000 amazon/dynamodb-local:1.11.477 -jar DynamoDBLocal.jar -inMemory -sharedDb
----

This starts a DynamoDB instance that is accessible on port `8000`.
You can check it's running by accessing the web shell on `http://localhost:8000/shell`.

Have a look at the https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html[Setting Up DynamoDB Local guide] for other options to run DynamoDB.

Open `http://localhost:8000/shell` in your browser.

Copy and paste the following code to the shell and run it:
[source,js,subs="verbatim,attributes"]
----
var params = {
    TableName: 'QuarkusFruits',
    KeySchema: [{ AttributeName: 'fruitName', KeyType: 'HASH' }],
    AttributeDefinitions: [{  AttributeName: 'fruitName', AttributeType: 'S', }],
    ProvisionedThroughput: { ReadCapacityUnits: 1, WriteCapacityUnits: 1, }
};

dynamodb.createTable(params, function(err, data) {
    if (err) ppJson(err);
    else ppJson(data);

});
----

=== Set up Dynamodb on AWS

Before you can use the AWS SDKs with DynamoDB, you must get an AWS access key ID and secret access key.
For more information, see https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/SettingUp.DynamoWebService.html[Setting Up DynamoDB (Web Service)].

We recommend to use the AWS CLI to provision the table:

[source,shell,subs="verbatim,attributes"]
----
aws dynamodb create-table --table-name QuarkusFruits \
                          --attribute-definitions AttributeName=fruitName,AttributeType=S \
                          --key-schema AttributeName=fruitName,KeyType=HASH \
                          --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1
----

== Solution
The application built here allows to manage elements (fruits) stored in Amazon DynamoDB.

We recommend that you follow the instructions in the next sections and create the application step by step.
However, you can go right to the completed example.

Clone the Git repository: `git clone {quickstarts-clone-url}`, or download an {quickstarts-archive-url}[archive].

The solution is located in the `dynamodb-client` directory.

== Creating the Maven project

First, we need a new project. Create a new project with the following command:

[source,shell,subs=attributes+]
----
mvn io.quarkus:quarkus-maven-plugin:{quarkus-version}:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=dynamodb-client \
    -DclassName="org.acme.dynamodb.FruitResource" \
    -Dpath="/fruits" \
    -Dextensions="resteasy-jsonb,dynamodb"
----

This command generates a Maven structure importing the RESTEasy/JAX-RS and DynamoDB Client extensions.
After this, the `amazon-dynamodb` extension has been added to your `pom.xml`.

== Creating JSON REST service

In this example, we will create an application to manage a list of fruits. The example application will demonstrate the two programming models supported by the extension.

First, let's create the `Fruit` bean as follows:

[source,java]
----
package org.acme.dynamodb;

import java.util.Map;
import java.util.Objects;

import io.quarkus.runtime.annotations.RegisterForReflection;
import software.amazon.awssdk.services.dynamodb.model.AttributeValue;

@RegisterForReflection
public class Fruit {

    private String name;
    private String description;

    public Fruit() {
    }

    public static Fruit from(Map<String, AttributeValue> item) {
        Fruit fruit = new Fruit();
        if (item != null && !item.isEmpty()) {
            fruit.setName(item.get(AbstractService.FRUIT_NAME_COL).s());
            fruit.setDescription(item.get(AbstractService.FRUIT_DESC_COL).s());
        }
        return fruit;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof Fruit)) {
            return false;
        }

        Fruit other = (Fruit) obj;

        return Objects.equals(other.name, this.name);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.name);
    }
}
----

Nothing fancy. One important thing to note is that having a default constructor is required by the JSON serialization layer. The static `from` method creates a bean based on the `Map`
object provided by the DynamoDB client response.

Now create a `org.acme.dynamodb.AbstractService` that will consist of helper methods that prepare DynamoDB request objects for reading and adding items to the table.

[source,java]
----
package org.acme.dynamodb;

import java.util.HashMap;
import java.util.Map;

import software.amazon.awssdk.services.dynamodb.model.AttributeValue;
import software.amazon.awssdk.services.dynamodb.model.GetItemRequest;
import software.amazon.awssdk.services.dynamodb.model.PutItemRequest;
import software.amazon.awssdk.services.dynamodb.model.ScanRequest;

public abstract class AbstractService {

    public final static String FRUIT_NAME_COL = "fruitName";
    public final static String FRUIT_DESC_COL = "fruitDescription";

    public String getTableName() {
        return "QuarkusFruits";
    }

    protected ScanRequest scanRequest() {
        return ScanRequest.builder().tableName(getTableName())
                .attributesToGet(FRUIT_NAME_COL, FRUIT_DESC_COL).build();
    }

    protected PutItemRequest putRequest(Fruit fruit) {
        Map<String, AttributeValue> item = new HashMap<>();
        item.put(FRUIT_NAME_COL, AttributeValue.builder().s(fruit.getName()).build());
        item.put(FRUIT_DESC_COL, AttributeValue.builder().s(fruit.getDescription()).build());

        return PutItemRequest.builder()
                .tableName(getTableName())
                .item(item)
                .build();
    }

    protected GetItemRequest getRequest(String name) {
        Map<String, AttributeValue> key = new HashMap<>();
        key.put(FRUIT_NAME_COL, AttributeValue.builder().s(name).build());

        return GetItemRequest.builder()
                .tableName(getTableName())
                .key(key)
                .attributesToGet(FRUIT_NAME_COL, FRUIT_DESC_COL)
                .build();
    }
}
----

Then, create a `org.acme.dynamodb.FruitSyncService` that will be the business layer of our application and stores/loads the fruits from DynamoDB using the synchronous client.

[source,java]
----
package org.acme.dynamodb;

import java.util.List;
import java.util.stream.Collectors;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;

import software.amazon.awssdk.services.dynamodb.DynamoDbClient;

@ApplicationScoped
public class FruitSyncService extends AbstractService {

    @Inject
    DynamoDbClient dynamoDB;

    public List<Fruit> findAll() {
        return dynamoDB.scanPaginator(scanRequest()).items().stream()
                .map(Fruit::from)
                .collect(Collectors.toList());
    }

    public List<Fruit> add(Fruit fruit) {
        dynamoDB.putItem(putRequest(fruit));
        return findAll();
    }

    public Fruit get(String name) {
        return Fruit.from(dynamoDB.getItem(getRequest(name)).item());
    }
}
----

Now, edit the `org.acme.dynamodb.FruitResource` class as follows:

[source,java]
----
package org.acme.dynamodb;

import java.util.List;

import javax.inject.Inject;
import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

@Path("/fruits")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public class FruitResource {

    @Inject
    FruitSyncService service;

    @GET
    public List<Fruit> getAll() {
        return service.findAll();
    }

    @GET
    @Path("{name}")
    public Fruit getSingle(@PathParam("name") String name) {
        return service.get(name);
    }

    @POST
    public List<Fruit> add(Fruit fruit) {
        service.add(fruit);
        return getAll();
    }
}
----

The implementation is pretty straightforward and you just need to define your endpoints using the JAX-RS annotations and use the `FruitSyncService` to list/add new fruits.

== Configuring DynamoDB clients

Both DynamoDB clients (sync and async) are configurable via the `application.properties` file that can be provided in the `src/main/resources` directory.

If you're going to use a local DynamoDB instance, configure it as follows:

[source,properties]
----
quarkus.dynamodb.region=eu-central-1
quarkus.dynamodb.endpoint-override=http://localhost:8000

quarkus.dynamodb.credentials.type=STATIC
quarkus.dynamodb.credentials.static-provider.access-key-id=test-key
quarkus.dynamodb.credentials.static-provider.secret-access-key=test-secret
----

- `quarkus.dynamodb.region` - It's required by the client, but since you're using a local DynamoDB instance you can pick any valid AWS region.
- `quarkus.dynamodb.endpoint-override` - Override the DynamoDB client to use a local instance instead of an AWS service
- `quarkus.dynamodb.credentials.type` - Set `STATIC` credentials provider with any values for `access-key-id` and `secret-access-key`

If you want to work with an AWS account, you'd need to set it with:
[source,properties]
----
quarkus.dynamodb.region=<YOUR_REGION>
quarkus.dynamodb.credentials.type=DEFAULT
----

- `quarkus.dynamodb.region` you should set it to the region where you provisioned the DynamoDB table,
- `quarkus.dynamodb.credentials.type` - use the `DEFAULT` credentials provider chain that looks for credentials in this order:
- Java System Properties - `aws.accessKeyId` and `aws.secretKey`
* Environment Variables - `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`
* Credential profiles file at the default location (`~/.aws/credentials`) shared by all AWS SDKs and the AWS CLI
* Credentials delivered through the Amazon EC2 container service if the `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` environment variable is set and the security manager has permission to access the variable,
* Instance profile credentials delivered through the Amazon EC2 metadata service

== Next steps

=== Packaging

Packaging your application is as simple as `./mvnw clean package`.
It can be run with `java -jar target/dynamodb-client-1.0-SNAPSHOT-runner.jar`.

With GraalVM installed, you can also create a native executable binary: `./mvnw clean package -Dnative`.
Depending on your system, that will take some time.

=== Going asynchronous

Thanks to the AWS SDK v2.x used by the Quarkus extension, you can use the asynchronous programming model out of the box.

Create a `org.acme.dynamodb.FruitAsyncService` that will be similar to our `FruitSyncService` but using an asynchronous programming model.

[source,java]
----
package org.acme.dynamodb;

import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.stream.Collectors;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;

import software.amazon.awssdk.services.dynamodb.DynamoDbAsyncClient;

@ApplicationScoped
public class FruitAsyncService extends AbstractService {

    @Inject
    DynamoDbAsyncClient dynamoDB;

    public CompletableFuture<List<Fruit>> findAll() {
        return dynamoDB.scan(scanRequest())
                .thenApply(res -> res.items().stream().map(Fruit::from).collect(Collectors.toList()));
    }

    public CompletableFuture<List<Fruit>> add(Fruit fruit) {
        return dynamoDB.putItem(putRequest(fruit)).thenCompose(ret -> findAll());
    }

    public CompletableFuture<Fruit> get(String name) {
        return dynamoDB.getItem(getRequest(name)).thenApply(resp -> Fruit.from(resp.item()));
    }
}
----

And an asynchronous REST resource:

[source,java]
----
package org.acme.dynamodb;

import java.util.List;
import java.util.concurrent.CompletionStage;

import javax.inject.Inject;
import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

@Path("/async-fruits")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public class FruitAsyncResource {

    @Inject
    FruitAsyncService service;

    @GET
    public CompletionStage<List<Fruit>> getAll() {
        return service.findAll();
    }

    @GET
    @Path("{name}")
    public CompletionStage<Fruit> getSingle(@PathParam("name") String name) {
        return service.get(name);
    }

    @POST
    public CompletionStage<List<Fruit>> add(Fruit fruit) {
        service.add(fruit);
        return getAll();
    }
}
----

== Configuration Reference

=== Common configuration parameters that applies both to async and sync clients.

|===
|Configuration key|Java type|Default Value|Description

|quarkus.dynamodb.region
|software.amazon.awssdk.regions.Region
|
|An Amazon Web Services region that hosts DynamoDB, e.g. 'us-east-1'

|quarkus.dynamodb.enable-endpoint-discovery
|Boolean
|`false`
|Endpoint discovery identifies and connects to the correct endpoint for a service API that supports endpoint discovery.

|quarkus.dynamodb.endpoint-override
|URI
|
|Configure the endpoint with which the SDK should communicate. If not specified, an appropriate endpoint to be used for a given AWS service and region.

|quarkus.dynamodb.credentials.type
|io.quarkus.dynamodb.runtime.AwsCredentialsProviderType
|`DEFAULT`
|Configure the credentials that should be used to authenticate with AWS.
|===

=== DEFAULT credentials provider

If `quarkus.dynamodb.credentials.type=DEFAULT` is specified, the provider will attempt to identify the credentials automatically using the following checks:

- Java System Properties - `aws.accessKeyId` and `aws.secretKey`
- Environment Variables - `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`
- Credential profiles file at the default location (~/.aws/credentials) shared by all AWS SDKs and the AWS CLI
- Credentials delivered through the Amazon EC2 container service if `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` environment variable is set and security manager has permission to access the variable.
- Instance profile credentials delivered through the Amazon EC2 metadata service

Additionally, you can configure the provider with:
|===
|Configuration key|Java type|Default Value|Description

|quarkus.dynamodb.credentials.default-provider.async-credential-update-enabled
|Boolean
|`false`
|Configure whether this provider should fetch credentials asynchronously in the background. If this is `true`, threads are less likely to block, but additional resources are used to maintain the provider.

|quarkus.dynamodb.credentials.default-provider.reuse-last-provider-enabled
|Boolean
|`true`
|Controls whether the provider should reuse the last successful credentials provider in the chain. Reusing the last successful credentials provider will typically return credentials faster than searching through the chain.
|===

=== STATIC credentials provider
If `quarkus.dynamodb.credentials.type=STATIC` is specified, the provider uses the access key and secret access key specified with:

|===
|Configuration key|Java type|Default Value|Description

|quarkus.dynamodb.credentials.static-provider.access-key-id
|String
|
|AWS access key ID.

|quarkus.dynamodb.credentials.static-provider.secret-access-key
|String
|
|AWS secret access key.
|===

=== SYSTEM_PROPERTY credentials provider
If `quarkus.dynamodb.credentials.type=SYSTEM_PROPERTY` is specified, it loads credentials from the `aws.accessKeyId`, `aws.secretAccessKey` and `aws.sessionToken` system properties.

=== ENV_VARIABLE credentials provider
If `quarkus.dynamodb.credentials.type=ENV_VARIABLE` is specified, it loads credentials from the `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and `AWS_SESSION_TOKEN` environment variables.

=== PROFILE credentials provider
If `quarkus.dynamodb.credentials.type=PROFILE` is specified, credentials are based on AWS configuration profiles.
This loads credentials from a http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html[profile file], allowing you to share multiple sets of AWS security credentials between different tools like the AWS SDK for Java and the AWS CLI.

It can be configured with:
|===
|Configuration key|Java type|Default Value|Description

|quarkus.dynamodb.credentials.profile-provider.profile-name
|String
|`default`
|Define the name of the profile that should be used by this credentials provider. If not specified, the value in `AWS_PROFILE` environment variable or `aws.profile` system property is used.
|===

=== CONTAINER credentials provider
If `quarkus.dynamodb.credentials.type=CONTAINER` is specified, it loads credentials from a local metadata service.
Containers currently supported by the AWS SDK:
- Amazon Elastic Container Service (ECS)
- AWS Greengrass


=== INSTANCE_PROFILE credentials provider
If `quarkus.dynamodb.credentials.type=INSTANCE_PROFILE` is specified, it loads credentials from the Amazon EC2 Instance Metadata Service.

=== PROCESS credentials provider

If `quarkus.dynamodb.credentials.type=PROCESS` used, credentials are loaded from an external process. This is used to support the credential_process setting in the profile credentials file.
See https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#sourcing-credentials-from-external-processes[Sourcing Credentials From External Processes] for more information.

It can be configured with:

|===
|Configuration key|Java type|Default Value|Description

|quarkus.dynamodb.credentials.process-provider.command
|String
|
|The command that should be executed to retrieve credentials.

|quarkus.dynamodb.credentials.process-provider.process-output-limit
|Long
| `1024`
|Configure the maximum amount of `bytes` that can be returned by the external process before an exception is raised.

|quarkus.dynamodb.credentials.process-provider.credential-refresh-threshold
|java.time.Duration
|`PT15S`
|Configure the amount of time between when the credentials expire and when the credentials should start to be refreshed. This allows the credentials to be refreshed *before* they are reported to expire.

|quarkus.dynamodb.credentials.process-provider.async-credential-update-enabled
|Boolean
|`false`
|Configure whether the provider should fetch credentials asynchronously in the background. If this is true, threads are less likely to block when credentials are loaded, but additional resources are used to maintain the provider.
|===

=== ANONYMOUS credentials provider
If `quarkus.dynamodb.credentials.type=ANONYMOUS` is specified, it always returns anonymous AWS credentials.
Anonymous AWS credentials result in un-authenticated requests and will fail unless the resource or API's policy has been configured to specifically allow anonymous access.

=== Synchronous transport layer configuration parameters
If `software.amazon.awssdk.services.dynamodb.DynamoDbClient` client is used a synchronous transport layer is utilized via the Apache HTTP Client. It can be configured with:
|===
|Configuration key|Java type|Default Value|Description

|quarkus.dynamodb.sync-client.connection-acquisition-timeout
|java.time.Duration
|`10S`
|The amount of time to wait when acquiring a connection from the pool before giving up and timing out. Default is 10 seconds.

|quarkus.dynamodb.sync-client.connection-max-idle-time
|java.time.Duration
|`60S`
|Configure the maximum amount of time that a connection should be allowed to remain open while idle. Default is 60 seconds.

|quarkus.dynamodb.sync-client.connection-timeout
|java.time.Duration
|`2S`
|Configure the endpoint with which the SDK should communicate. If not specified, an appropriate endpoint to be used for a given service and region. Default is 2 seconds.

|quarkus.dynamodb.sync-client.connection-time-to-live
|java.time.Duration
|`0`
|The maximum amount of time that a connection should be allowed to remain open, regardless of usage frequency.

|quarkus.dynamodb.sync-client.socket-timeout
|java.time.Duration
|`30S`
|The amount of time to wait for data to be transferred over an established, open connection before the connection is timed out. A duration of 0 means infinity, and is not recommended.

|quarkus.dynamodb.sync-client.max-connections
|Long
|`50`
|The maximum number of connections allowed in the connection pool. Each built HTTP client has it's own private connection pool.

|quarkus.dynamodb.sync-client.expect-continue-enabled
|Boolean
|`true`
|Configure whether the client should send an HTTP expect-continue handshake before each request.

|quarkus.dynamodb.sync-client.use-idle-connection-reaper
|Boolean
|`true`
|Configure whether the idle connections in the connection pool should be closed asynchronously. When enabled, connections left idling for longer than `quarkus.dynamodb.sync-client.connection-max-idle-time` will be closed. This will not close connections currently in use. By default, this is enabled.

|quarkus.dynamodb.sync-client.proxy.enabled
|Boolean
|`false`
|Enables HTTP Proxy.

|quarkus.dynamodb.sync-client.proxy.endpoint
|URI
|
|Configure the endpoint of the proxy server that the SDK should connect through. Currently, the endpoint is limited to a host and port. Any other URI components will result in an exception being raised.

|quarkus.dynamodb.sync-client.proxy.username
|String
|
|Configure the username to use when connecting through a proxy.

|quarkus.dynamodb.sync-client.proxy.password
|String
|
|Configure the password to use when connecting through a proxy.

|quarkus.dynamodb.sync-client.proxy.ntlm-domain
|String
|
|For NTLM proxies: Configure the Windows domain name to use when authenticating with the proxy.

|quarkus.dynamodb.sync-client.proxy.ntlm-workstation
|String
|
|For NTLM proxies: Configure the Windows workstation name to use when authenticating with the proxy.

|quarkus.dynamodb.sync-client.proxy.preemptive-basic-authentication-enabled
|Boolean
|
|Configure whether to attempt to authenticate pre-emptively against the proxy server using basic authentication.

|quarkus.dynamodb.sync-client.proxy.non-proxy-hosts
|List of String
|
|Configure the hosts that the client is allowed to access without going through the proxy.
|===

=== Asynchronous transport layer configuration parameters
If `software.amazon.awssdk.services.dynamodb.DynamoDbAsyncClient` client is used a asynchronous transport layer is utilized via the Netty I/O. It can be configured with:

|===
|Configuration key|Java type|Default Value|Description

|quarkus.dynamodb.async-client.max-concurrency
|Integer
|
|Maximum number of allowed concurrent requests. For HTTP/1.1 this is the same as max connections. For HTTP/2 the number of connections that will be used depends on the max streams allowed per connection.

|quarkus.dynamodb.async-client.max-pending-connection-acquires
|Integer
|`10_000`
|The maximum number of pending acquires allowed. Once this exceeds, acquire tries will be failed.

|quarkus.dynamodb.async-client.read-timeout
|java.time.Duration
|`30S`
|The amount of time to wait for a read on a socket before an exception is thrown. Specify `0` to disable.

|quarkus.dynamodb.async-client.write-timeout
|java.time.Duration
|`30S`
|The amount of time to wait for a write on a socket before an exception is thrown. Specify `0` to disable.

|quarkus.dynamodb.async-client.connection-timeout
|java.time.Durationn
|`2S`
|The amount of time to wait when initially establishing a connection before giving up and timing out.

|quarkus.dynamodb.async-client.connection-acquisition-timeout
|java.time.Duration
|`10S`
|The amount of time to wait when acquiring a connection from the pool before giving up and timing out.

|quarkus.dynamodb.async-client.connection-time-to-live
|java.time.Duration
|`0`
|The maximum amount of time that a connection should be allowed to remain open, regardless of usage frequency.

|quarkus.dynamodb.async-client.connection-max-idle-time
|java.time.Duration
|`60S`
|Configure the maximum amount of time that a connection should be allowed to remain open while idle. Currently has no effect if `quarkus.dynamodb.async-client.use-idle-connection-reaper` is false.

|quarkus.dynamodb.async-client.use-idle-connection-reaper
|Boolean
|`true`
|Configure whether the idle connections in the connection pool should be closed. When enabled, connections left idling for longer than `quarkus.dynamodb.async-client.connection-max-idle-time` will be closed. This will not close connections currently in use. By default, this is enabled.

|quarkus.dynamodb.async-client.protocol
|String
|`HTTP1_1`
|Sets the HTTP protocol to use (i.e. `HTTP1_1` or `HTTP_2`). Not all services support HTTP/2.

|quarkus.dynamodb.async-client.max-http2-streams
|Integer
|
|Sets the max number of concurrent streams for an HTTP/2 connection. This setting is only respected when the HTTP/2 protocol is used. Default is unlimited.

|quarkus.dynamodb.async-client.ssl-provider
|io.netty.handler.ssl.SslProvider
|`OPENSSL` or `JDK`
|Sets the Ssl Provider to be used in the Netty client. Default is `OPENSSL` if available, `JDK` otherwise.

|quarkus.dynamodb.async-client.event-loop.override
|String
|`false`
|This enables the custom configuration of the Netty event loop group.

|quarkus.dynamodb.async-client.event-loop.number-of-threads
|Integer
|
|Number of threads to use for the event loop group. If not set, the default Netty thread count is used (which is double the number of available processors unless the `io.netty.eventLoopThreads` system property is set.

|quarkus.dynamodb.async-client.event-loop.thread-name-prefix
|String
|`aws-java-sdk-NettyEventLoop`
|The thread name prefix for threads created by this thread factory used by event loop group. The prefix will be appended with a number unique to the thread factory and a number unique to the thread.
|===

include::duration-format-note.adoc[]
