= Extension Authors Guide

Shamrock extensions consist of two distinct parts, augmentation and runtime. The augmentation part is responsible for
all metadata processing, such as reading annotation, XML descriptors etc. The output of this augmentation phase
is recorded bytecode which is responsible for directly instantiating the relevant runtime services.

This means that metadata is only processed once at build time, which both saves on startup time, but also on memory
usage as the classes etc that are used for processing are not loaded (or even present) in the runtime JVM.

== Three Phases of Bootstrap and Shamrock Philosophy

There are three distinct phases of the bootstrap of a Shamrock app:

Augmentation::
    This is the first phase, and is done by the build step processors. These processors have access to Jandex annotation
    information and can parse any descriptors, but should not attempt to load any application classes. The output of these
    build steps is some recorded bytecode, that is used to actually bootstrap the application at runtime. Depending on the mode
    this step may be run in a different JVM to the following two steps.

Static Init::
    If bytecode is recorded with `@Record(STATIC_INIT)` then it will be executed from a static init method on the main
    class. This means that for a native image build this code is executed in a normal JVM as part of the image build
    process. Any retained objects that are produced in this stage will be directly serialized into the native image.
    This means that if a framework can boot in this phase then it will have its booted state directly written to the
    image, so the boot code does not need to be executed when the image is started.
+
There are some restrictions on what can be done in this stage as Substrate disallows some objects in the native image,
for example you should not attempt to listen on a port or start threads in this phase.
+
In JVM mode there is no real difference between this and runtime init, except that this is always executed first.

Runtime Init::
    If bytecode is recorded with `@Record(RUNTIME_INIT)` then it is executed from the application's main method. This code
    will be run on native image boot. In general as little code as possible should be executed in this phase, and should
    be restricted to code that needs to open ports etc.

This means that there are really two different optimizations we are trying to make, for native image we want to boot
as much as possible in static init, so that the resulting native image will start as fast as possible. When running on
the JVM we want to push as much code as possible into offline processing, so that as few classes as possible are loaded
on application start, and so that as little processing as possible is done as part of application startup. In servers like
WildFly, deployment related classes such as XML parsers hang around for the life of the application, using up valuable
memory. Shamrock aims to eliminate this, so that the only classes loaded at runtime are actually used at runtime.

As an example, the only reason that a Shamrock application should load an XML parser is if the user is using XML in their
application. Any XML parsing of configuration should be done in the Augmentation phase.

Another advantage of this approach is that it means Substrate can more easily eliminate features that are not used.
If features are directly initialized via bytecode, Substrate can detect that a method is never called and eliminate
that method. If config is read at runtime, Substrate cannot reason about the contents of the config and so needs to
keep all features in case they are required.


== Maven setup

Your runtime artifact should depend on shamrock-core-runtime, and possibly the runtime artifacts of other Shamrock
modules if you want to use functionality provided by them. You will also need to include the `maven-dependency-plugin`
to write out the needed runtime dependencies, if you are using the Shamrock parent pom it will automatically
inherit the correct configuration.

[source%nowrap,xml]
----

<dependencies>
    <dependency>
      <groupId>org.jboss.shamrock</groupId>
      <artifactId>shamrock-core-runtime</artifactId>
    </dependency>
</dependencies>

<build>
    <plugins>
        <plugin>
            <artifactId>maven-dependency-plugin</artifactId>
        </plugin>
    </plugins>
</build>
----

[WARNING]
====
Under no circumstances can the runtime module depend on a deployment artifact. This would result
in pulling all the deployment time code into runtime scope, which defeats the purpose of having the split.
====

Your deployment time module should depend on `shamrock-core-deployment`, your runtime artifact,
and possibly the deployment artifacts of other Shamrock modules if you want to use functionality provided by them.


[source%nowrap,xml]
----
<dependency>
  <groupId>org.jboss.shamrock</groupId>
  <artifactId>shamrock-core-deployment</artifactId>
</dependency>
----

NOTE: For historical reasons the `augment` step is still called `deployment`, this will likely remain until we do our big rename.

== Build Step Processors

Work is done at deployment time by producing and consuming instances of `org.jboss.builder.item.BuildItem`. This is done
by creating a class that has method(s) annotated with `org.jboss.shamrock.annotations.BuildStep`. These classes can
consume items by injection, and produce items by either returning them from the method or by injecting an
instance of `org.jboss.shamrock.annotations.BuildProducer` for the produced type. These processors can also record
bytecode invocations, which is mapped to a `BuildItem` transparently.

There are two distinct types of `BuildItem`, `SimpleBuildItem` and `MultiBuildItem`. `SimpleBuildItem` will only ever
have a single instance created, while `MultiBuildItem` can have many instances.

Injection can be done either via field injection, or via method parameter injection. Injection is used to set up
dependencies between build steps. For example if you inject a `List<ServletBuildItem>` your build step will not be called
until all possible producers of `ServletBuildItem` have been called. Injected objects are only valid during a `@BuildStep`
method invocation, once the method is complete they are no longer valid.

The following items are valid for injection:

- `SimpleBuildItem` instances (at some point we may support `Optional<SimpleBuildItem>`, but it is not implemented yet)
- `List<? extension MultiBuildItem>` instances
- `BuildProducer<? extends BuildItem>` instances

If a method returns a `BuildItem`, or injects a `BuildProducer` it is considered to be a producer of that item type,
while if it injects the item or list of items it is a consumer.

Note that a `@BuildStep` method will only be called if it produces something that another consumer or the final output
requires. If there is no consumer for a particular item then it will not be produced. What is required will depend on
the final target that is being produced, for example when running in developer mode the final output will not ask
for Substrate-specific build items such as `ReflectiveClassBuildItem` so methods that only produce Substrate specific
items will not be invoked.

Note that private methods and fields are not allowed, as injection is resolved at compile time via an annotation processor,
and the resulting code does not have permission to inject private fields or invoke private methods.

`BuildItem` instances should be immutable, as the producer/consumer model does not allow for mutation to be correctly
ordered. This is not enforced but failure to adhere to this can result in race conditions.

== Configuration

Configuration is done via `@ConfigProperty`, this section is TBD.

== Bytecode Recording

One of the main outputs of the build process is recorded bytecode. This bytecode actually sets up the runtime environment,
for example in order to start Undertow the resulting application will have some bytecode that directly registers all
Servlet instances and then starts Undertow.

As writing bytecode directly is incredibly complex this is instead done via bytecode recorders. At deployment time invocations
are made on proxy instances of template objects that contain the actual runtime logic, and these invocations are recorded,
including the value of method parameters. Bytecode is then created to do these same invocations on the actual template
object at runtime.

This is done by adding a `@Record` annotation to a `@BuildStep` method, and injecting a `@Template` annotated class
from the runtime module. A proxy of the template will be injected into the method, and any method invocations that are
made will be recorded, and will be run at application startup.

Methods on a template can return a value, which must be proxiable (if you want to return a non-proxiable item wrap it
in `org.jboss.shamrock.runtime.RuntimeValue`). These proxies may not be invoked directly, however they can be passed
into other template methods. This can be any template method, including from other `@Record` methods, so a common pattern
is to produce `BuildItem` instances that wrap the results of these template invocations.

For instance in order to make arbitrary changes to the Servlet deployment Undertow has a `ServletExtensionBuildItem`,
that is a `MultiBuildItem` that wraps a `ServletExtension` instance. I can return a `ServletExtension` from a template
in another module, and Undertow will consume it and pass it into the template method that starts Undertow.

At runtime the bytecode will be invoked in the order it is generated. This means that build step dependencies implicitly
control the order that generated bytecode is run. In the example above we know that the bytecode that produces a
`ServletExtensionBuildItem` will be run before the bytecode that consumes it.


=== RecorderContext

`org.jboss.shamrock.deployment.recording.RecorderContext` provides some convenience methods to enhance bytecode recording,
this includes the ability to register creation functions for classes without a no-args constructor, to register an object
substitution (basically a transformer from a non-serializable object to a serializable one and vice versa), and to create
a class proxy. This interface can be directly injected as a method parameter into any `@Recorder` method.

Calling `classProxy` with a given class name will create a `Class` that can be passed into template
methods, and at runtime will be substituted with the class whose name was passed in to `classProxy`. This is basically a
convenience to avoid the need to explicitly load classes in the templates.


TODO: config integration


== Testing Extensions

Testing of extensions should be done with the `org.jboss.shamrock.test.ShamrockUnitTest` runner. This runner allows
for Arquillian-style tests that test specific functionalities. It is not intended for testing user applications, this
should be done via `org.jboss.shamrock.test.ShamrockTest`. The main difference between these test runners is that
`ShamrockTest` simply boots the application once at the start of the run, while `ShamrockUnitTest` deploys a custom
Shamrock application for each test class.

These tests should be placed in the augmentation module, if additional Shamrock modules are required for testing
their augment modules should also be added as test scoped dependencies.

An example test class may look like:

[source,java]
----
import javax.enterprise.inject.Instance;
import javax.inject.Inject;

import org.eclipse.microprofile.health.*;
import org.jboss.shamrock.test.*;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.asset.EmptyAsset;
import org.jboss.shrinkwrap.api.spec.JavaArchive;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(ShamrockUnitTest.class)                                     <1>
public class FailingUnitTest {

    @Deployment                                                      <2>
    public static JavaArchive deploy() {
        return ShrinkWrap.create(JavaArchive.class)
                .addClasses(FailingHealthCheck.class)
                .addAsManifestResource(EmptyAsset.INSTANCE, "beans.xml");
    }

    @Inject                                                          <3>
    @Health
    Instance<HealthCheck> checks;

    @Test
    public void testHealthServlet() {
        URLResponse rep = URLTester.relative("health").invokeURL();  <4>
        Assert.assertEquals(503, rep.statusCode());
    }

    @Test
    public void testHealthBeans() {
        List<HealthCheck> check = new ArrayList<>();                 <5>
        for (HealthCheck i : checks) {
            check.add(i);
        }
        Assert.assertEquals(1, check.size());
        Assert.assertEquals(HealthCheckResponse.State.DOWN, check.get(0).call().getState());
    }
}
----


<1> This tells JUnit to use the Shamrock unit test runner
<2> This deployment method is used to build the application to be tested. It uses Shrinkwrap to create a JavaArchive to test
<3> It is possible to inject beans from our test deployment directly into the test case
<4> This method directly invokes the health check Servlet and verifies the response
<5> This method uses the injected health check bean to verify it is returning the expected result
