////
This guide is maintained in the main Quarkus repository
and pull requests should be submitted there:
https://github.com/quarkusio/quarkus/tree/main/docs/src/main/asciidoc
////
= Funqy HTTP Binding with Azure Functions
:extension-status: preview
include::_attributes.adoc[]
:categories: cloud
:summary: Use Funqy HTTP binding with Microsoft Azure Functions to deploy your serverless Quarkus applications.

You can use xref:funqy-http.adoc[Funqy HTTP] on Azure Functions.  This allows you to invoke on multiple Funqy functions
using HTTP deployed as one Azure Function.

WARNING: The Funqy HTTP + Azure Functions binding is not a replacement for REST over HTTP.  Because Funqy
needs to be portable cross a lot of different protocols and function providers its HTTP binding
is very minimalistic and you will lose REST features like linking and the ability to leverage
HTTP features like cache-control and conditional GETs.  You may want to consider using Quarkus's
Jakarta REST, Spring MVC, or Vert.x Web Reactive Route xref:azure-functions-http.adoc[support] instead.  They also work with Quarkus and Azure Functions.


include::{includes}/extension-status.adoc[]

Follow the xref:azure-functions-http.adoc[Azure Functions HTTP Guide].  It walks through using a variety of HTTP
frameworks on Azure Functions.  Including Funqy.

