////
This guide is maintained in the main Quarkus repository
and pull requests should be submitted there:
https://github.com/quarkusio/quarkus/tree/main/docs/src/main/asciidoc
////
[id="funqy-http-azure-functions"]
= Funqy HTTP binding with Azure Functions
:extension-status: preview
include::_attributes.adoc[]
:diataxis-type: concept
:categories: cloud

Use xref:funqy-http.adoc[Quarkus Funqy HTTP] binding with Microsoft Azure Functions to deploy your serverless Quarkus applications.
By integrating your Quarkus applications with Azure Functions, you can invoke multiple Funqy HTTP functions as one Azure function.

include::{includes}/extension-status.adoc[]

== Overview

// More overview information about Funqy and Quarkus and the integration with Azure is needed here.

[IMPORTANT]
====
The Quarkus Funqy HTTP with Azure Functions binding is not a replacement for REST over HTTP.
This is because Funqy needs to be portable across many different protocols and function providers and its HTTP binding is very basic.
====

With Funqy, you can lose REST features such as linking and the ability to use some HTTP features, for example, cache-control and conditional GETs.

To build RESTful Quarkus applications, consider using the Quarkus implementation of Jakarta REST, Spring MVC, or Vert.x Web Reactive Route support instead, as described in xref:azure-functions-http.adoc[Azure Functions with RESTEasy Reactive, Undertow, or Reactive Routes].
These HTTP frameworks can be easily integrated with Quarkus and Azure Functions.

== Get started

For more information about the HTTP frameworks in Quarkus that you can integrate with Azure Functions, including Funqy, see the following tutorial:

xref:azure-functions-http.adoc[Integrate and deploy a RESTEasy Reactive endpoint to Azure Functions].

== References

* xref:azure-integration-built-in.adoc[Quarkus integration with Microsoft Azure]
* xref:funqy-http.adoc[Quarkus Funqy HTTP]
