examples:
- source: devtools/gradle/gradle-app-plugin/src/test/resources/documentation/application-plugin-migration/direct/groovy/settings.gradle
  target: gradle-application-plugin-migration-direct-settings-3.gradle
- source: devtools/gradle/gradle-app-plugin/src/test/resources/documentation/application-plugin-migration/direct/kotlin/settings.gradle.kts
  target: gradle-application-plugin-migration-direct-settings-3.gradle.kts
- source: devtools/gradle/gradle-app-plugin/src/test/resources/documentation/application-plugin-migration/direct/groovy/settings.gradle.quarkus4
  target: gradle-application-plugin-migration-direct-settings-4.gradle
- source: devtools/gradle/gradle-app-plugin/src/test/resources/documentation/application-plugin-migration/direct/kotlin/settings.gradle.kts.quarkus4
  target: gradle-application-plugin-migration-direct-settings-4.gradle.kts
- source: devtools/gradle/gradle-app-plugin/src/test/resources/documentation/application-plugin-migration/coexistence/groovy/settings.gradle
  target: gradle-application-plugin-migration-coexistence-settings.gradle
- source: devtools/gradle/gradle-app-plugin/src/test/resources/documentation/application-plugin-migration/coexistence/kotlin/settings.gradle.kts
  target: gradle-application-plugin-migration-coexistence-settings.gradle.kts
- source: devtools/gradle/gradle-app-plugin/src/test/resources/documentation/application-plugin-migration/direct/groovy/build.gradle
  target: gradle-application-plugin-migration-direct-3.gradle
- source: devtools/gradle/gradle-app-plugin/src/test/resources/documentation/application-plugin-migration/direct/kotlin/build.gradle.kts
  target: gradle-application-plugin-migration-direct-3.gradle.kts
- source: devtools/gradle/gradle-app-plugin/src/test/resources/documentation/application-plugin-migration/direct/groovy/build.gradle.quarkus4
  target: gradle-application-plugin-migration-direct-4.gradle
- source: devtools/gradle/gradle-app-plugin/src/test/resources/documentation/application-plugin-migration/direct/kotlin/build.gradle.kts.quarkus4
  target: gradle-application-plugin-migration-direct-4.gradle.kts
- source: devtools/gradle/gradle-app-plugin/src/test/resources/documentation/application-plugin-migration/coexistence/groovy/build.gradle
  target: gradle-application-plugin-migration-coexistence.gradle
- source: devtools/gradle/gradle-app-plugin/src/test/resources/documentation/application-plugin-migration/coexistence/kotlin/build.gradle.kts
  target: gradle-application-plugin-migration-coexistence.gradle.kts
- source: devtools/gradle/gradle-app-plugin/src/test/resources/documentation/application-plugin-migration/coexistence/groovy/build.gradle.standalone-first
  target: gradle-application-plugin-migration-standalone-first.gradle
- source: devtools/gradle/gradle-app-plugin/src/test/resources/documentation/application-plugin-migration/coexistence/kotlin/build.gradle.kts.standalone-first
  target: gradle-application-plugin-migration-standalone-first.gradle.kts
- source: devtools/gradle/gradle-app-plugin/src/test/resources/documentation/application-plugin-migration/coexistence/groovy/build.gradle.standalone-only
  target: gradle-application-plugin-migration-standalone-only.gradle
- source: devtools/gradle/gradle-app-plugin/src/test/resources/documentation/application-plugin-migration/coexistence/kotlin/build.gradle.kts.standalone-only
  target: gradle-application-plugin-migration-standalone-only.gradle.kts
