= Using Hibernate ORM and JPA
:config-file: microprofile-config.properties

Hibernate ORM is the de facto JPA implementation and offers you the full breath of an Object Relational Mapper.
It works beautifully in {project-name}.

== Setting up and configuring Hibernate ORM without `persistence.xml` (recommended)

More often than not, you need one _persistence unit_ with few configuration options.
In {project-name}, you just need to:

* add your settings in `{config-file}`
* annotate your entities with `@Entity` and friends

and we make some opinionated choices and educated guesses.

In your `pom.xml`, add the following dependencies:

* JPA extension
* Agroal extension (the database connection pool)
* your JDBC driver extension (`jdbc-postgresql-deployment`, `jdbc-h2-deployment`, `jdbc-mariadb-deployment`, ...)
* and generic {project-name} extensions: CDI (arc)

[source,xml]
--
<dependencies>
    <!-- Hibernate ORM specific dependencies -->
    <dependency>
        <groupId>org.jboss.shamrock</groupId>
        <artifactId>shamrock-jpa-deployment</artifactId>
        <scope>provided</scope>
    </dependency>
    <dependency>
        <groupId>org.jboss.shamrock</groupId>
        <artifactId>shamrock-agroal-deployment</artifactId>
        <scope>provided</scope>
    </dependency>

    <!-- JDBC driver dependencies -->
    <dependency>
        <groupId>org.jboss.shamrock</groupId>
        <artifactId>jdbc-postgresql-deployment</artifactId>
        <scope>provided</scope>
    </dependency>

    <!-- General Protean dependencies -->
    <dependency>
        <groupId>org.jboss.shamrock</groupId>
        <artifactId>shamrock-arc-deployment</artifactId>
        <scope>provided</scope>
    </dependency>
</dependencies>
--

Finally add the relevant configuration properties in `{config-file}`.

[source,properties]
--
shamrock.datasource.url: jdbc:postgresql://localhost:5432/mydatabase
shamrock.datasource.driver: org.postgresql.Driver
shamrock.datasource.username: sarah
shamrock.datasource.password: connor
--

An `EntityManagerFactory` will be created based on {project-name} `datasource` configuration as long as the Hibernate ORM extension is declared in your `pom.xml`.
The dialect will be selected based on the JDBC driver.

You can then happily inject your `EntityManager`:

[source,java]
--
@ApplicationScoped
public class SantaClausService {
    @Inject private EntityManager em; <1>

    @Transactional <2>
    public void createGift(String giftDescription) {
        Gift gift = new Gift();
        gift.setName(giftDescription);
        em.persist(gift);
    }
}
--

<1> Inject your entity manager and have fun
<2> Mark your CDI bean method as `@Transactional` and the `EntityManager` will enlist and flush at commit.

=== Properties to refine your Hibernate ORM configuration

There are optional properties useful to refine your `EntityManagerFactory` or guide guesses of {project-name}.

`shamrock.hibernate.dialect`:: (e.g. `org.hibernate.dialect.PostgreSQL95Dialect`).
Class name of the Hibernate ORM dialect.

`shamrock.hibernate.schema-generation.database.action`::
(e.g. `drop-and-create` which is awesome in development mode). Select whether the database schema is generated or not.
Options are `none`, `create`, `drop-and-create`, `drop`

`shamrock.hibernate.show_sql`:: (defaults to `false`).
Show SQL logs and format them nicely.

[NOTE]
--
Do not mix `persistence.xml` and `shamrock.hibernate.*` properties in `{config-file}`.
{project-name} will raise an exception.
Make up your mind on which approach you want to use.
--

[TIP]
====
Want to start a PostgreSQL server on the side with Docker?

[source]
--
docker run --ulimit memlock=-1:-1 -it --rm=true --memory-swappiness=0 --name postgres-protean-hibernate -e POSTGRES_USER=hibernate -e POSTGRES_PASSWORD=hibernate -e POSTGRES_DB=hibernate_db -p 5432:5432 postgres:10.5
--

====

== Setting up and configuring Hibernate ORM with a `persistence.xml`

Alternatively, you can set a `META-INF/persistence.xml` to setup Hibernate ORM.
This is useful for:

* migrating existing code
* when you have relatively complex settings requiring the full flexibility of the configuration
* or if you like it the good old way

[NOTE]
--
If you have a `persistence.xml`, then you cannot use the `shamrock.hibernate.*` properties
and only persistence units defined in `persistence.xml` will be taken into account.
--

In your `pom.xml`, add the following dependencies:

* JPA extension
* Agroal extension (the database connection pool)
* your JDBC driver extension (`jdbc-postgresql-deployment`, `jdbc-h2-deployment`, `jdbc-mariadb-deployment`, ...)
* and generic {project-name} extensions: CDI (arc)

[source,xml]
--
<dependencies>
    <!-- Hibernate ORM specific dependencies -->
    <dependency>
        <groupId>org.jboss.shamrock</groupId>
        <artifactId>shamrock-jpa-deployment</artifactId>
        <scope>provided</scope>
    </dependency>
    <dependency>
        <groupId>org.jboss.shamrock</groupId>
        <artifactId>shamrock-agroal-deployment</artifactId>
        <scope>provided</scope>
    </dependency>

    <!-- JDBC driver dependencies -->
    <dependency>
        <groupId>org.jboss.shamrock</groupId>
        <artifactId>jdbc-postgresql-deployment</artifactId>
        <scope>provided</scope>
    </dependency>

    <!-- General Protean dependencies -->
    <dependency>
        <groupId>org.jboss.shamrock</groupId>
        <artifactId>shamrock-arc-deployment</artifactId>
        <scope>provided</scope>
    </dependency>
</dependencies>
--

Then add your `persistence.xml` in `META-INF`:

[source,xml]
--
<persistence xmlns="http://xmlns.jcp.org/xml/ns/persistence"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/persistence
             http://xmlns.jcp.org/xml/ns/persistence/persistence_2_1.xsd"
             version="2.1">

    <persistence-unit name="CustomerPU" transaction-type="JTA">

        <description>My customer entities</description>

        <properties>
            <!-- Connection specific -->
            <property name="hibernate.dialect" value="org.hibernate.dialect.PostgreSQL95Dialect"/>

            <property name="hibernate.show_sql" value="true"/>
            <property name="hibernate.format_sql" value="true"/>

            <!--
                Optimistically create the tables;
                will cause background errors being logged if they already exist,
                but is practical to retain existing data across runs (or create as needed) -->
            <property name="javax.persistence.schema-generation.database.action" value="drop-and-create"/>

            <property name="javax.persistence.validation.mode" value="NONE"/>
        </properties>

    </persistence-unit>
</persistence>
--

A `EntityManagerFactory` will be created based on {project-name} `datasource` configuration as long as the Hibernate ORM extension is declared in your `pom.xml`.

You can then happily inject your `EntityManager`:

[source,java]
--
@ApplicationScoped
public class SantaClausService {
    @Inject private EntityManager em; <1>

    @Transactional <2>
    public void createGift(String giftDescription) {
        Gift gift = new Gift();
        gift.setName(giftDescription);
        em.persist(gift);
    }
}
--

<1> Inject your entity manager and have fun
<2> Mark your CDI bean method as `@Transactional` and the `EntityManager` will enlist and flush at commit.


