////
This guide is maintained in the main Quarkus repository
and pull requests should be submitted there:
https://github.com/quarkusio/quarkus/tree/main/docs/src/main/asciidoc
////
= Hibernate Search guide
:hibernate-search-doc-prefix: https://docs.jboss.org/hibernate/search/6.0/reference/en-US/html_single/
include::./attributes.adoc[]

You have a Hibernate ORM-based application? You want to provide a full-featured full-text search to your users? You're at the right place.

With this guide, you'll learn how to synchronize your entities to an Elasticsearch cluster in a heart beat with Hibernate Search.
We will also explore how you can can query your Elasticsearch cluster using the Hibernate Search API.

== Prerequisites

To complete this guide, you need:

* less than 20 minutes
* an IDE
* JDK 11+ installed with `JAVA_HOME` configured appropriately
* Apache Maven {maven-version}
* Docker
* link:building-native-image[GraalVM installed if you want to run in native mode]

== Architecture

The application described in this guide allows to manage a (simple) library: you manage authors and their books.

The entities are stored in a PostgreSQL database and indexed in an Elasticsearch cluster.

== Solution

We recommend that you follow the instructions in the next sections and create the application step by step.
However, you can go right to the completed example.

Clone the Git repository: `git clone {quickstarts-clone-url}`, or download an {quickstarts-archive-url}[archive].

The solution is located in the `hibernate-search-orm-elasticsearch-quickstart` {quickstarts-tree-url}/hibernate-search-orm-elasticsearch-quickstart[directory].

[NOTE]
====
The provided solution contains a few additional elements such as tests and testing infrastructure.
====

== Creating the Maven project

First, we need a new project. Create a new project with the following command:

[source,bash,subs=attributes+]
----
mvn io.quarkus:quarkus-maven-plugin:{quarkus-version}:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=hibernate-search-orm-elasticsearch-quickstart \
    -DclassName="org.acme.hibernate.search.elasticsearch.LibraryResource" \
    -Dpath="/library" \
    -Dextensions="resteasy,hibernate-orm-panache,hibernate-search-orm-elasticsearch,resteasy-jackson,jdbc-postgresql"
cd hibernate-search-orm-elasticsearch-quickstart
----

This command generates a Maven structure importing the following extensions:

 * Hibernate ORM with Panache,
 * the PostgreSQL JDBC driver,
 * Hibernate Search + Elasticsearch,
 * RESTEasy and Jackson.

If you already have your Quarkus project configured, you can add the `hibernate-search-orm-elasticsearch` extension
to your project by running the following command in your project base directory:

[source,bash]
----
./mvnw quarkus:add-extension -Dextensions="hibernate-search-orm-elasticsearch"
----

This will add the following to your `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-hibernate-search-orm-elasticsearch</artifactId>
</dependency>
----

[IMPORTANT]
====
For now, let's delete the two generated tests `LibraryResourceTest` and `NativeLibraryResourceIT` present in `src/test/java`.
If you are interested in how you can test this application, just refer to the solution in the quickstarts Git repository:
it contains a lot of tests and the required testing infrastructure.
====

== Creating the bare entities

First, let's create our Hibernate ORM entities `Book` and `Author` in the `model` subpackage.

[source,java]
----
package org.acme.hibernate.search.elasticsearch.model;

import java.util.List;
import java.util.Objects;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

import io.quarkus.hibernate.orm.panache.PanacheEntity;

@Entity
public class Author extends PanacheEntity { // <1>

    public String firstName;

    public String lastName;

    @OneToMany(mappedBy = "author", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.EAGER) // <2>
    public List<Book> books;

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof Author)) {
            return false;
        }

        Author other = (Author) o;

        return Objects.equals(id, other.id);
    }

    @Override
    public int hashCode() {
        return 31;
    }
}
----
<1> We are using Hibernate ORM with Panache, it is not mandatory.
<2> We are loading these elements eagerly so that they are present in the JSON output.
In a real world application, you should probably use a DTO approach.

[source,java]
----
package org.acme.hibernate.search.elasticsearch.model;

import java.util.Objects;

import javax.persistence.Entity;
import javax.persistence.ManyToOne;

import com.fasterxml.jackson.annotation.JsonIgnore;

import io.quarkus.hibernate.orm.panache.PanacheEntity;

@Entity
public class Book extends PanacheEntity {

    public String title;

    @ManyToOne
    @JsonIgnore <1>
    public Author author;

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof Book)) {
            return false;
        }

        Book other = (Book) o;

        return Objects.equals(id, other.id);
    }

    @Override
    public int hashCode() {
        return 31;
    }
}
----
<1> We mark this property with `@JsonIgnore` to avoid infinite loops when serializing with Jackson.

== Initializing the REST service

While everything is not yet set up for our REST service, we can initialize it with the standard CRUD operations we will need.

Just copy this content in the `LibraryResource` file created by the Maven `create-project` command:

[source,java]
----
package org.acme.hibernate.search.elasticsearch;

import javax.transaction.Transactional;
import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

import org.acme.hibernate.search.elasticsearch.model.Author;
import org.acme.hibernate.search.elasticsearch.model.Book;
import org.jboss.resteasy.annotations.jaxrs.FormParam;
import org.jboss.resteasy.annotations.jaxrs.PathParam;

@Path("/library")
public class LibraryResource {

    @PUT
    @Path("book")
    @Transactional
    @Consumes(MediaType.APPLICATION_FORM_URLENCODED)
    public void addBook(@FormParam String title, @FormParam Long authorId) {
        Author author = Author.findById(authorId);
        if (author == null) {
            return;
        }

        Book book = new Book();
        book.title = title;
        book.author = author;
        book.persist();

        author.books.add(book);
        author.persist();
    }

    @DELETE
    @Path("book/{id}")
    @Transactional
    public void deleteBook(@PathParam Long id) {
        Book book = Book.findById(id);
        if (book != null) {
            book.author.books.remove(book);
            book.delete();
        }
    }

    @PUT
    @Path("author")
    @Transactional
    @Consumes(MediaType.APPLICATION_FORM_URLENCODED)
    public void addAuthor(@FormParam String firstName, @FormParam String lastName) {
        Author author = new Author();
        author.firstName = firstName;
        author.lastName = lastName;
        author.persist();
    }

    @POST
    @Path("author/{id}")
    @Transactional
    @Consumes(MediaType.APPLICATION_FORM_URLENCODED)
    public void updateAuthor(@PathParam Long id, @FormParam String firstName, @FormParam String lastName) {
        Author author = Author.findById(id);
        if (author == null) {
            return;
        }
        author.firstName = firstName;
        author.lastName = lastName;
        author.persist();
    }

    @DELETE
    @Path("author/{id}")
    @Transactional
    public void deleteAuthor(@PathParam Long id) {
        Author author = Author.findById(id);
        if (author != null) {
            author.delete();
        }
    }
}
----

Nothing out of the ordinary here: it is just good old Hibernate ORM with Panache operations in a standard JAX-RS service.

In fact, the interesting part is that we will need to add very few elements to make our full text search application working.

== Using Hibernate Search annotations

Let's go back to our entities.

Enabling full text search capabilities for them is as simple as adding a few annotations.

Let's edit the `Book` entity again to include this content:

[source,java]
----
package org.acme.hibernate.search.elasticsearch.model;

import java.util.Objects;

import javax.persistence.Entity;
import javax.persistence.ManyToOne;

import org.hibernate.search.mapper.pojo.mapping.definition.annotation.FullTextField;
import org.hibernate.search.mapper.pojo.mapping.definition.annotation.Indexed;

import com.fasterxml.jackson.annotation.JsonIgnore;

import io.quarkus.hibernate.orm.panache.PanacheEntity;

@Entity
@Indexed // <1>
public class Book extends PanacheEntity {

    @FullTextField(analyzer = "english") // <2>
    public String title;

    @ManyToOne
    @JsonIgnore
    public Author author;

    // Preexisting equals()/hashCode() methods
}
----
<1> First, let's use the `@Indexed` annotation to register our `Book` entity as part of the full text index.
<2> The `@FullTextField` annotation declares a field in the index specifically tailored for full text search.
In particular, we have to define an analyzer to split and analyze the tokens (~ words) - more on this later.

Now that our books are indexed, we can do the same for the authors.

Open the `Author` class and include the content below.

Things are quite similar here: we use the `@Indexed`, `@FullTextField` and `@KeywordField` annotations.

There are a few differences/additions though. Let's check them out.

[source,java]
----
package org.acme.hibernate.search.elasticsearch.model;

import java.util.List;
import java.util.Objects;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

import org.hibernate.search.engine.backend.types.Sortable;
import org.hibernate.search.mapper.pojo.mapping.definition.annotation.FullTextField;
import org.hibernate.search.mapper.pojo.mapping.definition.annotation.Indexed;
import org.hibernate.search.mapper.pojo.mapping.definition.annotation.IndexedEmbedded;
import org.hibernate.search.mapper.pojo.mapping.definition.annotation.KeywordField;

import io.quarkus.hibernate.orm.panache.PanacheEntity;

@Entity
@Indexed
public class Author extends PanacheEntity {

    @FullTextField(analyzer = "name") // <1>
    @KeywordField(name = "firstName_sort", sortable = Sortable.YES, normalizer = "sort") // <2>
    public String firstName;

    @FullTextField(analyzer = "name")
    @KeywordField(name = "lastName_sort", sortable = Sortable.YES, normalizer = "sort")
    public String lastName;

    @OneToMany(mappedBy = "author", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.EAGER)
    @IndexedEmbedded // <3>
    public List<Book> books;

    // Preexisting equals()/hashCode() methods
}
----
<1> We use a `@FullTextField` similar to what we did for `Book` but you'll notice that the analyzer is different - more on this later.
<2> As you can see, we can define several fields for the same property.
Here, we define a `@KeywordField` with a specific name.
The main difference is that a keyword field is not tokenized (the string is kept as one single token) but can be normalized (i.e. filtered) - more on this later.
This field is marked as sortable as our intention is to use it for sorting our authors.
<3> The purpose of `@IndexedEmbedded` is to include the `Book` fields into the `Author` index.
In this case, we just use the default configuration: all the fields of the associated `Book` entities are included in the index (i.e. the `title` field).
The nice thing with `@IndexedEmbedded` is that it is able to automatically reindex an `Author` if one of its ``Book``s has been updated thanks to the bidirectional relation.
`@IndexedEmbedded` also supports nested documents (using the `storage = NESTED` attribute) but we don't need it here.
You can also specify the fields you want to include in your parent index using the `includePaths` attribute if you don't want them all.

== Analyzers and normalizers

=== Introduction

Analysis is a big part of full text search: it defines how text will be processed when indexing or building search queries.

The role of analyzers is to split the text into tokens (~ words) and filter them (making it all lowercase and removing accents for instance).

Normalizers are a special type of analyzers that keeps the input as a single token.
It is especially useful for sorting or indexing keywords.

There are a lot of bundled analyzers but you can also develop your own for your own specific purposes.

You can learn more about the Elasticsearch analysis framework in the https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis.html[Analysis section of the Elasticsearch documentation].

=== Defining the analyzers used

When we added the Hibernate Search annotations to our entities, we defined the analyzers and normalizers used.
Typically:

[source,java]
----
@FullTextField(analyzer = "english")
----

[source,java]
----
@FullTextField(analyzer = "name")
----

[source,java]
----
@KeywordField(name = "lastName_sort", sortable = Sortable.YES, normalizer = "sort")
----

We use:

 * an analyzer called `name` for person names,
 * an analyzer called `english` for book titles,
 * a normalizer called `sort` for our sort fields

but we haven't set them up yet.

Let's see how you can do it with Hibernate Search.

[[analysis-configurer]]
=== Setting up the analyzers

It is an easy task, we just need to create an implementation of `ElasticsearchAnalysisConfigurer`
(and configure Quarkus to use it, more on that later).

To fulfill our requirements, let's create the following implementation:

[source,java]
----
package org.acme.hibernate.search.elasticsearch.config;

import org.hibernate.search.backend.elasticsearch.analysis.ElasticsearchAnalysisConfigurationContext;
import org.hibernate.search.backend.elasticsearch.analysis.ElasticsearchAnalysisConfigurer;

import javax.enterprise.context.Dependent;
import javax.inject.Named;

@Dependent
@Named("myAnalysisConfigurer") // <1>
public class AnalysisConfigurer implements ElasticsearchAnalysisConfigurer {

    @Override
    public void configure(ElasticsearchAnalysisConfigurationContext context) {
        context.analyzer("name").custom() // <2>
                .tokenizer("standard")
                .tokenFilters("asciifolding", "lowercase");

        context.analyzer("english").custom() // <3>
                .tokenizer("standard")
                .tokenFilters("asciifolding", "lowercase", "porter_stem");

        context.normalizer("sort").custom() // <4>
                .tokenFilters("asciifolding", "lowercase");
    }
}
----
<1> We will need to reference the configurer from the configuration properties, so we make it a named bean.
<2> This is a simple analyzer separating the words on spaces, removing any non-ASCII characters by its ASCII counterpart (and thus removing accents) and putting everything in lowercase.
It is used in our examples for the author's names.
<3> We are a bit more aggressive with this one and we include some stemming: we will be able to search for `mystery` and get a result even if the indexed input contains `mysteries`.
It is definitely too aggressive for person names but it is perfect for the book titles.
<4> Here is the normalizer used for sorting. Very similar to our first analyzer, except we don't tokenize the words as we want one and only one token.

== Adding full text capabilities to our REST service

In our existing `LibraryResource`, we just need to inject the `SearchSession`:

[source,java]
----
    @Inject
    SearchSession searchSession; // <1>
----
<1> Inject a Hibernate Search session, which relies on the `EntityManager` under the hood.
Applications with multiple persistence units can use the CDI qualifier `@io.quarkus.hibernate.orm.PersistenceUnit`
to select the right one:
see <<multiple-persistence-units-attaching-cdi>>.

And then we can add the following methods (and a few ``import``s):

[source,java]
----
    @Transactional // <1>
    void onStart(@Observes StartupEvent ev) throws InterruptedException { // <2>
        // only reindex if we imported some content
        if (Book.count() > 0) {
            searchSession.massIndexer()
                    .startAndWait();
        }
    }

    @GET
    @Path("author/search") // <3>
    @Transactional
    public List<Author> searchAuthors(@QueryParam String pattern, // <4>
            @QueryParam Optional<Integer> size) {
        return searchSession.search(Author.class) // <5>
                .where(f ->
                    pattern == null || pattern.trim().isEmpty() ?
                            f.matchAll() : // <6>
                            f.simpleQueryString()
                                .fields("firstName", "lastName", "books.title").matching(pattern) // <7>
                )
                .sort(f -> f.field("lastName_sort").then().field("firstName_sort")) // <8>
                .fetchHits(size.orElse(20)); // <9>
    }
----
<1> Important point: we need a transactional context for these methods.
<2> As we will import data into the PostgreSQL database using an SQL script, we need to reindex the data at startup.
For this, we use Hibernate Search's mass indexer, which allows to index a lot of data efficiently (you can fine tune it for better performances).
All the upcoming updates coming through Hibernate ORM operations will be synchronized automatically to the full text index.
If you don't import data manually in the database, you don't need that:
the mass indexer should then only be used when you change your indexing configuration (adding a new field, changing an analyzer's configuration...) and you want the new configuration to be applied to your existing entities.
<3> This is where the magic begins: just adding the annotations to our entities makes them available for full text search: we can now query the index using the Hibernate Search DSL.
<4> Use the `org.jboss.resteasy.annotations.jaxrs.QueryParam` annotation type to avoid repeating the parameter name.
<5> We indicate that we are searching for ``Author``s.
<6> We create a predicate: if the pattern is empty, we use a `matchAll()` predicate.
<7> If we have a valid pattern, we create a https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html[`simpleQueryString()`] predicate on the `firstName`, `lastName` and `books.title` fields matching our pattern.
<8> We define the sort order of our results. Here we sort by last name, then by first name. Note that we use the specific fields we created for sorting.
<9> Fetch the `size` top hits, `20` by default. Obviously, paging is also supported.

[NOTE]
====
The Hibernate Search DSL supports a significant subset of the Elasticsearch predicates (match, range, nested, phrase, spatial...).
Feel free to explore the DSL using autocompletion.

When that's not enough, you can always fall back to
link:{hibernate-search-doc-prefix}#search-dsl-predicate-extensions-elasticsearch-from-json[defining a predicate using JSON directly].
====

== Configuring the application

As usual, we can configure everything in the Quarkus configuration file, `application.properties`.

Edit `src/main/resources/application.properties` and inject the following configuration:

[source,properties]
----
quarkus.ssl.native=false <1>

quarkus.datasource.db-kind=postgresql <2>
quarkus.datasource.username=quarkus_test
quarkus.datasource.password=quarkus_test
quarkus.datasource.jdbc.url=jdbc:postgresql:quarkus_test

quarkus.hibernate-orm.database.generation=drop-and-create <3>
quarkus.hibernate-orm.sql-load-script=import.sql <4>

quarkus.hibernate-search-orm.elasticsearch.version=7 <5>
quarkus.hibernate-search-orm.elasticsearch.analysis.configurer=bean:myAnalysisConfigurer <6>
quarkus.hibernate-search-orm.schema-management.strategy=drop-and-create <7>
quarkus.hibernate-search-orm.automatic-indexing.synchronization.strategy=sync <8>
----
<1> We won't use SSL so we disable it to have a more compact native executable.
<2> Let's create a PostgreSQL datasource.
<3> We will drop and recreate the schema every time we start the application.
<4> We load some initial data.
<5> We need to tell Hibernate Search about the version of Elasticsearch we will use.
It is important because there are significant differences between Elasticsearch mapping syntax depending on the version.
Since the mapping is created at build time to reduce startup time, Hibernate Search cannot connect to the cluster to automatically detect the version.
<6> We point to the custom `AnalysisConfigurer` which defines the configuration of our analyzers and normalizers.
<7> Obviously, this is not for production: we drop and recreate the index every time we start the application.
<8> This means that we wait for the entities to be searchable before considering a write complete.
On a production setup, the `write-sync` default will provide better performance.
Using `sync` is especially important when testing as you need the entities to be searchable immediately.

[TIP]
For more information about the Hibernate Search extension configuration please refer to the <<configuration-reference, Configuration Reference>>.

== Creating a frontend

Now let's add a simple web page to interact with our `LibraryResource`.
Quarkus automatically serves static resources located under the `META-INF/resources` directory.
In the `src/main/resources/META-INF/resources` directory, overwrite the existing `index.html` file with the content from this
{quickstarts-blob-url}/hibernate-search-orm-elasticsearch-quickstart/src/main/resources/META-INF/resources/index.html[index.html] file.

== Automatic import script

For the purpose of this demonstration, let's import an initial dataset.

Let's create a `src/main/resources/import.sql` file with the following content:

[source,sql]
----
INSERT INTO author(id, firstname, lastname) VALUES (nextval('hibernate_sequence'), 'John', 'Irving');
INSERT INTO author(id, firstname, lastname) VALUES (nextval('hibernate_sequence'), 'Paul', 'Auster');

INSERT INTO book(id, title, author_id) VALUES (nextval('hibernate_sequence'), 'The World According to Garp', 1);
INSERT INTO book(id, title, author_id) VALUES (nextval('hibernate_sequence'), 'The Hotel New Hampshire', 1);
INSERT INTO book(id, title, author_id) VALUES (nextval('hibernate_sequence'), 'The Cider House Rules', 1);
INSERT INTO book(id, title, author_id) VALUES (nextval('hibernate_sequence'), 'A Prayer for Owen Meany', 1);
INSERT INTO book(id, title, author_id) VALUES (nextval('hibernate_sequence'), 'Last Night in Twisted River', 1);
INSERT INTO book(id, title, author_id) VALUES (nextval('hibernate_sequence'), 'In One Person', 1);
INSERT INTO book(id, title, author_id) VALUES (nextval('hibernate_sequence'), 'Avenue of Mysteries', 1);
INSERT INTO book(id, title, author_id) VALUES (nextval('hibernate_sequence'), 'The New York Trilogy', 2);
INSERT INTO book(id, title, author_id) VALUES (nextval('hibernate_sequence'), 'Mr. Vertigo', 2);
INSERT INTO book(id, title, author_id) VALUES (nextval('hibernate_sequence'), 'The Brooklyn Follies', 2);
INSERT INTO book(id, title, author_id) VALUES (nextval('hibernate_sequence'), 'Invisible', 2);
INSERT INTO book(id, title, author_id) VALUES (nextval('hibernate_sequence'), 'Sunset Park', 2);
INSERT INTO book(id, title, author_id) VALUES (nextval('hibernate_sequence'), '4 3 2 1', 2);
----

== Preparing the infrastructure

We need a PostgreSQL instance and an Elasticsearch cluster.

Let's use Docker to start one of each:

[source,bash,subs=attributes+]
----
docker run -it --rm=true --name elasticsearch_quarkus_test -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch-oss:{elasticsearch-version}
----

[source,bash]
----
docker run --ulimit memlock=-1:-1 -it --rm=true --memory-swappiness=0 --name postgresql_quarkus_test -e POSTGRES_USER=quarkus_test -e POSTGRES_PASSWORD=quarkus_test -e POSTGRES_DB=quarkus_test -p 5432:5432 postgres:13.1
----

== Time to play with your application

You can now interact with your REST service:

 * start Quarkus with `./mvnw compile quarkus:dev`
 * open a browser to `http://localhost:8080/`
 * search for authors or book titles (we initialized some data for you)
 * create new authors and books and search for them too

As you can see, all your updates are automatically synchronized to the Elasticsearch cluster.

[[multiple-persistence-units]]
== Multiple persistence units

=== Configuring multiple persistence units

With the Hibernate ORM extension,
link:hibernate-orm#multiple-persistence-units[you can set up multiple persistence units],
each with its own datasource and configuration.

If you do declare multiple persistence units,
you will also configure Hibernate Search separately for each persistence unit.

The properties at the root of the `quarkus.hibernate-search-orm.` namespace define the default persistence unit.
For instance, the following snippet defines a default datasource and a default persistence unit,
and sets the Elasticsearch host for that persistence unit to `es1.mycompany.com:9200`.

[source,properties]
----
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:default;DB_CLOSE_DELAY=-1

quarkus.hibernate-orm.dialect=org.hibernate.dialect.H2Dialect

quarkus.hibernate-search-orm.elasticsearch.hosts=es1.mycompany.com:9200
quarkus.hibernate-search-orm.elasticsearch.version=7
quarkus.hibernate-search-orm.automatic-indexing.synchronization.strategy=write-sync
----

Using a map based approach, it is also possible to configure named persistence units:

[source,properties]
----
quarkus.datasource."users".db-kind=h2 <1>
quarkus.datasource."users".jdbc.url=jdbc:h2:mem:users;DB_CLOSE_DELAY=-1

quarkus.datasource."inventory".db-kind=h2 <2>
quarkus.datasource."inventory".jdbc.url=jdbc:h2:mem:inventory;DB_CLOSE_DELAY=-1

quarkus.hibernate-orm."users".datasource=users <3>
quarkus.hibernate-orm."users".packages=org.acme.model.user

quarkus.hibernate-orm."inventory".datasource=inventory <4>
quarkus.hibernate-orm."inventory".packages=org.acme.model.inventory

quarkus.hibernate-search-orm."users".elasticsearch.hosts=es1.mycompany.com:9200 <5>
quarkus.hibernate-search-orm."users".elasticsearch.version=7
quarkus.hibernate-search-orm."users".automatic-indexing.synchronization.strategy=write-sync

quarkus.hibernate-search-orm."inventory".elasticsearch.hosts=es2.mycompany.com:9200 <6>
quarkus.hibernate-search-orm."inventory".elasticsearch.version=7
quarkus.hibernate-search-orm."inventory".automatic-indexing.synchronization.strategy=write-sync
----
<1> Define a datasource named `users`.
<2> Define a datasource named `inventory`.
<3> Define a persistence unit called `users` pointing to the `users` datasource.
<4> Define a persistence unit called `inventory` pointing to the `inventory` datasource.
<5> Configure Hibernate Search for the `users` persistence unit,
setting the Elasticsearch host for that persistence unit to `es1.mycompany.com:9200`.
<6> Configure Hibernate Search for the `inventory` persistence unit,
setting the Elasticsearch host for that persistence unit to `es2.mycompany.com:9200`.

[[multiple-persistence-units-attaching-model-classes]]
=== Attaching model classes to persistence units

For each persistence unit, Hibernate Search will only consider indexed entities that are attached to that persistence unit.
Entities are attached to a persistence unit by
link:hibernate-orm#multiple-persistence-units-attaching-model-classes[configuring the Hibernate ORM extension].

[[multiple-persistence-units-attaching-cdi]]
== CDI integration

You can inject Hibernate Search's main entry points, `SearchSession` and `SearchMapping`, using CDI:

[source,java]
----
@Inject
SearchSession searchSession;
----

This will inject the `SearchSession` of the default persistence unit.

To inject the `SearchSession` of a named persistence unit (`users` in our example),
just add a qualifier:

[source,java]
----
@Inject
@PersistenceUnit("users") <1>
SearchSession searchSession;
----
<1> This is the `@io.quarkus.hibernate.orm.PersistenceUnit` annotation.

You can inject the `SearchMapping` of a named persistence unit using the exact same mechanism:

[source,java]
----
@Inject
@PersistenceUnit("users")
SearchMapping searchMapping;
----

== Building a native executable

You can build a native executable with the usual command `./mvnw package -Pnative`.

[NOTE]
====
As usual with native executable compilation, this operation consumes a lot of memory.

It might be safer to stop the two containers while you are building the native executable and start them again once you are done.
====

Running it is as simple as executing `./target/hibernate-search-orm-elasticsearch-quickstart-1.0.0-SNAPSHOT-runner`.

You can then point your browser to `http://localhost:8080/` and use your application.

[NOTE]
====
The startup is a bit slower than usual: it is mostly due to us dropping and recreating the database schema and the Elasticsearch mapping every time at startup.
We also inject some data and execute the mass indexer.

In a real life application, it is obviously something you won't do at startup.
====

[[offline-startup]]
== Offline startup

By default, Hibernate Search sends a few requests to the Elasticsearch cluster on startup.
If the Elasticsearch cluster is not necessarily up and running when Hibernate Search starts,
this could cause a startup failure.

To address this, you can configure Hibernate Search to not send any request on startup:

* Disable Elasticsearch version checks on startup by setting the configuration property
  link:#quarkus-hibernate-search-orm-elasticsearch_quarkus.hibernate-search-orm.elasticsearch.version-check.enabled[`quarkus.hibernate-search-orm.elasticsearch.version-check.enabled`]
  to `false`.
* Disable schema management on startup by setting the configuration property
  link:#quarkus-hibernate-search-orm-elasticsearch_quarkus.hibernate-search-orm.schema-management.strategy[`quarkus.hibernate-search-orm.schema-management.strategy`]
  to `none`.

Of course, even with this configuration, Hibernate Search still won't be able to index anything or run search queries
until the Elasticsearch cluster becomes accessible.

[IMPORTANT]
====
If you disable automatic schema creation by setting `quarkus.hibernate-search-orm.schema-management.strategy` to `none`,
you will have to create the schema manually at some point before your application starts persisting/updating entities
and executing search requests.

See link:{hibernate-search-doc-prefix}#mapper-orm-schema-management-manager[this section of the reference documentation]
for more information.
====

[[aws-request-signing]]
== AWS request signing

If you need to use https://docs.aws.amazon.com/elasticsearch-service/[Amazon’s managed Elasticsearch service],
you will find it requires a proprietary authentication method involving request signing.

To enable AWS request signing, an additional extension is required:

[source,bash]
----
./mvnw quarkus:add-extension -Dextensions="hibernate-search-orm-elasticsearch-aws"
----

Once the extension is there, you will need some more configuration:

* Configure the AWS region with
link:#quarkus-hibernate-search-orm-elasticsearch-aws_quarkus.hibernate-search-orm.elasticsearch.aws.region[`quarkus.hibernate-search-orm.elasticsearch.aws.region`].
* Enable request signing with
link:#quarkus-hibernate-search-orm-elasticsearch-aws_quarkus.hibernate-search-orm.elasticsearch.aws.signing.enabled[`quarkus.hibernate-search-orm.elasticsearch.aws.signing.enabled`].
* Optionally, configure how credentials are retrieved with
link:#quarkus-hibernate-search-orm-elasticsearch-aws_quarkus.hibernate-search-orm.elasticsearch.aws.credentials.type[`quarkus.hibernate-search-orm.elasticsearch.aws.credentials.type`].
The default gets the credentials from the application environment (AWS instance role, ...),
but several more options are available.

For example:

[source,properties]
----
quarkus.hibernate-search-orm.elasticsearch.aws.region=us-east-1
quarkus.hibernate-search-orm.elasticsearch.aws.signing.enabled=true
----

Or, if credentials are not available in the application environment (AWS instance role, ...):

[source,properties]
----
quarkus.hibernate-search-orm.elasticsearch.aws.region=us-east-1
quarkus.hibernate-search-orm.elasticsearch.aws.signing.enabled=true
quarkus.hibernate-search-orm.elasticsearch.aws.credentials.type=static
quarkus.hibernate-search-orm.elasticsearch.aws.credentials.static-provider.access-key-id=AKIDEXAMPLE
quarkus.hibernate-search-orm.elasticsearch.aws.credentials.static-provider.secret-access-key=wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY
----

== Further reading

If you are interested in learning more about Hibernate Search 6,
the Hibernate team publishes link:{hibernate-search-doc-prefix}[an extensive reference documentation].

== FAQ

=== Why Elasticsearch only?

Hibernate Search supports both a Lucene backend and an Elasticsearch backend.

In the context of Quarkus and to build microservices, we thought the latter would make more sense.
Thus we focused our efforts on it.

We don't have plans to support the Lucene backend in Quarkus for now.

[[configuration-reference]]
== Hibernate Search Configuration Reference

[[configuration-reference-main]]
=== Main Configuration

include::{generated-dir}/config/quarkus-hibernate-search-orm-elasticsearch.adoc[leveloffset=+1, opts=optional]

[NOTE]
[[bean-reference-note-anchor]]
.About bean references
====
When referencing beans using a string value in configuration properties, that string is parsed.

Here are the most common formats:

* `bean:` followed by the name of a `@Named` CDI bean.
For example `bean:myBean`.
* `class:` followed by the fully-qualified name of a class, to be instantiated through CDI if it's a CDI bean,
or through its public, no-argument constructor otherwise.
For example `class:com.mycompany.MyClass`.
* An arbitrary string referencing a built-in implementation.
Available values are detailed in the documentation of each configuration property,
such as `async`/`read-sync`/`write-sync`/`sync` for
<<quarkus-hibernate-search-orm-elasticsearch_quarkus.hibernate-search-orm.automatic-indexing.synchronization.strategy,`quarkus.hibernate-search-orm.automatic-indexing.synchronization.strategy`>>.

Other formats are also accepted, but are only useful for advanced use cases.
See link:{hibernate-search-doc-prefix}#configuration-bean-reference-parsing[this section of Hibernate Search's reference documentation]
for more information.
====

:no-duration-note: true

[[configuration-reference-aws]]
=== AWS Integration Configuration

include::{generated-dir}/config/quarkus-hibernate-search-orm-elasticsearch-aws.adoc[leveloffset=+1, opts=optional]
