= Developing with {project-name}

== Creating a new project

Remember, you need to configure Maven as indicated on the link:maven-config.html[Maven configuration].
Then, you can scaffold a new project with:

[source,subs=attributes+]
----
mvn org.jboss.shamrock:shamrock-maven-plugin:{shamrock-version}:create \
    -DprojectGroupId=my-groupId \
    -DprojectArtifactId=my-artifactId \
    -DprojectVersion=my-version \
    -DclassName="org.my.group.MyResource"
----

The following table lists the attributes you can pass to the `create` command:

[cols=3*,options="header"]
|===
| Attribute
| Default Value
| Description

| `projectGroupId`
| _mandatory_
| The group id of the created project

| `projectArtifactId`
| _mandatory_
| The artifact id of the created project

| `projectVersion`
| 1.0-SNAPSHOT
| The version of the created project

| `shamrockVersion`
| {shamrock-version}
| The Shamrock version

| `className`
| _Not created is omitted_
| The fully qualified name of the generated resource

| `path`
| `/hello`
| The resource path

| `root`
| `/app`
| The application root prefix

| `extensions`
| _[]_
| The list of extensions to add to the project (comma-separated)

|===

If you decide to generate a REST resource (using the `className` attribute), the endpoint is exposed at: `http://localhost:8080/$root/$path`.
If you use the default values, the URL is: http://localhost:8080/app/hello.

The project is either generated in the current directory or in a directory named after the passed artifactId.
If the current directory is empty, the project is generated in-place.

== Dealing with extensions

You can list extensions with: `mvn shamrock:list-extensions`.
You can enable an extension using:

[source]
mvn shamrock:add-extension -Dextensions="validation"

Extensions are passed using a comma-separated list.

== Development mode

Shamrock comes with a built-in development mode.
Run you application with:

[source]
mvn compile shamrock:dev

You can then update the application sources, resources and configurations.
The changes are automatically reflected in your running application.

== Import in your IDE

Once you have a <<Creating a new project, project generated>>, you can import it in your favorite IDE.
The only requirement is the ability to import a Maven project.

**Eclipse**

In Eclipse, click on: `File -> Import`.
In the wizard, select: `Maven -> Existing Maven Project`.
On the next screen, select the root location of the project.
The next screen list the found modules; select the generated project and click on `Finish`. Done!

// Until https://github.com/protean-project/shamrock/issues/232 is fixed:
In a separated terminal, run `mvn compile shamrock:dev`, and enjoy a highly productive environment.

**IntelliJ**

In IntelliJ:

1. From inside IntelliJ select `File -> New -> Project From Existing Sources...` or, if you are on the welcome dialog, select `Import project`.
2. Select the project root
3. Select `Import project from external model` and `Maven`
4. Next a few times (review the different options if needed)
5. On the last screen click on Finish

In a separated terminal or in the embedded terminal, run `mvn compile shamrock:dev`. Enjoy!

**Apache Netbeans**

In Netbeans:

1. Select `File -> Open Project`
2. Select the project root
3. Click on `Open Project`

In a separated terminal or the embedded terminal, go to the project root and run `mvn compile shamrock:dev`. Enjoy!

**Visual Studio Code**

Open the project directory in VS Code. If you have installed the Java Extension Pack (grouping a set of Java extensions), the project is loaded as a Maven project.