////
This guide is maintained in the main Quarkus repository
and pull requests should be submitted there:
https://github.com/quarkusio/quarkus/tree/main/docs/src/main/asciidoc
////
= Infinispan Client Extension Reference Guide
include::_attributes.adoc[]
:categories: data
:summary: Infinispan is an in memory distributed data store and cache server that offers flexible deployment options and robust capabilities for storing, managing, and processing data.
:topics: data,infinispan
:extensions: io.quarkus:quarkus-infinispan-client

Infinispan is a distributed, in-memory key/value store that provides Quarkus applications with a highly configurable
and independently scalable data layer.
This extension gives you client functionality that connects applications running on Quarkus with remote Infinispan clusters.
To get started with Infinispan, we recommend:

1. Following the https://infinispan.org/get-started/[Get Started Tutorial] (5 minutes).
2. Running the *remote cache* https://infinispan.org/tutorials/[simple code tutorials].

Learn more in the https://infinispan.org/documentation[Infinispan documentation].

== Installation

Run the following command in the base directory of your Quarkus project to add the `infinispan-client` extension:

:add-extension-extensions: infinispan-client
include::{includes}/devtools/extension-add.adoc[]

This command adds the following dependency to your build file:

[source,bash,subs=attributes+,role="primary asciidoc-tabs-sync-maven"]
.Maven
----
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-infinispan-client</artifactId>
</dependency>
----

[source,gradle,role="secondary asciidoc-tabs-target-sync-gradle"]
.Gradle
----
implementation 'io.quarkus:quarkus-infinispan-client'
annotationProcessor 'org.infinispan.protostream:protostream-processor:{infinispan-protostream-version}' <1>
----
<1> Mandatory in the Gradle build to enable the generation of the files in the annotation based serialization

[IMPORTANT]
====
You must include the Protostream annotations processor in your build file.
Starting with Java 24, schema generation will not work unless this annotation processor
is explicitly added.

[source,bash,subs=attributes+,role="primary asciidoc-tabs-sync-maven"]
.Maven
----
<plugin>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>${compiler-plugin.version}</version>
    <configuration>
        <annotationProcessorPaths>
            <path>
                <groupId>org.infinispan.protostream</groupId>
                <artifactId>protostream-processor</artifactId>
            </path>
        </annotationProcessorPaths>
    </configuration>
</plugin>
----
====

== Connection to Infinispan

=== Running the server

You need at least one running instance of the Infinispan Server.

.Development mode

If you are running a Docker instance, you can use xref:infinispan-dev-services.adoc[Infinispan Dev Services]
and connect without configuration.

If you want to run the server yourself using Docker, check out the 5-minute https://infinispan.org/get-started/[Getting stated with Infinispan]
tutorial to run Infinispan Server

You can also https://infinispan.org/download/[download] {infinispan-version} Server bare metal distribution and run the following command
from the distribution folder.
[source,bash]
----
$ ./bin/server.sh
----

Infinispan Server *enables authentication and security authorization by default*, so you need to create a user with permissions.

* If you run the *Infinispan Server image*, pass the `USER="admin"` and `PASS="password"` parameters.
* If you run the *bare metal distribution*, use the Command Line Interface (CLI) as follows:
+
[source,bash]
----
$ ./bin/cli.sh user create admin -p password
----

.Production mode

In Kubernetes, we recommend the https://infinispan.org/docs/infinispan-operator/main/operator.html[Infinispan Operator].
Additionally, grab a look to
the https://infinispan.org/tutorials/simple/simple_tutorials.html#cross-site-replication_remote-cache-tutorials[Cross Site Replication]
tutorial. You will learn how to run two separate Infinispan Clusters with docker compose (for local dev) and the Operator.

=== Configuring the connection

If you are running an Infinispan Server, add the following properties to connect in the
`application.properties` file in the `src/main/resources` directory.

[source,properties]
----
quarkus.infinispan-client.hosts=localhost:11222 <1>

quarkus.infinispan-client.username=admin <2>
quarkus.infinispan-client.password=password <3>
----
<1> Sets Infinispan Server address list, separated with semicolons
<2> Sets the authentication username
<3> Sets the authentication password

Alternatively, you can use uri connection by providing a single connection property
[source,properties]
----
quarkus.infinispan-client.uri=hotrod://admin:password@localhost:11222 <1>
----
<1> Sets Infinispan URI connection. The following properties will be ignored: hosts, username and password.

[TIP]
====
Use Infinispan Dev Services to run a server and connect without configuration.
====

=== Configuring backup clusters in Cross-Site Replication
In High Availability production deployments, it is common to have multiple Infinispan Clusters that are
distributed across various Data Centers worldwide. Infinispan offers the capability to connect these clusters and
configure backups between them. This enables seamless switching between clusters through both automated and manual
methods using a single connection. To achieve this, it is necessary to configure the client to direct to the backup
clusters.

[source,properties]
----
quarkus.infinispan-client.hosts=host1:11222;host2:3122 <1>
quarkus.infinispan-client.username=admin
quarkus.infinispan-client.password=password
quarkus.infinispan-client.backup-cluster.nyc-site.hosts=nyc1:11222;nyc2:21222;nyc3:31222 <2>
quarkus.infinispan-client.backup-cluster.lon-site.hosts=lon1:11222;lon2:21222;lon3:31222 <3>
----
<1> Sets Infinispan Server address list, separated with semicolons. This is the default cluster.
<2> Configures a backup site 'nyc-site' with the provided address list
<3> Configures an additional backup site 'lon-site' with the provided address list

Based on the provided configuration, in the event of the default cluster becoming unavailable, the client will
seamlessly transition to one of the accessible backup clusters.
Additionally, there is also the option to manually switch the client to an alternate cluster:

[source,java]
----
@ApplicationScoped
public class InfinispanExample {
    @Inject
    RemoteCacheManager cacheManager;

    public void doSomething() {
       cacheManager.switchToCluster("nyc-site"); //<1>
       cacheManager.switchToCluster("lon-site"); //<2>
       cacheManager.switchToDefaultCluster(); //<3>
    }
}
----
<1> The client connects to the 'nyc-site'.
<2> The client connects to the 'lon-site'.
<3> The client connects to the default site.

By default, Protobuf Schemas will also be uploaded to the backup clusters. However, it might be required to handle
the registration manually as a schema may evolve over time when used in production, so you can
disable this from occurring in each backup site by configuring the
`quarkus.infinispan-client.backup-cluster.YOUR_SITE_NAME.use-schema-registration` to `false`.
The value of this property will be ignored if the `use-schema-registration` global property is `false`.

[NOTE]
====
Cross-site replication is a powerful feature offered by Infinispan that facilitates data backup between clusters
situated in geographically diverse data centers, even spanning across various cloud providers.
Learn more in the link:https://infinispan.org/docs/stable/titles/xsite/xsite.html[Infinispan documentation].
====

=== Default and named connections
This extension lets you configure a _default_ Infinispan client connections and _named_ ones.
Named connections are essential to connect to multiple Infinispan clusters.

The default connection is configured using the `quarkus.infinispan-client.*` properties as seen above.
When using the default connection, you can inject using a _plain_ `@Inject`:

_Named_ clients are configured using the `quarkus.infinispan-client.<name>.*` properties:

[source,properties]
----
quarkus.infinispan-client.site-lon.hosts=localhost:11222
quarkus.infinispan-client.site-lon.username=admin
quarkus.infinispan-client.site-lon.password=password

quarkus.infinispan-client.site-nyc.hosts=localhost:31222
quarkus.infinispan-client.site-nyc.username=admin
quarkus.infinispan-client.site-nyc.password=password
----

Use the `@InfinispanClientName` qualifier with dependency injection:
[source,java]
----
@ApplicationScoped
public class InfinispanExample {
    @Inject
    @InfinispanClientName("site-lon")
    RemoteCacheManager rcmLon;

    @Inject
    @InfinispanClientName("site-nyc")
    RemoteCacheManager rmcNyc;
}
----

=== Infinispan Health Check
If you are using the quarkus-smallrye-health extension, the Infinispan client extensions will automatically add a readiness health check to validate the connection.

When you access the `/q/health/ready` endpoint of your application you will have information about the server connection and available caches.

This behavior can be disabled via the property `quarkus.infinispan-client.health.enabled`.

=== Tracing with OpenTelemetry
Infinispan supports instrumentation of the server via OpenTelemetry. Having the `quarkus-opentelemetry` extension will propagate
the traces from the Infinispan Client to the Server.
This behavior can be disabled via the property `quarkus.infinispan-client.tracing.propagation.enabled`

=== Creating caches from the client
When a cache is accessed from the client, if the cache does not exist in the Infinispan Server and you want
to create it on first access, use one of the following properties:

[source,properties]
----
quarkus.infinispan-client.cache.magazine.configuration=<distributed-cache><encoding media-type="application/x-protostream"/></distributed-cache> <1>
quarkus.infinispan-client.cache.books.configuration-resource=booksDistributedCache.json <2>
quarkus.infinispan-client.cache.authors.configuration-uri=/file/authorsIndexedCache.yaml <3>
----
<1> The configuration in xml of the 'magazine' (yaml and json are also supported)
<2> The file name located under the `resources` folder that contains the configuration of the 'books' cache
<3> A provided file URI. The file URI can also be a file under resources

If  `configuration-resource`, `configuration` and `configuration-uri` are configured for the same cache with
the same Quarkus profile, `configuration-uri` gets the highest preference, over `configuration-resource` and `configuration`.
`configuration-resource` gets preference over `configuration`.

[WARNING]
====
The `configuration-resource` is build time property and the file will be included in the native build automatically.
`configuration-uri` can also point to a file under the `resources` folder. However, the file won't be automatically included
in the native executable, unless you configure the property `quarkus.native.resources.includes`.
====

[TIP]
====
Cache configuration can be provided in XML, JSON or YAML. Use the Infinispan Console and the cache configuration Wizard
to learn more about Infinispan Caches and create guided configurations.
====

If nothing is configured for a particular cache, it will be created with the following basic configuration:

.XML
[source,xml,options="nowrap",subs=attributes+,role="primary"]
----
<distributed-cache>
    <encoding media-type="application/x-protostream"/>
</distributed-cache>
----

.JSON
[source,json,options="nowrap",subs=attributes+,role="secondary"]
----
{
    "distributed-cache": {
        "encoding": {
            "media-type": "application/x-protostream"
        }
    }
}
----

.YAML
[source,yaml,options="nowrap",subs=attributes+,role="secondary"]
----
distributedCache:
  encoding:
    mediaType: "application/x-protostream"
----

=== Authentication mechanisms

You can use the following authentication mechanisms with the Infinispan client:

* DIGEST-SHA-512 (default)
* DIGEST-MD5
* PLAIN (recommended only in combination with TLS encryption)
* EXTERNAL

Other authentication mechanisms, such as SCRAM and GSSAPI, are not yet verified with the Infinispan client.

You can find more information on configuring authentication in https://infinispan.org/docs/stable/titles/hotrod_java/hotrod_java.html#hotrod_endpoint_auth-hotrod-client-configuration[Hot Rod Endpoint Authentication Mechanisms].

NOTE: You must configure authentication in the `hotrod-client.properties` file if you use Dependency Injection.

== Serialization (Key Value types support)

By default, the client will support keys and values of the following types: byte[],
primitive wrappers (e.g. Integer, Long, Double), String, Date and Instant. User types require
some additional steps that are detailed here. Let's say we have the following user classes:

.Author.java
[source,java]
----
public record Author(String name, String surname) {
}
----

.Book.java
[source,java]
----
public record Book(String title,
                   String description,
                   int publicationYear,
                   Set<Author> authors,
                   Type bookType,
                   BigDecimal price) {
}
----

Serialization of user types uses a library based on protobuf,
called https://github.com/infinispan/protostream[Protostream].

[TIP]
====
Infinispan caches can store keys and values in different encodings, but recommend using https://developers.google.com/protocol-buffers[Protocol Buffers (Protobuf)].

For more information see our https://infinispan.org/docs/stable/titles/encoding/encoding.html[Cache Encoding and Marshalling] guide.
====


=== Annotation based Serialization

This can be done automatically by adding protostream annotations to your user classes.
In addition, a single Initializer annotated interface is required which controls how
the supporting classes are generated.

Here is an example of how the preceding classes should be changed:

.Author.java
[source,java]
----
@Proto //<1>
public record Author(String name, String surname) { //<2>
}
----
<1> Since Protostream 5.0, a single annotation is needed to generate a default mapping
<2> Since Protostream 5.0, records are supported

.Type.java
[source,java]
----
@Proto
public enum Type { //<1>
    FANTASY,
    PROGRAMMING
}
----
<1> Enums are supported

.Book.java
[source,java]
----
@Proto
@Indexed // <1>
public record Book(@Text String title, //<2>
                   @Keyword(projectable = true, sortable = true, normalizer = "lowercase", indexNullAs = "unnamed", norms = false) //<3>
                   String description,
                   int publicationYear,
                   Set<Author> authors, // <4>
                   Type bookType,
                   BigDecimal price) { // <5>
}
----
<1> Indicates that the entity will be indexed. Necessary to perform distributed full-text query operations.
<2> Indicates the `title` should be indexed as text
<3> Indicates the `description` field field should be indexed as a Keyword.
<4> Collections are supported
<5> Protostream provides default Protobuf mappers for commonly used types as `BigDecimal`, included in the `org.infinispan.protostream.types` package.

Then all that is required is a very simple `GeneratedSchema` interface with an annotation
on it to specify configuration settings

.BooksSchema.java
[source,java]
----
import org.infinispan.protostream.GeneratedSchema;
import org.infinispan.protostream.annotations.ProtoSchema;
import org.infinispan.protostream.types.java.math.BigDecimalAdapter;

@ProtoSchema(includeClasses = { Book.class, Author.class, BigDecimalAdapter.class }, schemaPackageName = "book_sample")
interface BookStoreSchema extends GeneratedSchema {
}
----

[TIP]
====
You can use the `basePackages` property to scan a full package containing your classes.
You can override the default marshalling by using the `@Protofield` annotation.
====

So in this case we will automatically generate the marshaller and schemas for the included classes and
place them in the schema package automatically. The package does not have to be provided, but if you use Infinispan search capabilities, you must know the generated package.

NOTE: In Quarkus the `schemaFileName` and `schemaFilePath` attributes should NOT be set on the `ProtoSchema` annotation. Setting either attributes causes native runtime errors.

=== Custom serialization

The previous method is suggested for any case when the user can annotate their classes.
Unfortunately the user may not be able to annotate all classes they will put in the
cache. In this case you must define your schema and create your own Marshaller(s)
yourself.

Protobuf schema:: You can supply a protobuf schema through either one of two ways.
. Proto File
 +
You can put the `.proto` file in the `META-INF` directory of the project. These files will
automatically be picked up at initialization time.
+
.library.proto
----
package book_sample;

message Book {
  required string title = 1;
  required string description = 2;
  required int32 publicationYear = 3; // no native Date type available in Protobuf
  repeated Author authors = 4;
  requited double price = 5; // no native BigDecimal type available in Protobuf but you can use the adapter
}

message Author {
  required string name = 1;
  required string surname = 2;
}
----
. In Code
 +
Or you can define the proto schema directly in user code by defining a produced bean of type
`org.infinispan.protostream.schema.Schema`.
+
[source,java]
----
   @Produces
   Schema bookSchema() {
        return new Schema.Builder("book.proto")
                .packageName("book_sample")
                .addMessage("Author")
                     .addField(Type.Scalar.STRING, "name", 1)
                     .addField(Type.Scalar.STRING, "surname", 2)
                .addMessage("Book")
                     .addField(Type.Scalar.STRING, "title", 1)
                     .addField(Type.Scalar.STRING, "description", 2)
                     .addField(Type.Scalar.INT32, "publicationYear", 3)
                     .addRepeatedField(Type.create("Author"), "author", 4)
                     .addField(Type.Scalar.DOUBLE, "price", 5)
                .build();
    }
----
User Marshaller::
The last thing to do is to provide a `org.infinispan.protostream.MessageMarshaller` implementation
for each user class defined in the proto schema. This class is then provided via `@Produces` in a similar
fashion to the code based proto schema definition above.
+
Here is the Marshaller class for our Author & Book classes.
+
NOTE: The type name must match the `<protobuf package>.<protobuf message>` exactly!
+
.AuthorMarshaller.java
[source,java]
----
public class AuthorMarshaller implements MessageMarshaller<Author> {

   @Override
   public String getTypeName() {
      return "book_sample.Author";
   }

   @Override
   public Class<? extends Author> getJavaClass() {
      return Author.class;
   }

   @Override
   public void writeTo(ProtoStreamWriter writer, Author author) throws IOException {
      writer.writeString("name", author.getName());
      writer.writeString("surname", author.getSurname());
   }

   @Override
   public Author readFrom(ProtoStreamReader reader) throws IOException {
      String name = reader.readString("name");
      String surname = reader.readString("surname");
      return new Author(name, surname);
   }
}
----
+
.BookMarshaller.java
[source,java]
----
public class BookMarshaller implements MessageMarshaller<Book> {

   @Override
   public String getTypeName() {
      return "book_sample.Book";
   }

   @Override
   public Class<? extends Book> getJavaClass() {
      return Book.class;
   }

   @Override
   public void writeTo(ProtoStreamWriter writer, Book book) throws IOException {
      writer.writeString("title", book.getTitle());
      writer.writeString("description", book.getDescription());
      writer.writeInt("publicationYear", book.getPublicationYear());
      writer.writeCollection("authors", book.getAuthors(), Author.class);
      writer.writeDouble("price", book.getPrice().doubleValue());
   }

   @Override
   public Book readFrom(ProtoStreamReader reader) throws IOException {
      String title = reader.readString("title");
      String description = reader.readString("description");
      int publicationYear = reader.readInt("publicationYear");
      Set<Author> authors = reader.readCollection("authors", new HashSet<>(), Author.class);
      BigDecimal price = BigDecimal.valueOf(reader.readDouble("price"));
      return new Book(title, description, publicationYear, authors, price);
   }
}
----
+
And you pass the marshaller by defining the following:
+
[source,java]
----
   @Produces
   MessageMarshaller authorMarshaller() {
      return new AuthorMarshaller();
   }

   @Produces
   MessageMarshaller bookMarshaller() {
      return new BookMarshaller();
   }
----
NOTE: The above produced Marshaller method MUST return `MessageMarshaller` without types or else it will not be found.

== Dependency Injection

As you saw above we support the user injecting Marshaller configuration. You can do the inverse with
the Infinispan client extension providing injection for `RemoteCacheManager` and `RemoteCache` objects.
There is one global `RemoteCacheManager` that takes all the configuration
parameters setup in the above sections.

It is very simple to inject these components. All you need to do is to add the `@Inject` annotation to
the field, constructor or method. In the below code we utilize field and constructor injection.

.SomeClass.java
[source,java]
----
    @Inject
    SomeClass(RemoteCacheManager remoteCacheManager) {
       this.remoteCacheManager = remoteCacheManager;
    }

    @Inject
    @Remote("myCache")
    RemoteCache<String, Book> cache;

    RemoteCacheManager remoteCacheManager;
----

If you notice the `RemoteCache` declaration has an additional annotation named `Remote`.
This is a *qualifier* annotation allowing you to specify which named cache that will be injected. This
annotation is not required and if it is not supplied, the default cache will be injected.
The RemoteCacheManager and RemoteCache bean scope is `@ApplicationScoped`.

For non default connections, combine the qualifier `@InfinispanClientName` and `@Remote`.

.SomeClass.java
[source,java]
----
    @Inject
    @InfinispanClientName("lon-site")
    @Remote("books")
    RemoteCache<String, Book> lonBooks;

    @Inject
    @InfinispanClientName("nyc-site")
    @Remote("books")
    RemoteCache<String, Book> nycBooks;
----


NOTE: Other types may be supported for injection, please see other sections for more information

=== Mock Support
Quarkus supports the use of mock objects using two different approaches. You can either use CDI alternatives to
mock out a bean for all test classes, or use `QuarkusMock` to mock out beans on a per test basis.
Check the xref:getting-started-testing.adoc[Getting started with testing guide] for more information.

RemoteCacheManager and RemoteCache can be mocked.

.BookService.java
[source,java]
----
@ApplicationScoped
public class BookService {

   @Inject
   @Remote("books")
   RemoteCache<String, Book> books; //<1>

   public String getBookDescriptionById(String id) {
      Book book = books.get(id);
      if (book == null) {
         return "default";
      }

      return book.getDescription();
   }
}
----
<1> Use dependency injection to connect to the books cache

In the test class, the RemoteCache can be mocked.

.BookServiceTest.java
[source,java]
----
@QuarkusTest
public class BookServiceTest {

    @Inject
    BookService bookService;

    @InjectMock // <1>
    @Remote("books")
    RemoteCache<String, Book> bookRemoteCache;

    @Test
    public void mockRemoteCache() {
        Mockito.when(bookRemoteCache.get("harry_potter")).thenReturn(new Book(... "Best saga ever");//<2>

        Assertions.assertThat(bookService.getBookDescriptionById("harry_potter")).isEqualTo("Best saga ever");//<3>
    }
}
----
<1> Inject a mock instead of the RemoteCache bean
<2> Use Mockito to mock the call of the RemoteCache
<3> Assert the service call

=== Registering Protobuf Schemas with Infinispan Server
You need to register the generated Protobuf schemas with Infinispan Server to perform queries or convert from
`Protobuf` to other media types such as `JSON`.

[TIP]
====
You can check the schemas that exist under the `Schemas` tab by logging into
Infinispan Console at `http://SERVER_HOST:SERVER_PORT` (for example `http://localhost:11222`).

Check the xref:infinispan-dev-services.adoc[Infinispan Dev Services Guide] to connect to the Infinispan
Dev Services server.
====

By default, Protobuf schemas generated this way will be registered by this extension when the client first connects.
However, it might be required to handle the registration manually as a schema may evolve over time when used in
production, so you can disable this from occurring by configuring the
`quarkus.infinispan-client.use-schema-registration` to `false`.

To configure the schema manually
please use https://infinispan.org/docs/infinispan-operator/main/operator.html[Infinispan Operator]
for Kubernetes deployments, Infinispan Console,
https://infinispan.org/docs/stable/titles/rest/rest.html#rest_v2_protobuf_schemas[REST API] or the
https://infinispan.org/docs/stable/titles/encoding/encoding.html#registering-sci-remote-caches_marshalling[Hot Rod Java Client].

[[infinispan-annotations-api]]
=== Caching using annotations

[IMPORTANT]
====
Infinispan Caching annotations are deprecated *in this extension* and will be removed.
Use or replace your annotations by using the xref:cache-infinispan-reference.adoc[Infinispan Cache extension].
Update your import statements to use the annotations from `io.quarkus.cache` package instead of
`io.quarkus.infinispan.client`.
====

The Infinispan Client extension offers a set of annotations that can be used in a CDI managed bean to enable caching abilities with Infinispan.

[WARNING]
====
Caching annotations are not allowed on private methods.
They will work fine with any other access modifier including package-private (no explicit modifier).
====

=== @CacheResult

Loads a method result from the cache without executing the method body whenever possible.

When a method annotated with `@CacheResult` is invoked, Quarkus will use the method argument as the cache key and check in the cache whether the method has been already invoked.
Methods with multiple parameters are not allowed. For composite keys, define a Protobuf schema that will hold multiple values.
If a value is found in the cache, it is returned and the annotated method is never actually executed.
If no value is found, the annotated method is invoked and the returned value is stored in the cache using the computed key.
This annotation cannot be used on a method returning `void`.

NOTE: Infinispan Client extension is not able yet to cache `null` values unlike the Quarkus-Cache extension.

=== @CacheInvalidate

Removes an entry from the cache.

When a method annotated with `@CacheInvalidate` is invoked, Infinispan will use the method argument as a cache key to try to remove an existing entry from the cache.
If the key does not identify any cache entry, nothing will happen.

=== @CacheInvalidateAll

When a method annotated with `@CacheInvalidateAll` is invoked, Infinispan will remove all entries from the cache.


== Querying

The Infinispan client supports both indexed and non-indexed search as long as the
`ProtoStreamMarshaller` is configured above. This allows the user to query on *keys* or
*values* based on the properties of the proto schema. *Indexed queries are preferred for performance reasons*.

.XML
[source,xml,options="nowrap",subs=attributes+,role="primary"]
----
<distributed-cache name="books" statistics="true">
    <!-- other configuration -->
	<indexing enabled="true" storage="filesystem" startup-mode="PURGE">
		<indexed-entities>
			<indexed-entity>book_sample.Book</indexed-entity>
		</indexed-entities>
	</indexing>
</distributed-cache>
----

.JSON
[source,json,options="nowrap",subs=attributes+,role="secondary"]
----
{
  "books": {
    "distributed-cache": {
      ...
      "indexing": {
        "enabled": true,
        "storage": "filesystem",
        "startupMode": "PURGE",
        "indexed-entities": [
          "book_sample.Book"
        ]
      }
    }
  }
}
----

.YAML
[source,yaml,options="nowrap",subs=attributes+,role="secondary"]
----
distributedCache:
  # other configuration
  indexing:
    enabled: "true"
    storage: "filesystem"
    startupMode: "PURGE"
    indexedEntities:
      - "book_sample.Book"
----

Query builds upon the proto definitions you can configure when setting up the `ProtoStreamMarshaller`.
Either method of Serialization above will automatically register the schema with the server at
startup, meaning that you will automatically gain the ability to query objects stored in the
remote Infinispan Server.

.Book.java
[source,java]
----
@Indexed <1>
public class Book {

    @ProtoFactory
    public Book(String title, String description, int publicationYear, Set<Author> authors) {
      ...
    }

    @ProtoField(number = 1)
    @Text <2>
    public String getTitle() {
        return title;
    }

    @ProtoField(number = 2)
    @Keyword(projectable = true, sortable = true, normalizer = "lowercase", indexNullAs = "unnamed", norms = false) <3>
    public String getDescription() {
        return description;
    }
    ...
----
<1> `@Indexed` annotation makes the POJO indexable
<2> `@Basic` annotation is used for indexed fields without any special transformation
<3> `@Keyword` annotation is used to apply a normalizer to a text field

You can use either the Query DSL or the Ickle Query language with the Quarkus Infinispan client
extension.

.Query.java
[source,java]
----
@Inject
@Remote("books")
RemoteCache<String, Book> booksCache; //<1>

Query<Book> query = booksCache.query("from book_sample.Book b where b.authors.name like '%" + name + "%'"); //<2>
List<Book> list = query.execute().list();
----
<1> Inject the books cache
<2> Perform a full text query on books author name

NOTE: You can read more about https://infinispan.org/docs/stable/titles/query/query.html[querying] in the Infinispan documentation.

[IMPORTANT]
====
Prior to Quarkus 3.9 and the Infinispan 15 integration, queries were executed by calling the following code:
.Query.java
[source,java]
----
QueryFactory queryFactory = Search.getQueryFactory(booksCache); <1>
Query query = queryFactory.create("from book_sample.Book");
List<Book> list = query.execute().list();
----
<1> Breaking change in 3.9

This code won't work anymore since `RemoteCache` is now an `@ApplicationScoped` proxy bean.
`Search.getQueryFactory` will raise a ClassCastException.
Remove the unecessary indirection by using the `query` method in the `RemoteCache` API as follows.

[source,java]
----
Query<Book> query = booksCache.<Book>query("from book_sample.Book");
List<Book> list = query.execute().list();
----
====

== Counters

Infinispan also has a notion of counters and the Quarkus Infinispan client supports them out of
the box.

The Quarkus Infinispan client extension allows for Dependency Injection
of the `CounterManager` directly. All you need to do is annotate your field, constructor or method,
and you get it with no fuss. You can then use counters as you would normally.

[source,java]
----
@Inject
CounterManager counterManager;
----

You can read more about https://infinispan.org/docs/stable/titles/developing/developing.html#clustered_counters[clustered counters] in the Infinispan documentation.

== Near Caching

Near caching is disabled by default, but you can enable it on a per cache basic by configuring the following properties:

[source,properties]
----
quarkus.infinispan-client.cache.books.near-cache-mode=INVALIDATED <1>
quarkus.infinispan-client.cache.books.near-cache-max-entries=200 <2>
quarkus.infinispan-client.cache.books.near-cache-use-bloom-filter=true <3>
----
<1> Enables near caching for the 'books' cache by setting the mode to `INVALIDATED`
<2> Sets the maximum number of entries that the near cache of the 'books' cache can hold before eviction occurs
<3> Enables bloom filter for the 'books' cache

=== Bounded near caching

You should always use bounded near caches by specifying the maximum number of entries they can contain.

=== Bloom filters

If you need to optimize the performance for write operations by reducing the total number of invalidation messages,
enable bloom filter. Bloom filters reside on Infinispan Server and keep track of the entries that the client has requested.
They cannot be used with unbounded near cache: maximum number of entries must be defined when enabling bloom filters.

== Encryption

Encryption at this point requires additional steps to get working.

The first step is to configure the `application.properties` file to point to your truststore
and/or keystore. This is further detailed https://infinispan.org/docs/stable/titles/hotrod_java/hotrod_java.html#hotrod_encryption[here].

The Infinispan Client extension enables SSL/TLS by default. You can read more about this
at xref:native-and-ssl.adoc[Using SSL With Native Executables].

== SSL Host Name Validation

To prevent MITM attacks, when SSL is enabled, SSL host name validation is enabled by default in Infinispan.
In this case, configuring the SNI host name is mandatory to start the client.

[source,properties]
----
quarkus.infinispan-client.sni-host-name=localhost <1>
----
<1> Sets the SNI host name

This behaviour can be changed by disabling the validation.

[source,properties]
----
quarkus.infinispan-client.ssl-host-name-validation=false <1>
----
<1> Disables ssl host name validation

== Additional Features

The Infinispan Client has additional features that were not mentioned here. This means this
feature was not tested in a Quarkus environment, and they may or may not work. Please let us
know if you need these added!

[[dev-services]]
== Dev Services for Infinispan

When you use the infinispan-client extension in dev mode or in test, Quarkus automatically starts an Infinispan server
and configure your application.

=== Enabling / Disabling Dev Services for Infinispan

NOTE: Learn more in the xref:infinispan-dev-services.adoc[Infinispan Dev Services guide].

== Shared server

Quarkus will share the Infinispan broker if you have multiple applications running in dev mode.
Dev Services for Infinispan implements a _service discovery_ mechanism for your multiple Quarkus applications running in _dev_ mode to share a single broker.

NOTE: Dev Services for Infinispan starts the container with the `quarkus-dev-service-infinispan` label which is used to identify the container.

If you need multiple (shared) Infinispan server, you can configure the `quarkus.infinispan-client.devservices.service-name` attribute and indicate the server name.
It looks for a container with the same value, or starts a new one if none can be found.
The default service name is `infinispan`.

Sharing is enabled by default in dev mode, but disabled in test mode.
You can disable the sharing with `quarkus.infinispan-client.devservices.shared=false`.

== Setting the port

By default, Dev Services for Infinispan picks a random port and configures the application.
You can set the port by configuring the `quarkus.infinispan-client.devservices.port` property.

== Configuration Reference

include::{generated-dir}/config/quarkus-infinispan-client.adoc[opts=optional, leveloffset=+1]
