////
This guide is maintained in the main Quarkus repository
and pull requests should be submitted there:
https://github.com/quarkusio/quarkus/tree/main/docs/src/main/asciidoc
////
= Dev Services for Jaeger
:extension-status: preview
include::_attributes.adoc[]
:categories: data
:summary: Start Jaeger automatically in dev and test modes.

Quarkus supports a feature called Dev Services that allows you to run collect traces without any config.
What that means practically, is that if you have docker running and have not configured `quarkus.jaeger.endpoint`,
Quarkus will automatically start a Jaeger container when running tests or dev mode, and automatically configure the connection.

Available properties to customize the Jaeger DevService.

include::{generated-dir}/config/quarkus-jaeger-config-group-devservices-dev-services-config.adoc[opts=optional, leveloffset=+1]

When running the production version of the application, the Jaeger connection needs to be configured as normal,
so if you want to include a production tracing config in your `application.properties` and continue to use Dev Services
we recommend that you use the `%prod.` profile to define your Jaeger configuration settings.

Dev Services for Jaeger relies on Docker to start the server.
If your environment does not support Docker, you will need to start the server manually, or connect to an already running server.

NOTE: If you want to disable ryuk container, set variable `TESTCONTAINERS_RYUK_DISABLED=true`.

== Shared server

Most of the time you need to share the server between multiple applications.
Dev Services for Jaeger implements a _service discovery_ mechanism for your multiple Quarkus applications running in _dev_ mode to share a single server.
This results in having _all_ traces from all traced microservices in the same container. Even after the original microservice is
shut down, the container persists. This can be changed with setting `testcontainers.reuse.enable=false` under `~/.testcontainers.properties` file.


NOTE: Dev Services for Jaeger starts the container with the `quarkus-dev-service-jaeger` label which is used to identify the container.

If you need multiple (shared) servers, you can configure the `quarkus.jaeger.devservices.service-name` attribute and indicate the server name.
It looks for a container with the same value, or starts a new one if none can be found.
The default service name is `jaeger`.
