= How do we measure performance

This guide covers:

* how we measure memory usage
* how we measure startup time

All of our tests are run on the same hardware for a given batch.
It goes without saying but it's better when you say it.

== How do we measure memory usage

When measuring the footprint of a {project-name} application, we measure https://fr.wikipedia.org/wiki/Resident_set_size[Resident Set Size (RSS)]
and not the JVM heap size which is only a small part of the overall problem.
The JVM not only allocates the heap size (`-Xms`, `-Xmx`) but also some native structure (class meta data etc).

It is important to measure the whole memory to see the impact of a Cloud Native application.
It is particularly true of containers which will kill a process based on its full memory usage.

Likewise, don't fall into the trap of only measuring private memory which is what the process uses that is not shareable with other processes.
While private memory might be useful in a environment deploying many different applications (and thus sharing memory a lot),
it is very misleading in environments like Kubernetes/OpenShift.

Here is how we measure memory usage in various operating systems:

Linux::
TODO
Windows::
TODO
macOS::
TODO

== How do we measure startup time

Some frameworks use aggressive lazy initialization techniques.
It is important to measure the startup time to first request to most accurately reflect how long a framework needs to start.
Otherwise, you will miss the time the framework _actually_ takes to initialize.

Here is how we measure startup time in our tests.

TODO