= What is Protean

:toc: macro
:toclevels: 4
:doctype: book
:icons: font
:docinfo1:

:numbered:
:sectnums:
:sectnumlevels: 4
:project-name: Protean

[quote]
--
{project-name} is a Cloud Native, Container First framework for writing Java applications.
--

Container First::
Minimal footprint Java applications optimal for running in containers
Cloud Native::
Embraces 12 factor architecture in environments like Kubernetes.
Unify imperative and reactive::
Brings under one programming model non blocking and imperative styles of development.
Standards-based::
Based on the standards and frameworks you love and use (RESTEasy, Hibernate, Netty, Eclipse Vert.x, Apache Camel...)
Microservice First::
Brings lightning fast startup time and code turn around to Java apps
Developer Joy::
Development centric experience without compromise to bring your amazing apps to life in no time

All under one framework.

== Scratch pad


{project-name} believes in developer Joy.


It unifies imperative and reactive.
It's a Microservice first toolkit.

Standards based
Protean brings all the standards and frameworks you love and use: RESTEasy, Hibernate, Netty, vert.x, Camel...)

Imperative and Reactive

* ahead-of-time native binary (executable binary)
* Cloud Native
* Java
* modular
* Substrate VM native

Seamlessly build container optimal

Container affinity

Container optimal

* low memory
* low startup time
* ahead of time optimal

Unifying Imperative and Reactive under one framework.

Usability
* easy to use
* productive environemnt
* hot reload

Standards based


