////
This guide is maintained in the main Quarkus repository
and pull requests should be submitted there:
https://github.com/quarkusio/quarkus/tree/main/docs/src/main/asciidoc
////
= Quarkus Data Hibernate reference guide
include::_attributes.adoc[]
:summary: Hibernate is the de facto Jakarta Persistence implementation and offers you the full breadth of an Object Relational Mapper. Quarkus Data Hibernate focuses on making simple and common mappings trivial.
:config-file: application.properties
:topics: data,hibernate-orm,hibernate-reactive,panache,sql,jdbc
:extensions: io.quarkus:quarkus-data-hibernate,io.quarkus:quarkus-hibernate-orm,io.quarkus:quarkus-hibernate-reactive
:hibernate-panache-api: https://javadoc.io/doc/io.quarkus.data.hibernate/hibernate-panache/{quarkus-version}
:extension-status: experimental

Quarkus Data Hibernate is the perfect solution if you want to get started using Hibernate in Quarkus.

If you are new to Quarkus Data Hibernate, start with the
xref:quarkus-data-hibernate-getting-started.adoc[Quarkus Data Hibernate getting started tutorial].
For native SQL queries, see the
xref:quarkus-data-hibernate-sql.adoc[Quarkus Data Hibernate native SQL tutorial].

This guide does not go into the specifics of using either
xref:hibernate-orm.adoc[Hibernate ORM], or its underlying
link:{jakarta-persistence-spec-url}[Jakarta Persistence specification].
Refer to their documentation for more in-depth knowledge.

include::{includes}/extension-status.adoc[]

WARNING: This extension is currently experimental, so its API may change, in particular names of
classes or packages may change, even the module name. We are in the process of making it a public preview in order
to obtain public feedback, so please report feedback either on link:https://quarkusio.zulipchat.com/#narrow/channel/187038-dev/topic/WG.20-.20Panache.2ENext/with/562916276[Zulip]
or via link:https://github.com/orgs/quarkusio/projects/50/views/1[GitHub issues].

== Installation

Quarkus Data Hibernate uses an annotation processor to inspect your entities and repository interfaces at build time.
It validates repository methods and queries, then generates the repository implementations that Quarkus makes
available as CDI beans. This catches many mapping and query errors during the build instead of at runtime.

To add the required extensions and database driver, configure the datasource, and enable the annotation processor,
follow the xref:quarkus-data-hibernate-getting-started.adoc[Quarkus Data Hibernate getting started tutorial].

== Entities

An entity is a Java class that represents data stored in a database. Typically, the class maps to a table, each entity
instance maps to a row, and its fields map to columns. Quarkus Data Hibernate works with entities defined using
Jakarta Persistence annotations.

=== Defining an entity

In order to map a Java class to a Database table, just:

- Write a class.
- Annotate it with link:{jakarta-persistence-javadocs-url}/jakarta/persistence/entity[`@Entity`].
- Make it extend `ManagedEntity`.
- Make its fields `public`.

[source,java]
----
import io.quarkus.data.hibernate.ManagedEntity;
import jakarta.persistence.Entity;

import java.time.LocalDate;

@Entity
public class Cat extends ManagedEntity {
    public String name;
    public LocalDate birth;
    public Breed breed;

    public enum Breed {
        CUTE, HAIRLESS;
    }
}
----

Instances of `ManagedEntity` are managed by Hibernate ORM. After an instance is persisted, changes to its fields are
automatically sent to the database without an explicit `update` instruction.

[[about-entity-identifiers]]
=== Entity identifiers

`ManagedEntity` comes with a default generated database identifier because it extends `WithId.AutoLong`, which
provides a generated database identifier of type `Long`.

You can choose to extend `WithId.AutoString` for a `String` identifier, `WithId.AutoUUID` for a `UUID` identifier,
or `WithId.AutoUUIDv7` for a unique, time-sortable `UUID` identifier. These types provide an attribute of the form:

[source,java]
----
@Id
public IdType id;
----

WARNING: The identifier will not be automatically generated in this case, so you have to set its value manually on creation.

You can also provide your own database identifier explicitly and implement the `ManagedEntity.CustomId` interface in
your entity, as well as use the `ManagedRepository.CustomId` interface for your repository, to specify the database
identifier type:

[source,java]
----
@Entity
public class CatWithId implements ManagedEntity.CustomId {
    @Id
    public String id;
    public String name;

    public interface Repo extends ManagedRepository.CustomId<CatWithId, String> {
        @Find
        CatWithId findByName(String name);
    }
}
----

The following entity supertypes provide an identifier. You do not have to extend one of these types if you define your
own identifier:

[cols="1,1,1"]
|===
|ID type|Supertype|Shortcut type

|`Long`
|`WithId.AutoLong`
|`ManagedEntity`

|`UUID`
|`WithId.AutoUUID`
|

|`UUID`
|`WithId.AutoUUIDv7`
|

|`String`
|`WithId.String`
|

|`T`
|`WithId<Id>`
|

|===

== Repositories

A Quarkus Data Hibernate repository is:

- An interface nested in the entity (though it could be a top-level interface if you prefer)
- Which extends the `ManagedRepository` interface, with the entity in question as type parameter
- And contains query methods, annotated with either `@Find` or `@HQL` or even `@SQL` (for native queries), or
`default` methods with implementation of queries

[source,java]
----
@Entity
public class Cat extends ManagedEntity {
    public String name;
    public LocalDate birth;
    public Breed breed;

    public enum Breed {
        CUTE, HAIRLESS;
    }

    public interface Repo extends ManagedRepository<Cat> {
        @Find
        Cat findByName(String name);

        @HQL("where breed = CUTE")
        List<Cat> findCute();

        @HQL("delete from Cat where name = :name")
        long deleteByName(String name);

        @HQL("delete from Cat where breed = HAIRLESS")
        long deleteHairless();
    }
}
----

=== Generated finder and query methods

You can use `@Find` methods to find single instances or collections of entities by using the parameters of the method
to build a query. The Hibernate documentation contains the complete
link:https://docs.jboss.org/hibernate/orm/{hibernate-orm-version-major-minor}/introduction/html_single/Hibernate_Introduction.html#generated-finder-methods[generated finder method reference].

.A few common examples
[source,java]
----
@Find
List<Cat> findAllCats(); <1>

@Find
long countAllCats(); <2>

@Find
Cat findCatByNameAndBreed(String name, Breed breed); <3>
----
<1> Finder methods may return collections of entities
<2> Or generate `COUNT` queries
<3> Or single entities, and any number of parameters which must all match the queried entities.

Alternately, you can use `@HQL` or `@SQL` queries, which support HQL and SQL queries. The Hibernate documentation contains the complete
link:https://docs.jboss.org/hibernate/orm/{hibernate-orm-version-major-minor}/introduction/html_single/Hibernate_Introduction.html#generated-query-methods[generated query method reference].

.Examples of `@HQL` or `@SQL` usage
[source,java]
----
@HQL("from Cat")
List<Cat> findAllCats(); <1>

@HQL("select min(birth) from Cat")
LocalDate oldestCat(); <2>

@HQL("where name = :name and breed = :breed")
Cat findCatByNameAndBreed(String name, Breed breed); <3>
----
<1> Query methods may return collections of entities
<2> Or projections of a single column, even multiple columns with `Object[]` and `List<Object[]>` types
<3> Queries can of course refer to method parameters.

Generated finder and HQL query methods are type-checked at build time. They are validated for entity names, fields,
HQL syntax, and parameter names. Native SQL is validated by the database when the query is executed; see the
xref:quarkus-data-hibernate-sql.adoc[native SQL tutorial].

=== How to use a Repository

Repositories are CDI beans and can be injected where you intend to use them:

[source,java]
----
@Inject
Cat.Repo repo;

@Transactional
public void method() {
    Cat cat = new Cat();
    cat.name = "Lucky";
    cat.birth = LocalDate.of(2015, 01, 12);
    cat.breed = Cat.Breed.CUTE;

    // Persist the cat
    cat.persist();

    // Make a change, no need to update it
    cat.name = "Luckynou";

    // Find our cat
    cat = repo.findByName("Luckynou");

    // Find cute cats
    List<Cat> cuteCats = repo.findCute();

    // Delete our cat
    cat.delete();

    // Delete queries
    repo.deleteByName("Lucky");
    repo.deleteHairless();
}
----

You can also access a nested repository by using a generated static method on the
link:https://docs.jboss.org/hibernate/orm/{hibernate-orm-version-major-minor}/introduction/html_single/Hibernate_Introduction.html#static-metamodel[generated metamodel]
of your entity:

[source,java]
----
Cat_.repo().deleteAll();
----

All repositories defined as nested interfaces of an entity are available under their generated metamodel class through
accessor methods with the same name as the repository. This is equivalent to injecting the repository type and uses CDI
under the hood to look up the repository.

=== The `ManagedRepository` supertype

The `ManagedRepository` type provides most of the operations needed to work with an entity, such as `persist()`,
`delete()`, `isPersistent()`, and `listAll()`.

Here is an example of how it can be used:

[source,java]
----
@Inject
Cat.Repo repo;

@Transactional
public void repositoryOperations(Cat cat) {
    // entity operations
    repo.persist(cat);
    repo.delete(cat);
    boolean isPersistent = repo.isPersistent(cat);
    // operations on all entities
    long count = repo.count();
    long deleted = repo.deleteAll();
    List<Cat> allCats = repo.listAll();
    repo.streamAll().forEach(kitty -> kitty.name = kitty.name.toUpperCase());
    BlockingDataQuery<Cat> catQuery = repo.findAll();
    List<Cat> sortedCats = repo.findAll().sort(Sort.asc("name")).list();
    // operations on the Hibernate session
    repo.flush();
    Session session = repo.getSession();
    // ID-related operations
    boolean wasDeleted = repo.deleteById(cat.id);
    Cat foundCat = repo.findById(cat.id);
    Optional<Cat> optionalCat = repo.findByIdOptional(cat.id);
}
----

=== Dynamically built queries

When defining finder and query operations on a repository, queries are validated and generated at build time. If you
need to construct a query dynamically, use the query methods provided by `ManagedRepository`. These methods accept
query strings, so they are not type-safe.

[source,java]
----
@Inject
Cat.Repo repo;

@Transactional
public void nonTypeSafeQueries() {
    // Find a cat by name
    Cat cat = repo.find(Cat_.NAME, "Lucky").singleResult();
    // All cute cats
    List<Cat> cuteCats = repo.list(Cat_.BREED, Cat.Breed.CUTE);
    // Cats with no known birth date
    repo.stream(Cat_.BIRTH + " is null").forEach(kitty -> System.err.println(kitty));
    // Get rid of non-cute cats
    long deleted = repo.delete(Cat_.BREED, Cat.Breed.HAIRLESS);
    // Count ugly cats with no name
    repo.count("breed = ?1 and name is null", Cat.Breed.HAIRLESS);
    // Make every cat cute
    repo.update("breed = CUTE");
    // Sort results using BlockingDataQuery
    List<Cat> sortedByName = repo.findAll().sort(Sort.asc("name")).list();
    List<Cat> sortedMatches = repo.find("breed = ?1", Cat.Breed.CUTE)
            .sort(Sort.desc("name"))
            .list();
}
----

Sorting is applied on the `BlockingDataQuery` returned by `find()` and `findAll()`, not on the shortcut `list()`,
`listAll()`, `stream()`, or `streamAll()` methods. For a single criterion, pass a `Sort` directly. Use `Order` only
when you need multiple criteria, or when receiving an `Order` from a REST endpoint:

[source,java]
----
List<Cat> byName = repo.findAll().sort(Sort.asc("name")).list();
List<Cat> byNameThenBirth = repo.findAll()
        .sort(Order.by(Sort.asc("name"), Sort.desc("birth")))
        .list();
----

== Session and access models

Quarkus Data Hibernate supports managed and stateless sessions with blocking and reactive APIs.

[[use-stateless-sessions]]
=== Stateless sessions

Subtypes of `ManagedEntity` are managed by Hibernate ORM, and changes to the entity are automatically sent to the
database without requiring an explicit `update` operation.

To make every update operation explicit, use a Hibernate ORM _stateless session_. Extend `RecordEntity` for the entity
and `RecordRepository` for its repository. Compared with a managed entity:

- Changes to entity fields must be explicitly pushed to the database by calling `update()` on the entity or repository.
- Call `insert()` instead of `persist()` to insert the entity.
- The session type is `StatelessSession` instead of `Session`.

Queries and the way you obtain entities remain the same. Stateless sessions can also use <<jakarta-data,Jakarta Data repositories>>.

[[lets-get-reactive]]
=== Reactive access

For reactive access:

- The entity extends `ManagedEntity.Reactive`.
- The repository extends `ManagedRepository.Reactive`.
- Operations return `Uni<T>` instead of `T`, which is the standard Mutiny reactive type.
- Use `@WithTransaction` in place of `@Transactional` and compose operations as usual with Mutiny.

[[reactive-and-stateless]]
==== Reactive stateless sessions

Use `RecordEntity.Reactive` and `RecordRepository.Reactive` for reactive stateless sessions. Changes must be explicitly
pushed by calling `update()`, and insertion uses `insert()` instead of `persist()`.

The xref:quarkus-data-hibernate-getting-started.adoc#reactive[getting started tutorial] describes the
required dependencies and reactive datasource configuration. You can use any of the
xref:hibernate-reactive.adoc#hr-getting-started[supported reactive drivers].

=== Alternative entity and repository accessors

You can access an entity using any supported session model, regardless of the entity supertype. Pick the supertype that
represents the majority of your use cases and use the following accessors for alternative operations:

[cols="1,1,1"]
|===
|Session type|Entity accessor|Equivalent entity type

|`Session`
|`.managedBlocking()`
|`ManagedEntity`

|`StatelessSession`
|`.statelessBlocking()`
|`RecordEntity`

|`Mutiny.Session`
|`.managedReactive()`
|`ManagedEntity.Reactive`

|`Mutiny.StatelessSession`
|`.statelessReactive()`
|`RecordEntity.Reactive`

|===

For repository operations, obtain alternative repositories from the generated metamodel accessors, or inject them with
`@Inject`:

[cols="1,1,1"]
|===
|Session type|Metamodel accessor|Repository type

|`Session`
|`Cat_.managedBlocking()`
|`ManagedRepository<Cat>`

|`StatelessSession`
|`Cat_.statelessBlocking()`
|`RecordRepository<Cat>`

|`Mutiny.Session`
|`Cat_.managedReactive()`
|`ManagedRepository.Reactive<Cat>`

|`Mutiny.StatelessSession`
|`Cat_.statelessReactive()`
|`RecordRepository.Reactive<Cat>`

|===

You can also define any number of repositories for custom operations within an entity. All nested repositories are
available through generated metamodel accessors, such as `Cat_.repo()` and `Cat_.theOtherRepo()`.

=== Entity and repository type matrix

The following table lists the entity and repository supertypes for each operation model and identifier type. You do not
have to extend `WithId<Id>` if you define your own entity identifier field:

[cols="1,1,1,1,1"]
|===
|Session type|ID type|Entity superclass|Entity superinterface|Repository supertype

|`Session` (managed, blocking)
|`Long`
|`ManagedEntity`
|
|`ManagedRepository<Entity>`

|`Session` (managed, blocking)
|`Id`
|`WithId<Id>`
|`ManagedEntity.CustomId`
|`ManagedRepository.CustomId<Entity, Id>`

|`StatelessSession` (stateless, blocking)
|`Long`
|`RecordEntity`
|
|`RecordRepository<Entity>`

|`StatelessSession` (stateless, blocking)
|`Id`
|`WithId<Id>`
|`RecordEntity.CustomId`
|`RecordRepository.CustomId<Entity, Id>`

|`Mutiny.Session` (managed, reactive)
|`Long`
|`ManagedEntity.Reactive`
|
|`ManagedRepository.Reactive<Entity>`

|`Mutiny.Session` (managed, reactive)
|`Id`
|`WithId<Id>`
|`ManagedEntity.Reactive.CustomId`
|`ManagedRepository.Reactive.CustomId<Entity, Id>`

|`Mutiny.StatelessSession` (stateless, reactive)
|`Long`
|`RecordEntity.Reactive`
|
|`RecordRepository.Reactive<Entity>`

|`Mutiny.StatelessSession` (stateless, reactive)
|`Id`
|`WithId<Id>`
|`RecordEntity.Reactive.CustomId`
|`RecordRepository.Reactive.CustomId<Entity, Id>`

|===

== Startup code

For startup code, use `@Transactional` for blocking operations and `@WithTransaction` for reactive operations. See the
xref:lifecycle.adoc#startup_annotation[application lifecycle guide] for information about `@Startup`.

[[jakarta-data]]
== Jakarta Data

Quarkus Data Hibernate builds on the link:{jakarta-data-spec-url}[Jakarta Data] repository model and supports its
annotations directly. Entities can extend a variant of `ManagedEntity` or `RecordEntity`, or neither. The Jakarta Data
API is provided by the `quarkus-data-hibernate` extension, so no additional dependency is required.

Jakarta Data 1.0 defines stateless repository semantics. Use `RecordRepository` for this model, or `ManagedRepository`
when repository operations should use a managed persistence context. Both repository types support Jakarta Data
annotations and provide blocking and reactive variants.

For portable repository methods, use the Jakarta Data `@Find`, `@Query`, and `@Delete` annotations. Quarkus Data
Hibernate also supports the Hibernate-specific `@Find`, `@HQL`, and `@SQL` annotations, which can be used alongside
Jakarta Data annotations in the same repository. The following example uses only Jakarta Data annotations:

[source,java]
----
@Entity
public class Cat {
    @Id
    @GeneratedValue
    public Long id;
    public String name;
    public LocalDate birth;
    public Breed breed;

    public enum Breed {
        CUTE, HAIRLESS;
    }

    public interface Repo extends RecordRepository<Cat, Long> {
        @Find <1>
        Cat findByName(String name);

        @Query("where breed = CUTE") <2>
        List<Cat> findCute();

        @Delete <3>
        long deleteByName(String name);

        @Query("delete from Cat where breed = HAIRLESS") <4>
        long deleteHairless();
    }
}
----
<1> `@Find` defines a finder method from its parameters.
<2> `@Query` defines a query using the Jakarta Data Query Language.
<3> `@Delete` defines a finder-style delete method and can return the number of deleted entities.
<4> A delete operation can also be written explicitly with `@Query`.

Repositories are CDI beans and are also available through generated metamodel accessors such as `Cat_.repo()`.

Refer to the link:https://hibernate.org/repositories/[Hibernate Data Repositories] and
link:{jakarta-data-spec-url}[Jakarta Data] documentation for the complete repository API.

== REST integration

When your application uses both `quarkus-data-hibernate` and `quarkus-rest-jackson`, Quarkus automatically adds REST
support for common Jakarta Data parameter types. You can declare these types directly as REST endpoint parameters, and
they are populated from HTTP query parameters without manual parsing.

=== Supported parameter types

The following Jakarta Data types are automatically mapped from query parameters:

[cols="1,2,1,2"]
|===
|Jakarta Data type|Query parameters|Defaults|Example URL

|`PageRequest`
|`page`, `size`, `requestTotal`
|`page=1`, `size=10`, `requestTotal=true`
|`?page=2&size=25`

|`Sort<Cat>`
|`sort`
|`null`
|`?sort=name` (ascending) or `?sort=-name` (descending)

|`Order<Cat>`
|`sort` (repeating)
|empty `Order.by()`
|`?sort=name&sort=-salary`

|`Limit`
|`limit`, `startAt`, `endAt`
|`null` (no limit), `startAt=1`
|`?limit=10` or `?limit=10&startAt=51` or `?startAt=51&endAt=60`

|`Direction`
|`direction`
|`null`
|`?direction=ASC` or `?direction=desc`

|===

For `Sort` and `Order`, prefix the property name with `-` to indicate descending order.

When binding sort parameters from REST endpoints to `BlockingDataQuery`, prefer `Order<Cat>` over `Sort<Cat>`. A
missing `sort` query parameter yields `null` for `Sort<Cat>` but an empty `Order.by()` for `Order<Cat>`. If the
`Sort<Cat>` parameter is `null`, `.sort(null)` is a no-op. `Order` is preferred when multiple columns can be requested.

NOTE: Cursor-based pagination (`PageRequest.Mode.CURSOR_NEXT` and `CURSOR_PREVIOUS`) is not currently supported by this
REST integration. Only offset-based pagination is available through query parameters.

=== Page serialization

When a REST endpoint returns a `jakarta.data.page.Page`, it is serialized as a JSON object with pagination metadata,
rather than as a plain array:

[source,json]
----
{
  "content": [ ... ],
  "hasNext": true,
  "hasPrevious": false,
  "totalElements": 100,
  "totalPages": 34
}
----

The `totalElements` and `totalPages` fields are included only when the `PageRequest` was created with
`requestTotal=true`.

=== Example endpoint

Here is an example of a REST endpoint that uses `PageRequest` and `Order` to return a paginated, sorted
list of cats. Paging and sorting are configured on the `PanacheQuery` returned by `findAll()`:

[source,java]
----
import jakarta.data.Order;
import jakarta.data.page.PageRequest;
import jakarta.inject.Inject;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;

import java.util.List;

@Path("cats")
public class CatResource {

    @Inject
    Cat.Repo repo;

    @GET
    public List<Cat> list(PageRequest pageRequest, Order<Cat> order) { // <1>
        return repo.findAll().pages().request(pageRequest).sort(order).list();
    }
}
----
<1> `PageRequest` is populated from `page`, `size`, and `requestTotal` query parameters.
`Order` is populated from repeating `sort` query parameters.

A client can then call:

[source]
----
GET /cats?page=1&size=20&sort=name&sort=-birth
----

This produces a `PageRequest.ofPage(1, 20, true)` and `Order.by(Sort.asc("name"), Sort.desc("birth"))`.

== Query languages

There are multiple technologies to express queries in Quarkus Data Hibernate. They are related languages rather than
separate query engines: each standard defines a different level of functionality or portability.

- The link:https://docs.hibernate.org/orm/{hibernate-orm-version-major-minor}/querylanguage/html_single/[Hibernate Query Language]
  (HQL) is Hibernate's full query language. Use it with the Hibernate-specific `@HQL` annotation when you need
  Hibernate features beyond the standard query languages.
- The link:{jakarta-persistence-spec-url}#a4665[Jakarta Persistence Query Language] (JPQL) is the standard query language
  defined by Jakarta Persistence and is a subset of HQL. A valid JPQL query is also a valid HQL query. This language is
  evolving into the standalone link:https://jakarta.ee/specifications/query/1.0/jakarta-query-1.0-m1[Jakarta Query specification].
- The link:{jakarta-data-spec-url}#_jakarta_data_query_language[Jakarta Data Query Language] (JDQL) is the portable
  subset of JPQL used by Jakarta Data's `@Query` annotation. Prefer it when the repository should remain independent
  of Hibernate-specific query features.
- Panache Query Language adds concise forms for common HQL queries. It is accepted by query methods such as `find()`,
  `list()`, `update()`, and `delete()` on `ManagedRepository` and `RecordRepository`, and is expanded to HQL before
  execution.

=== Panache Query Language

Most HQL select queries have the form `from EntityName [where ...] [order by ...]`, with optional elements at the end.

If a select query does not start with `from`, `select`, or `with`, the following additional forms are supported:

- `order by ...` expands to `from EntityName order by ...`.
- `<singleAttribute>` with a single parameter expands to `from EntityName where <singleAttribute> = ?`.
- `where <query>` expands to `from EntityName where <query>`.
- `<query>` expands to `from EntityName where <query>`.

If an update query does not start with `update`, the following additional forms are supported:

- `from EntityName ...` expands to `update EntityName ...`.
- `set? <singleAttribute>` with a single parameter expands to `update EntityName set <singleAttribute> = ?`.
- `set? <update-query>` expands to `update EntityName set <update-query>`.

If a delete query does not start with `delete`, the following additional forms are supported:

- `from EntityName ...` expands to `delete from EntityName ...`.
- `<singleAttribute>` with a single parameter expands to `delete from EntityName where <singleAttribute> = ?`.
- `<query>` expands to `delete from EntityName where <query>`.

== Repository security

Quarkus Security provides initial support for securing repositories with security annotations. Security annotations can
be placed on methods directly declared by a repository.

[source,java]
----
@PermissionsAllowed("cat:list")
@PermissionsAllowed("cat:read")
@Find
List<Cat> findByName(String name);
----

You can also place a security annotation on the repository interface:

[source,java]
----
@RolesAllowed("admin")
public interface SecuredCatRepo extends ManagedRepository<Cat> {
    @Find
    List<Cat> findByName(String name);
}
----

Only methods directly declared on an annotated repository interface are secured. Methods inherited from
`ManagedRepository`, such as `findById`, `persist`, or `deleteAll`, are not secured because type-level annotations only
affect the type they annotate.

Generic interface methods using type variables or wildcards cannot currently be secured reliably with standard security
annotations. Apply the security annotation to the calling method, such as a REST endpoint, or redeclare the repository
method with a concrete type.

See the xref:security-authorize-web-endpoints-reference.adoc[authorization of web endpoints reference] for information
about Quarkus Security annotations.
