= README: Quarkus documentation
include::_attributes.adoc[]

Quarkus documentation uses asciidoc syntax.

A gradual refactoring effort is underway to reshape Quarkus documentation to make it easier to both read and write (see xref:doc-concepts.adoc[Quarkus documentation concepts] for more on this transition).

For more information on contributing to Quarkus docs, see:

- xref:doc-contribute-docs-howto.adoc[How to contribute documentation]
- xref:doc-concepts.adoc[Quarkus documentation concepts]
- xref:doc-reference.adoc[Quarkus documentation reference]

== Glossary

This is a collection of preferred term in the documentation and website.
Please stay within these terms for consistency.

* Live coding:: for our `quarkus:dev` capability
* GraalVM native image:: preferred term for the VM creating native executable. No space.
* Substrate VM:: non-preferred. Exclude.
* Native Executable:: the executable that is compiled to native 1s and 0s
* Docker image:: for the actual `Dockerfile` definition and when the tool chain is involved
* Container:: when we discuss Quarkus running in... containers
* Supersonic Subatomic Java:: our tagline
* Kubernetes Native Java:: our preferred tagline to say that we rock for containers
* Developer Joy:: for everything going from live reload to the opinionated layer to a single config file
* Unify Imperative and Reactive:: imperative and reactive. 'Nuff said.
* Best of breed frameworks and standards:: when we explain our stack
