= README: Quarkus documentation
include::_attributes.adoc[]

Quarkus documentation uses link:https://asciidoc.org/[AsciiDoc] markup.

A gradual refactoring effort is underway to reshape Quarkus documentation to make it easier to both read and write. For more information about this transition, see xref:doc-concept.adoc[Quarkus documentation content types].

For more information on contributing to Quarkus docs, see:

- xref:doc-contribute-docs-howto.adoc[Contribute to Quarkus documentation]
- xref:doc-concept.adoc[Quarkus documentation content types]
- xref:doc-reference.adoc[Quarkus style and content guidelines]
- xref:doc-create-tutorial.adoc[Creating a tutorial]

== Glossary

This is a collection of preferred terms in the documentation and website.
Please stay within these terms for consistency.

* Live coding:: for our `quarkus:dev` capability
* GraalVM native image:: preferred term for the VM creating native executable. No space.
* Substrate VM:: non-preferred. Exclude.
* Native Executable:: the executable that is compiled to native 1s and 0s
* Docker image:: for the actual `Dockerfile` definition and when the tool chain is involved
* Container:: when we discuss Quarkus running in... containers
* Supersonic Subatomic Java:: our tagline
* Kubernetes Native Java:: our preferred tagline to say that we rock for containers
* Developer Joy:: for everything going from live reload to the opinionated layer to a single config file
* Unify Imperative and Reactive:: imperative and reactive. 'Nuff said.
* Best of breed frameworks and standards:: when we explain our stack
