////
This guide is maintained in the main Quarkus repository
and pull requests should be submitted there:
https://github.com/quarkusio/quarkus/tree/main/docs/src/main/asciidoc
////
= Using Keycloak Admin Client

include::./attributes.adoc[]

The Quarkus Keycloak Admin Client and its reactive twin facilitate running the Keycloak Admin Client in a native mode.
This guide demonstrates how you can leverage the xref:cdi-reference.adoc[Quarkus ArC] and inject the admin client to your Quarkus application.
To learn more about the Keycloak Admin Client, please refer to its https://www.keycloak.org/docs/latest/server_development/#example-using-java[reference guide].

== Prerequisites

:prerequisites-docker:
include::{includes}/prerequisites.adoc[]
* https://www.keycloak.org/docs/latest/server_installation/index.html[Keycloak]

== Creating the Project

First, we need a new project.
Create a new project with the following command:

:create-app-artifact-id: security-keycloak-admin-client
:create-app-extensions: keycloak-admin-client-reactive,resteasy-reactive-jackson
include::{includes}/devtools/create-app.adoc[]

This command generates a project which imports the `keycloak-admin-client-reactive` and `resteasy-reactive-jackson` extensions.

If you already have your Quarkus project configured, you can add the `keycloak-admin-client-reactive` and `resteasy-reactive-jackson` extensions
to your project by running the following command in your project base directory:

:add-extension-extensions: keycloak-admin-client-reactive,resteasy-reactive-jackson
include::{includes}/devtools/extension-add.adoc[]

This will add the following to your build file:

[source,xml,role="primary asciidoc-tabs-target-sync-cli asciidoc-tabs-target-sync-maven"]
.pom.xml
----
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-keycloak-admin-client-reactive</artifactId>
</dependency>
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-resteasy-reactive-jackson</artifactId>
</dependency>
----

[source,gradle,role="secondary asciidoc-tabs-target-sync-gradle"]
.build.gradle
----
implementation("io.quarkus:quarkus-keycloak-admin-client-reactive")
implementation("io.quarkus:quarkus-resteasy-reactive-jackson")
----

We also are going to need a simple resource with a `Keycloak` injected as request scoped CDI bean.

[source,java]
----
package org.acme.keycloak.admin.client;

import org.keycloak.admin.client.Keycloak;
import org.keycloak.representations.idm.RoleRepresentation;

import javax.inject.Inject;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import java.util.List;

@Path("/api/admin")
public class RolesResource {

        @Inject
        Keycloak keycloak;

        @GET
        @Path("/roles")
        public List<RoleRepresentation> getRoles() {
            return keycloak.realm("quarkus").roles().list();
        }

}
----

Now, you can produce the `Keycloak` bean yourself, or you can instruct Quarkus to produce `Keycloak` bean.

NOTE: If you produce the bean yourself, please remember that `org.keycloak.admin.client.Keycloak` implements `AutoCloseable` and it's important to avoid resource exhaustion and related exceptions. If you configure your beans as explained below, Quarkus will do it for you.

The Keycloak admin client needs an access token as its Admin REST API requires authorization.
If you exchange user's credentials for the access token, here is an example configuration for the `password` grant type:

[source,properties]
----
quarkus.keycloak.admin-client=true
quarkus.keycloak.admin-client.server-url=http://localhost:8081
quarkus.keycloak.admin-client.realm=quarkus
quarkus.keycloak.admin-client.client-id=quarkus-client
quarkus.keycloak.admin-client.username=alice
quarkus.keycloak.admin-client.password=alice
quarkus.keycloak.admin-client.grant-type=PASSWORD <1>
----
<1> Use `password` grant type.

An example using the `client-credentials` grant type needs only a minor adjustments:

[source,properties]
----
quarkus.keycloak.admin-client=true
quarkus.keycloak.admin-client.server-url=http://localhost:8081
quarkus.keycloak.admin-client.realm=quarkus
quarkus.keycloak.admin-client.client-id=quarkus-client
quarkus.keycloak.admin-client.client-secret=secret
quarkus.keycloak.admin-client.username= # remove default username
quarkus.keycloak.admin-client.password= # remove default password
quarkus.keycloak.admin-client.grant-type=CLIENT_CREDENTIALS <1>
----
<1> Use `client_credentials` grant type.

NOTE: Note that the xref:security-openid-connect-client.adoc[OidcClient] can also be used to acquire tokens.

[[arc-configuration-reference]]
== Quarkus Keycloak Admin Client Configuration Reference

include::{generated-dir}/config/quarkus-keycloak-admin-client.adoc[leveloffset=+1, opts=optional]

== References

* https://www.keycloak.org/documentation.html[Keycloak Documentation]
* xref:security-keycloak-authorization.adoc[Keycloak Authorization extension]
* xref:security-openid-connect-web-authentication.adoc[Using OpenID Connect to Protect Web Application]
* xref:security.adoc[Quarkus Security]
* xref:security-openid-connect.adoc[Using OpenID Connect to Protect Service Applications]
* xref:security-openid-connect-client.adoc[OpenID Connect Client and Token Propagation Quickstart]