[id="security-basic-authentication-concept"]
= Basic authentication
include::_attributes.adoc[]
:diataxis-type: concept
:categories: security,web

HTTP Basic authentication is one of the least resource-demanding techniques that enforce access controls to web resources. 
You can secure your Quarkus application endpoints with HTTP Basic authentication. Quarkus provides a built-in authentication mechanism for Basic authentication.

Basic authentication uses fields in the HTTP header and does not require HTTP cookies, session identifiers, or login pages.

== Authorization header

An HTTP user agent, for example, a web browser, uses an `Authorization` header to provide a username and password in each HTTP request.
The header is specified as `Authorization: Basic <credentials>`, where credentials are the Base64 encoding of the user ID and password joined by a colon, as shown in the following example.

====
.Example

If the user name is `Alice` and the password is `secret`, the HTTP authorization header would be `Authorization: Basic QWxjZTpzZWNyZXQ=`, where `QWxjZTpzZWNyZXQ=` is a Base64 encoded representation of the `Alice:secret` string.
====

The Basic authentication mechanism does not provide confidentiality protection for the transmitted credentials.
The credentials are merely encoded with Base64 when in transit and not encrypted or hashed in any way.
Therefore, Basic authentication is used with HTTPS to provide confidentiality.

Basic authentication is a well-specified, simple challenge and response scheme that all web browsers and most web servers understand.

== Limitations with using Basic authentication

The following table outlines some limitations of using HTTP Basic authentication to secure your Quarkus applications:


.Limitations of HTTP Basic authentication
[width=80%]
[cols="35%,65%"]
|===
|Limitation |Description

|Credentials are sent as plain text
|Use HTTPS with Basic authentication to avoid exposing the credentials.
The risk of exposing credentials as plain text increases if a load balancer terminates HTTPS, as the request is forwarded to Quarkus over HTTP.
Also, in multi-hop deployments, the credentials can be exposed if HTTPS is used between the client and the first Quarkus endpoint only, and the credentials are propagated to the next Quarkus endpoint over HTTP.

|Credentials are sent with each request
|In Basic authentication, a username and password must be sent with each request, which increases the risk of credentials being exposed.

|Application complexity increases
|The Quarkus application must validate that usernames, passwords, and roles are managed securely.
This process, however, can introduce significant complexity to the application.
Depending on the use case, other authentication mechanisms that delegate username, password, and role management to specialized services might be a better choice.

|===

== Implementing Basic authentication in Quarkus

For more information about how you can secure your Quarkus applications by using Basic authentication, see the following resources:

* xref:security-basic-authentication-howto.adoc[Enable Basic authentication]
* xref:security-basic-authentication-tutorial.adoc[Secure a Quarkus application with Basic authentication and Jakarta Persistence]

== Role-based access control

{project-name} also includes built-in security to allow for role-based access control (RBAC) based on the common security annotations @RolesAllowed, @DenyAll, @PermitAll on REST endpoints and CDI beans. 
For more information, see xref:security-authorize-web-endpoints-reference.adoc[Authorization of web endpoints].

== References

* xref:security-overview-concept.adoc[Quarkus Security overview]
* xref:security-architecture-concept.adoc[Quarkus Security architecture] 
* xref:security-authentication-mechanisms-concept.adoc#other-supported-authentication-mechanisms[Authentication mechanisms in Quarkus]
* xref:security-identity-providers-concept.adoc[Identity providers]
* xref:security-authorize-web-endpoints-reference.adoc[Authorization of web endpoints]
