////
This document is maintained in the main Quarkus repository
and pull requests should be submitted there:
https://github.com/quarkusio/quarkus/tree/main/docs/src/main/asciidoc
////
[id="security-basic-authentication-howto"]
= Enable Basic authentication
include::_attributes.adoc[]
:diataxis-type: howto
:categories: security
:topics: security,authentication,basic-authentication,http
:extensions: io.quarkus:quarkus-vertx-http,io.quarkus:quarkus-security-jpa,io.quarkus:quarkus-security-jpa-reactive,io.quarkus:quarkus-elytron-security-properties-file,io.quarkus:quarkus-elytron-security-jdbc,io.quarkus:quarkus-elytron-security-ldap

Enable Basic authentication to require a username and password before users can access your Quarkus application. Configure an identity provider to store and verify credentials, then activate the Basic authentication mechanism built into Quarkus HTTP.

For more about the mechanism, see xref:security-basic-authentication.adoc[Basic authentication].
For a production application, store credentials in a database through an identity provider.
Configuring credentials in the `application.properties` file is not appropriate for production credentials; this approach is suitable for testing only. This how-to includes an optional embedded-realm example from the `elytron-security-properties-file` extension to demonstrate that approach.

== Prerequisites

* You have installed at least one extension that provides an `IdentityProvider` to verify username and password credentials and map them to a `SecurityIdentity`.
For example:

ifndef::no-quarkus-security-jpa-reactive[]
** xref:security-jpa.adoc[Quarkus Security Jakarta Persistence extensions (`quarkus-security-jpa` or `quarkus-security-jpa-reactive`)]
endif::no-quarkus-security-jpa-reactive[]
ifdef::no-quarkus-security-jpa-reactive[]
** xref:security-jpa.adoc[Quarkus Security Jakarta Persistence extension (`quarkus-security-jpa`)]
endif::no-quarkus-security-jpa-reactive[]
** xref:security-properties.adoc[Elytron security properties file extension `(quarkus-elytron-security-properties-file)`]
** xref:security-jdbc.adoc[Elytron security JDBC extension `(quarkus-elytron-security-jdbc)`]

== Procedure

. In the `application.properties` file, set the `quarkus.http.auth.basic` property to `true`.
+
[source,properties]
----
quarkus.http.auth.basic=true
----

. Configure an identity provider to verify the username and password against your user store.
For a production application, configure one of the identity provider extensions listed in the Prerequisites, for example, by storing users in a database with the Jakarta Persistence extension.
For more information, see the xref:security-identity-providers.adoc[Identity providers] guide.

. *For testing only:* In a non-production environment, you can use the embedded realm provided by the `quarkus-elytron-security-properties-file` extension instead of a production identity provider.
.. To enable authentication for the embedded realm, set the `quarkus.security.users.embedded.enabled` property to `true`.
+
[source,properties]
----
quarkus.security.users.embedded.enabled=true
----

.. You can also configure the required user credentials: user name, password, and roles.
For example:
+
[source,properties]
----
quarkus.http.auth.basic=true
quarkus.security.users.embedded.enabled=true
quarkus.security.users.embedded.plain-text=true
quarkus.security.users.embedded.users.alice=alice
quarkus.security.users.embedded.users.bob=bob
quarkus.security.users.embedded.roles.alice=admin
quarkus.security.users.embedded.roles.bob=user
----
where:

* The user, `alice`, has `alice` as their password and `admin` as their role.
* The user, `bob`, has `bob` as their password and `user` as their role.

== Verification

. Start your application.

. Send a request to a secured endpoint _without_ credentials and confirm that the application returns a `401 Unauthorized` response:
+
[source,shell]
----
$ curl -i -X GET http://localhost:8080/<your_secured_endpoint>

HTTP/1.1 401 Unauthorized
WWW-Authenticate: Basic
----

. Send the same request _with_ a valid username and password and confirm that the application returns a `200 OK` response:
+
[source,shell]
----
$ curl -i -X GET -u <username>:<password> http://localhost:8080/<your_secured_endpoint>

HTTP/1.1 200 OK
----

== Next steps

For a more detailed walk-through that shows you how to configure Basic authentication together with Jakarta Persistence for storing user credentials in a database, see the xref:security-getting-started-tutorial.adoc[Getting started with Security by using Basic authentication and Jakarta Persistence] guide.

== Additional resources

* xref:security-overview.adoc[Quarkus Security overview]
* xref:security-identity-providers.adoc[Identity Providers]
* xref:security-testing.adoc#configuring-user-information[Configuring User Information in application.properties]
* xref:security-basic-authentication.adoc[Basic authentication]
