[id="security-basic-authentication-howto"]
= Enable Basic authentication
include::_attributes.adoc[]
:categories: security

Enable Basic authentication for your Quarkus project and allow users to authenticate with a username and password.
 
== Prerequisites
 
* You have installed at least one extension that provides an `IdentityProvider` based on username and password, such as xref:security-jdbc.adoc[Elytron JDBC].
 
. Enable Basic authentication by setting the value of `quarkus.http.auth.basic` property to `true`.
+
[source,properties]
----
quarkus.http.auth.basic=true
----
 
For a Basic authentication configuration walk-through that uses `JPA`, see the xref:security-basic-authentication-tutorial.adoc[Secure a Quarkus application with Basic authentication] guide.
 
== Additional resources

* xref:security-overview-concept.adoc[Quarkus Security overview]
* xref:security-overview-concept.adoc#identity-providers[Security Identity Providers]
* xref:security-testing.adoc#configuring-user-information[Configuring User Information in application.properties]
