////
This guide is maintained in the main Quarkus repository
and pull requests should be submitted there:
https://github.com/quarkusio/quarkus/tree/master/docs/src/main/asciidoc
////
= Quarkus - Using our Spring compatibility layer

include::./attributes.adoc[]

While you are encouraged to use CDI annotations for injection and JAX-RS annotation for defining REST endpoints,
Quarkus provides a compatibility layer for Spring dependency injection in the form of the `spring-di` extension and for Spring Web in the form of the `spring-web` extension.

This guide explains how your Quarkus application can leverage the well known Dependency Injection annotations included in the Spring Framework and the
equally well known Spring Web annotation to define RESTful services.

== Prerequisites

To complete this guide, you need:

* less than 15 minutes
* an IDE
* JDK 1.8+ installed with `JAVA_HOME` configured appropriately
* Apache Maven 3.5.3+




== Solution

We recommend that you follow the instructions in the next sections and create the application step by step.
However, you can go right to the completed example.

Clone the Git repository: `git clone {quickstarts-clone-url}`, or download an {quickstarts-archive-url}[archive].

The solution is located in the `using-spring` directory.

== Creating the Maven project

First, we need a new project. Create a new project with the following command:

[source,shell,subs=attributes+]
----
mvn io.quarkus:quarkus-maven-plugin:{quarkus-version}:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=using-spring \
    -DclassName="org.acme.spring.GreeterResource" \
    -Dpath="/greeting" \
    -Dextensions="spring-web"
----

This command generates a Maven project with a REST endpoint and imports the `spring-di` extension.


== Add beans using Spring annotations

Let's proceed to create some beans using various Spring annotations.

First we will create a `StringFunction` interface that some of our beans will implement and which will be injected into another bean later on.
Create a `src/main/java/org/acme/spring/di/StringFunction.java` file and set the following content:

[source,java]
----
package org.acme.spring;

import java.util.function.Function;

public interface StringFunction extends Function<String, String> {

}
----

With the interface in place, we will add an `AppConfiguration` class which will use the Spring's Java Config style for defining a bean.
It will be used to create a `StringFunction` bean that will capitalize the text passed as parameter.
Create a `src/main/java/org/acme/spring/di/AppConfiguration.java` file with the following content:

[source,java]
----
package org.acme.spring;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class AppConfiguration {

    @Bean(name = "capitalizeFunction")
    public StringFunction capitalizer() {
        return String::toUpperCase;
    }
}
----

Now we define another bean that will implement `StringFunction` using Spring's stereotype annotation style.
This bean will effectively be a no-op bean that simply returns the input as is.
Create a `src/main/java/org/acme/spring/di/NoOpSingleStringFunction.java` file and set the following content:

[source,java]
----
package org.acme.spring;

import org.springframework.stereotype.Component;

@Component("noopFunction")
public class NoOpSingleStringFunction implements StringFunction {

    @Override
    public String apply(String s) {
        return s;
    }
}
----

Quarkus also provides support for injecting configuration values using Spring's `@Value` annotation.
To see that in action, first edit the `src/main/resources/application.properties` with the following content:

[source,java]
----
# Your configuration properties
greeting.message = hello
----

Next create a new Spring bean in `src/main/java/org/acme/spring/di/MessageProducer.java` with the following content:


[source,java]
----
package org.acme.spring;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

@Service
public class MessageProducer {

    @Value("${greeting.message}")
    String message;

    public String getPrefix() {
        return message;
    }
}
----

The final bean we will create ties together all the previous beans.
Create a `src/main/java/org/acme/spring/di/GreeterBean.java` file and copy the following content:

[source,java]
----
package org.acme.spring;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

@Component
public class GreeterBean {

    private final MessageProducer messageProducer;

    @Autowired
    @Qualifier("noopFunction")
    StringFunction noopStringFunction;

    @Autowired
    @Qualifier("capitalizeFunction")
    StringFunction capitalizerStringFunction;

    @Value("${greeting.suffix:!}")
    String suffix;

    public GreeterBean(MessageProducer messageProducer) {
        this.messageProducer = messageProducer;
    }

    public String greet(String name) {
        final String initialValue = messageProducer.getPrefix() + " " + name + suffix;
        return noopStringFunction.andThen(capitalizerStringFunction).apply(initialValue);
    }
}
----

In the code above, we see that both field injection and constructor injection are being used (note that constructor injection does not need the `@Autowired` annotation since there is a single constructor).
Furthermore, the `@Value` annotation on `suffix` has also a default value defined, which in this case will be used since we have not defined `greeting.suffix` in `application.properties`.


=== Writing the GreetingController

The Quarkus maven plugin automatically generated a `src/main/java/org/acme/spring/di/GreeterResource.java` file.
However since we are going to be using Spring Web annotations to define our REST endpoint, go ahead and delete that file.
Then create a new `src/main/java/org/acme/spring/di/GreeterResource.java` file and add the following content:

[source,java]
----
package org.acme.spring;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/greeting")
public class GreeterController {

    private final GreeterBean greeterBean;

    public GreeterController(GreeterBean greeterBean) {
        this.greeterBean = greeterBean;
    }

    @GetMapping
    public Greeting hello() {
        return new Greeting(greeterBean.greet("world"));
    }
}
----

== Update the test

We also need to update the functional test to reflect the changes made to the endpoint.
First rename the `src/test/java/org/acme/spring/di/GreetingResourceTest.java` file to `src/test/java/org/acme/spring/di/GreetingControllerTest.java`
and change its content to:


[source, java]
----
package org.acme.spring;

import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.api.Test;

import static io.restassured.RestAssured.given;
import static org.hamcrest.CoreMatchers.is;

@QuarkusTest
public class GreetingControllerTest {

    @Test
    public void testGreeting() {
        given()
            .when().get("/greeting")
            .then()
                .statusCode(200)
                .body("message", is("HELLO WORLD!"));
    }

}
----

== Package and run the application

Run the application with: `./mvnw compile quarkus:dev`.
Open your browser to http://localhost:8080/greeting.

The result should be: `{"message": "HELLO WORLD!"}`.

== Run the application as a native

You can of course create a native image using instructions similar to link:building-native-image-guide.html[this] guide.

== Supported Spring Web functionality

Quarkus currently supports a subset of the functionality that Spring Web provides. More specifically Quarkus supports the REST related features of Spring Web
(in a high level, think of `@RestController` instead of `@Controller`).

=== Annotations

The table below summarizes the supported annotations:

.Supported Spring Web annotation
|===
|Name|Comments

|@RestController
|

|@RequestMapping
|
|@GetMapping
|
|@PostMapping
|
|@PutMapping
|
|@DeleteMapping
|
|@PatchMapping
|
|@RequestParam
|
|@RequestHeader
|
|@MatrixVariable
|
|@PathVariable
|
|@CookieValue
|
|@RequestBody
|
|@ResponseStatus
|
|@ExceptionHandler
|Can only be used in a @RestControllerAdvice class, not on a per-controller basis
|@RestControllerAdvice
|Only the @ExceptionHandler capability is supported
|===

=== Controller method return types

The following method return types are supported:

* Primitive types
* String (which will be used as a literal, no Spring MVC view support is provided)
* POJO classes which will be serialized via JSON
* `org.springframework.http.ResponseEntity`

=== Controller method return types

In addition to the method parameters that can be annotated with the appropriate Spring Web annotation from the previous table,
`javax.servlet.http.HttpServletRequest` and `javax.servlet.http.HttpServletResponse` are also supported.


== Important Technical Note

Please note that the Spring support in Quarkus does not start a Spring Application Context nor are any Spring infrastructure classes run.
Spring classes and annotations are only used for reading metadata and / or are used as user code method return types or parameter types.
What that means for end users, is that adding arbitrary Spring to the classpath will not be used at all. Moreover Spring infrastructure
things like `org.springframework.beans.factory.config.BeanPostProcessor` will not be run.

