////
This guide is maintained in the main Quarkus repository
and pull requests should be submitted there:
https://github.com/quarkusio/quarkus/tree/main/docs/src/main/asciidoc
////
= Using our Tooling

include::./attributes.adoc[]

Quarkus comes with a toolchain enabling developers from live reload all the way down to deploying a Kubernetes application. In addition there are plugins and extensions to all major IDEs.

In this guide, we will explore:

* how to use xref:maven-tooling.adoc[Maven] as a build tool
* how to use xref:gradle-tooling.adoc[Gradle] as a build tool
* how to use the xref:cli-tooling.adoc[CLI] for your toolchain
* how to create and scaffold a new project
* how to deal with extensions
* how to enable live reload
* how to develop your application in your IDE
* how to compile your application natively
* how to setup Quarkus tools in xref:ide-tooling.adoc[Visual Studio Code, Eclipse IDE, Eclipse Che and IntelliJ] 

[[build-tool]]
== Choosing your build tool

Quarkus comes with a toolchain to help you at all development stages.
You can use Maven or Gradle as build tool.
And we offer a CLI that is convenient to use (coming soon).

* xref:maven-tooling.adoc[Maven]
* xref:gradle-tooling.adoc[Gradle]
* xref:cli-tooling.adoc[CLI]
* xref:ide-tooling.adoc[IDE]
