////
This document is maintained in the main Quarkus repository, and pull requests should be submitted there:
https://github.com/quarkusio/quarkus/tree/main/docs/src/main/asciidoc
////
[id="update-quarkus"]
= Update projects to the latest Quarkus version
include::_attributes.adoc[]
:diataxis-type: howto
:categories: core
:extension-status: "experimental"
:summary: Learn how to upgrade your projects to the latest version of {project-name}
:topics: tooling

You can update or upgrade your {project-name} projects to the latest version of {project-name} by using an update command.

The update command primarily employs OpenRewrite recipes to automate updates for most project dependencies, source code, and documentation.
Although these recipes update many migration items, they do not cover all the items detailed in the {quarkus-migration-guide}.

Post-update, if expected updates are missing, consider the following reasons:

- The recipe might not include a specific item in your project.
- Your project might use an extension that is incompatible with the latest {project-name} version.
- If you have Gradle Kotlin build files (`.kts`), Quarkus Update https://github.com/quarkusio/quarkus/issues/33046[will fail] until OpenRewrite supports these.

[IMPORTANT]
====
For projects that use Hibernate ORM or Hibernate Reactive, review the link:https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0:-Hibernate-ORM-5-to-6-migration[Hibernate ORM 5 to 6 migration] quick reference.
The following update command covers only a subset of this guide.
====

== Prerequisites

:prerequisites-time: 30 minutes
include::{includes}/prerequisites.adoc[]
* A project based on {project-name} version 2.13 or later.

== Procedure

. Create a working branch for your project by using your version control system.

. To use the Quarkus CLI in the next step, xref:cli-tooling.adoc#installing-the-cli[install the latest version of the Quarkus CLI].
Confirm the version number using `quarkus -v`.

. Go to the project directory and update the project to the latest stream:
+
[role="primary asciidoc-tabs-sync-cli"]
.Using Quarkus CLI
+
****
[source, bash, subs=attributes+]
----
quarkus update
----
Optional: To specify a particular stream, use the `--stream` option; for example: `--stream=3.2`
ifndef::devtools-no-maven[]
ifdef::devtools-wrapped[+]
****
+
[role="secondary asciidoc-tabs-sync-maven"]
.Using Maven
+
****
[source, bash, subs=attributes+]
----
./mvnw {quarkus-platform-groupid}:quarkus-maven-plugin:{quarkus-version}:update -N
----
Optional: To specify a particular stream, use the `-Dstream` option; for example: `-Dstream=3.2`
endif::[]
ifndef::devtools-no-gradle[]
ifdef::devtools-wrapped[+]
****

. Analyze the update command output for potential instructions and perform the suggested tasks if necessary.

. Use a diff tool to inspect all changes.

. Review the {quarkus-migration-guide} for items that were not updated by the update command.
If your project has such items, implement the additional steps advised in these topics.

. Ensure the project builds without errors, all tests pass, and the application functions as required before deploying to production.
