package io.quarkus.qute.deployment.i18n;

import static io.quarkus.qute.i18n.MessageBundle.DEFAULT_NAME;
import static org.junit.jupiter.api.Assertions.assertEquals;

import jakarta.inject.Inject;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.RegisterExtension;

import io.quarkus.qute.Engine;
import io.quarkus.qute.i18n.Message;
import io.quarkus.qute.i18n.MessageBundle;
import io.quarkus.test.QuarkusExtensionTest;

/**
 * Regression test for <a href="https://github.com/quarkusio/quarkus/issues/55584">#55584</a>.
 * <p>
 * {@code MessageBundleProcessor.implementResolve()} splits message keys into groups of 300 so
 * that generated {@code resolve_*} methods stay within JVM method size limits. With more than
 * 300 keys the generated bytecode must still verify and every key must remain resolvable.
 */
public class MessageBundleLargeKeyMapTest {

    /**
     * One more than the group limit used in {@code MessageBundleProcessor.implementResolve()},
     * so generation of at least two {@code resolve_*} methods is required.
     */
    private static final int MESSAGE_COUNT = 302;

    @RegisterExtension
    static final QuarkusExtensionTest config = new QuarkusExtensionTest()
            .withApplicationRoot(jar -> jar.addClasses(LargeMessages.class));

    @Inject
    LargeMessages messages;

    @Inject
    Engine engine;

    @Test
    public void testLargeMessageBundle() {
        // Typed API is generated separately from resolve groups; smoke-check the range ends
        assertEquals("m0", messages.m0());
        assertEquals("m301", messages.m301());

        // Dynamic lookup exercises the generated resolve_* methods (and cross-group delegation)
        for (int i = 0; i < MESSAGE_COUNT; i++) {
            String key = "m" + i;
            assertEquals(key, engine.parse("{msg:message('" + key + "')}").render(),
                    "dynamic resolve failed for key " + key);
        }
    }

    @MessageBundle(DEFAULT_NAME)
    public interface LargeMessages {

        @Message("m0")
        String m0();

        @Message("m1")
        String m1();

        @Message("m2")
        String m2();

        @Message("m3")
        String m3();

        @Message("m4")
        String m4();

        @Message("m5")
        String m5();

        @Message("m6")
        String m6();

        @Message("m7")
        String m7();

        @Message("m8")
        String m8();

        @Message("m9")
        String m9();

        @Message("m10")
        String m10();

        @Message("m11")
        String m11();

        @Message("m12")
        String m12();

        @Message("m13")
        String m13();

        @Message("m14")
        String m14();

        @Message("m15")
        String m15();

        @Message("m16")
        String m16();

        @Message("m17")
        String m17();

        @Message("m18")
        String m18();

        @Message("m19")
        String m19();

        @Message("m20")
        String m20();

        @Message("m21")
        String m21();

        @Message("m22")
        String m22();

        @Message("m23")
        String m23();

        @Message("m24")
        String m24();

        @Message("m25")
        String m25();

        @Message("m26")
        String m26();

        @Message("m27")
        String m27();

        @Message("m28")
        String m28();

        @Message("m29")
        String m29();

        @Message("m30")
        String m30();

        @Message("m31")
        String m31();

        @Message("m32")
        String m32();

        @Message("m33")
        String m33();

        @Message("m34")
        String m34();

        @Message("m35")
        String m35();

        @Message("m36")
        String m36();

        @Message("m37")
        String m37();

        @Message("m38")
        String m38();

        @Message("m39")
        String m39();

        @Message("m40")
        String m40();

        @Message("m41")
        String m41();

        @Message("m42")
        String m42();

        @Message("m43")
        String m43();

        @Message("m44")
        String m44();

        @Message("m45")
        String m45();

        @Message("m46")
        String m46();

        @Message("m47")
        String m47();

        @Message("m48")
        String m48();

        @Message("m49")
        String m49();

        @Message("m50")
        String m50();

        @Message("m51")
        String m51();

        @Message("m52")
        String m52();

        @Message("m53")
        String m53();

        @Message("m54")
        String m54();

        @Message("m55")
        String m55();

        @Message("m56")
        String m56();

        @Message("m57")
        String m57();

        @Message("m58")
        String m58();

        @Message("m59")
        String m59();

        @Message("m60")
        String m60();

        @Message("m61")
        String m61();

        @Message("m62")
        String m62();

        @Message("m63")
        String m63();

        @Message("m64")
        String m64();

        @Message("m65")
        String m65();

        @Message("m66")
        String m66();

        @Message("m67")
        String m67();

        @Message("m68")
        String m68();

        @Message("m69")
        String m69();

        @Message("m70")
        String m70();

        @Message("m71")
        String m71();

        @Message("m72")
        String m72();

        @Message("m73")
        String m73();

        @Message("m74")
        String m74();

        @Message("m75")
        String m75();

        @Message("m76")
        String m76();

        @Message("m77")
        String m77();

        @Message("m78")
        String m78();

        @Message("m79")
        String m79();

        @Message("m80")
        String m80();

        @Message("m81")
        String m81();

        @Message("m82")
        String m82();

        @Message("m83")
        String m83();

        @Message("m84")
        String m84();

        @Message("m85")
        String m85();

        @Message("m86")
        String m86();

        @Message("m87")
        String m87();

        @Message("m88")
        String m88();

        @Message("m89")
        String m89();

        @Message("m90")
        String m90();

        @Message("m91")
        String m91();

        @Message("m92")
        String m92();

        @Message("m93")
        String m93();

        @Message("m94")
        String m94();

        @Message("m95")
        String m95();

        @Message("m96")
        String m96();

        @Message("m97")
        String m97();

        @Message("m98")
        String m98();

        @Message("m99")
        String m99();

        @Message("m100")
        String m100();

        @Message("m101")
        String m101();

        @Message("m102")
        String m102();

        @Message("m103")
        String m103();

        @Message("m104")
        String m104();

        @Message("m105")
        String m105();

        @Message("m106")
        String m106();

        @Message("m107")
        String m107();

        @Message("m108")
        String m108();

        @Message("m109")
        String m109();

        @Message("m110")
        String m110();

        @Message("m111")
        String m111();

        @Message("m112")
        String m112();

        @Message("m113")
        String m113();

        @Message("m114")
        String m114();

        @Message("m115")
        String m115();

        @Message("m116")
        String m116();

        @Message("m117")
        String m117();

        @Message("m118")
        String m118();

        @Message("m119")
        String m119();

        @Message("m120")
        String m120();

        @Message("m121")
        String m121();

        @Message("m122")
        String m122();

        @Message("m123")
        String m123();

        @Message("m124")
        String m124();

        @Message("m125")
        String m125();

        @Message("m126")
        String m126();

        @Message("m127")
        String m127();

        @Message("m128")
        String m128();

        @Message("m129")
        String m129();

        @Message("m130")
        String m130();

        @Message("m131")
        String m131();

        @Message("m132")
        String m132();

        @Message("m133")
        String m133();

        @Message("m134")
        String m134();

        @Message("m135")
        String m135();

        @Message("m136")
        String m136();

        @Message("m137")
        String m137();

        @Message("m138")
        String m138();

        @Message("m139")
        String m139();

        @Message("m140")
        String m140();

        @Message("m141")
        String m141();

        @Message("m142")
        String m142();

        @Message("m143")
        String m143();

        @Message("m144")
        String m144();

        @Message("m145")
        String m145();

        @Message("m146")
        String m146();

        @Message("m147")
        String m147();

        @Message("m148")
        String m148();

        @Message("m149")
        String m149();

        @Message("m150")
        String m150();

        @Message("m151")
        String m151();

        @Message("m152")
        String m152();

        @Message("m153")
        String m153();

        @Message("m154")
        String m154();

        @Message("m155")
        String m155();

        @Message("m156")
        String m156();

        @Message("m157")
        String m157();

        @Message("m158")
        String m158();

        @Message("m159")
        String m159();

        @Message("m160")
        String m160();

        @Message("m161")
        String m161();

        @Message("m162")
        String m162();

        @Message("m163")
        String m163();

        @Message("m164")
        String m164();

        @Message("m165")
        String m165();

        @Message("m166")
        String m166();

        @Message("m167")
        String m167();

        @Message("m168")
        String m168();

        @Message("m169")
        String m169();

        @Message("m170")
        String m170();

        @Message("m171")
        String m171();

        @Message("m172")
        String m172();

        @Message("m173")
        String m173();

        @Message("m174")
        String m174();

        @Message("m175")
        String m175();

        @Message("m176")
        String m176();

        @Message("m177")
        String m177();

        @Message("m178")
        String m178();

        @Message("m179")
        String m179();

        @Message("m180")
        String m180();

        @Message("m181")
        String m181();

        @Message("m182")
        String m182();

        @Message("m183")
        String m183();

        @Message("m184")
        String m184();

        @Message("m185")
        String m185();

        @Message("m186")
        String m186();

        @Message("m187")
        String m187();

        @Message("m188")
        String m188();

        @Message("m189")
        String m189();

        @Message("m190")
        String m190();

        @Message("m191")
        String m191();

        @Message("m192")
        String m192();

        @Message("m193")
        String m193();

        @Message("m194")
        String m194();

        @Message("m195")
        String m195();

        @Message("m196")
        String m196();

        @Message("m197")
        String m197();

        @Message("m198")
        String m198();

        @Message("m199")
        String m199();

        @Message("m200")
        String m200();

        @Message("m201")
        String m201();

        @Message("m202")
        String m202();

        @Message("m203")
        String m203();

        @Message("m204")
        String m204();

        @Message("m205")
        String m205();

        @Message("m206")
        String m206();

        @Message("m207")
        String m207();

        @Message("m208")
        String m208();

        @Message("m209")
        String m209();

        @Message("m210")
        String m210();

        @Message("m211")
        String m211();

        @Message("m212")
        String m212();

        @Message("m213")
        String m213();

        @Message("m214")
        String m214();

        @Message("m215")
        String m215();

        @Message("m216")
        String m216();

        @Message("m217")
        String m217();

        @Message("m218")
        String m218();

        @Message("m219")
        String m219();

        @Message("m220")
        String m220();

        @Message("m221")
        String m221();

        @Message("m222")
        String m222();

        @Message("m223")
        String m223();

        @Message("m224")
        String m224();

        @Message("m225")
        String m225();

        @Message("m226")
        String m226();

        @Message("m227")
        String m227();

        @Message("m228")
        String m228();

        @Message("m229")
        String m229();

        @Message("m230")
        String m230();

        @Message("m231")
        String m231();

        @Message("m232")
        String m232();

        @Message("m233")
        String m233();

        @Message("m234")
        String m234();

        @Message("m235")
        String m235();

        @Message("m236")
        String m236();

        @Message("m237")
        String m237();

        @Message("m238")
        String m238();

        @Message("m239")
        String m239();

        @Message("m240")
        String m240();

        @Message("m241")
        String m241();

        @Message("m242")
        String m242();

        @Message("m243")
        String m243();

        @Message("m244")
        String m244();

        @Message("m245")
        String m245();

        @Message("m246")
        String m246();

        @Message("m247")
        String m247();

        @Message("m248")
        String m248();

        @Message("m249")
        String m249();

        @Message("m250")
        String m250();

        @Message("m251")
        String m251();

        @Message("m252")
        String m252();

        @Message("m253")
        String m253();

        @Message("m254")
        String m254();

        @Message("m255")
        String m255();

        @Message("m256")
        String m256();

        @Message("m257")
        String m257();

        @Message("m258")
        String m258();

        @Message("m259")
        String m259();

        @Message("m260")
        String m260();

        @Message("m261")
        String m261();

        @Message("m262")
        String m262();

        @Message("m263")
        String m263();

        @Message("m264")
        String m264();

        @Message("m265")
        String m265();

        @Message("m266")
        String m266();

        @Message("m267")
        String m267();

        @Message("m268")
        String m268();

        @Message("m269")
        String m269();

        @Message("m270")
        String m270();

        @Message("m271")
        String m271();

        @Message("m272")
        String m272();

        @Message("m273")
        String m273();

        @Message("m274")
        String m274();

        @Message("m275")
        String m275();

        @Message("m276")
        String m276();

        @Message("m277")
        String m277();

        @Message("m278")
        String m278();

        @Message("m279")
        String m279();

        @Message("m280")
        String m280();

        @Message("m281")
        String m281();

        @Message("m282")
        String m282();

        @Message("m283")
        String m283();

        @Message("m284")
        String m284();

        @Message("m285")
        String m285();

        @Message("m286")
        String m286();

        @Message("m287")
        String m287();

        @Message("m288")
        String m288();

        @Message("m289")
        String m289();

        @Message("m290")
        String m290();

        @Message("m291")
        String m291();

        @Message("m292")
        String m292();

        @Message("m293")
        String m293();

        @Message("m294")
        String m294();

        @Message("m295")
        String m295();

        @Message("m296")
        String m296();

        @Message("m297")
        String m297();

        @Message("m298")
        String m298();

        @Message("m299")
        String m299();

        @Message("m300")
        String m300();

        @Message("m301")
        String m301();
    }
}
