package io.quarkus.runtime;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.MethodType;

public final class JVMUnsafeWarningsControl {

    /**
     * This is a horrible hack to disable the Unsafe-related warnings that are printed on startup:
     * we know about the problem, we're working on it, and there's no need to print a warning scaring our
     * users with it.
     * <p>
     * Note: this method is called in the bytecode generated by MainClassBuildStep, make sure you adjust
     * this class accordingly if you change the method name here.
     */
    public static void disableUnsafeRelatedWarnings() {
        // No need for this in JVMs earlier than 24
        if (Runtime.version().feature() < 24) {
            return;
        }
        try {
            Class<?> unsafeClass = Class.forName("sun.misc.Unsafe");
            MethodHandles.Lookup lookup = MethodHandles.privateLookupIn(
                    unsafeClass,
                    MethodHandles.lookup());
            MethodHandle trySetMemoryAccessWarned = lookup.findStatic(
                    unsafeClass,
                    "trySetMemoryAccessWarned",
                    MethodType.methodType(boolean.class));
            @SuppressWarnings("unused")
            boolean unused = (boolean) trySetMemoryAccessWarned.invokeExact();
        } catch (Throwable e) {
            //let's ignore it - if we failed with our horrible hack, worst that could happen is that the ugly warning is printed
        }
    }
}
