package io.quarkus.runtime;

import java.util.Map;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Provides a low-level API for registering and accessing runtime values generated by Quarkus or Quarkus
 * extensions. Typically, such values describe a fully configured application, known only at application startup,
 * such as the HTTP port.
 * <p>
 * These values should not be exposed by the Config mechanism directly, as that would require mutating the Config
 * system, which should be immutable, and cause hard-to-debug issues. Instead, RuntimeValues should be preferred for
 * exposing such values.
 */
public class RuntimeValues {
    private static final Map<String, Object> values = new ConcurrentHashMap<>();

    /**
     * Registers a value with a specified key.
     *
     * @param key key with which the specified value is to be associated
     * @param value value to be associated with the specified key
     * @return the value associated with the specified key
     * @throws IllegalArgumentException if the specified key already has an associated value
     */
    @SuppressWarnings("unchecked")
    public static <T> T register(final RuntimeKey<T> key, final T value) {
        Object mapValue = values.putIfAbsent(key.key(), value);
        if (mapValue != null && !mapValue.equals(value)) {
            throw new IllegalArgumentException("Key already registered " + key.key() + " with value " + mapValue);
        }
        return (T) mapValue;
    }

    /**
     * Returns the value to which the specified key is mapped.
     *
     * @param key the key whose associated value is to be returned
     * @return the value to which the specified key is mapped
     * @throws java.lang.IllegalArgumentException if the specified key has no associated value
     */
    @SuppressWarnings("unchecked")
    public static <T> T get(final RuntimeKey<T> key) {
        T t = (T) values.get(key.key());
        if (t == null) {
            throw new IllegalArgumentException("Key " + key.key() + " not found");
        }
        return t;
    }

    /**
     * Returns the value to which the specified key is mapped.
     *
     * @param key the key whose associated value is to be returned
     * @param defaultValue the default mapping of the key
     * @return the value to which the specified key is mapped, or {@code defaultValue} if the key has no value
     */
    @SuppressWarnings("unchecked")
    public static <T> T get(final RuntimeKey<T> key, final T defaultValue) {
        return (T) values.getOrDefault(key.key(), defaultValue);
    }

    static String getValue(final String propertyName) {
        Object value = values.get(propertyName);
        // TODO - We may require to convert this to the expected config string
        return value != null ? value.toString() : null;
    }

    public static final class RuntimeKey<T> {
        private final String key;

        RuntimeKey(String key) {
            this.key = key;
        }

        public String key() {
            return key;
        }

        @Override
        public boolean equals(Object o) {
            if (!(o instanceof RuntimeKey<?> that))
                return false;
            return Objects.equals(key, that.key);
        }

        @Override
        public int hashCode() {
            return Objects.hashCode(key);
        }

        public static RuntimeKey<String> key(final String key) {
            return new RuntimeKey<>(key);
        }

        public static RuntimeKey<Integer> intKey(final String key) {
            return new RuntimeKey<>(key);
        }
    }
}
