package org.jboss.shamrock.startup;

/**
 * A task that is run on startup. Generally this will be provided by generated bytecode
 */
public interface StartupTast {

    void deploy(StartupContext context);

}
