quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=hibernate_orm_test
quarkus.datasource.password=hibernate_orm_test
quarkus.datasource.reactive.url=${postgres.reactive.url}

quarkus.hibernate-orm.database.generation=drop-and-create

quarkus.log.category."org.hibernate.reactive.context".level=TRACE

quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=false
quarkus.hibernate-orm.log.highlight-sql=true
