quarkus.application.name=observation-reactive-integration-test
quarkus.rest-client.client.url=${test.url}

# Speed up tests
quarkus.otel.bsp.schedule.delay=100
quarkus.otel.bsp.export.timeout=5s
quarkus.otel.metric.export.interval=100ms
