package io.quarkus.gradle.tasks;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Map;
import java.util.Properties;

import javax.inject.Inject;

import org.gradle.api.tasks.TaskAction;
import org.gradle.util.GradleVersion;
import org.gradle.workers.WorkQueue;

import io.quarkus.bootstrap.model.ApplicationModel;
import io.quarkus.gradle.tasks.worker.BuildAotEnhancedImageWorker;

/**
 * Takes the AOT file generated by the ITs and builds a container image that includes it.
 */
public abstract class BuildAotEnhancedImage extends QuarkusBuildTask {

    private static final String QUARKUS_CONTAINER_IT_PROPERTIES = "quarkus-container-it.properties";

    @Inject
    public BuildAotEnhancedImage() {
        super("Build AOT enhanced container image", false);
    }

    @TaskAction
    public void buildAotEnhancedImage() {
        File buildDirectory = getProject().getLayout().getBuildDirectory().getAsFile().get();
        Path metadataFilePath = buildDirectory.toPath().resolve(QUARKUS_CONTAINER_IT_PROPERTIES);

        if (!Files.exists(metadataFilePath)) {
            getLogger().debug("Skipping AOT enhanced image build: {} not found", metadataFilePath);
            return;
        }

        Properties properties = new Properties();
        try (FileInputStream fis = new FileInputStream(metadataFilePath.toFile())) {
            properties.load(fis);
        } catch (IOException e) {
            getLogger().warn("Failed to load {}", metadataFilePath.toAbsolutePath(), e);
            return;
        }

        String aotFileValue = properties.getProperty("aot-file");
        if (aotFileValue == null) {
            getLogger().debug("`aot-file` property not set in `{}`", QUARKUS_CONTAINER_IT_PROPERTIES);
            return;
        }

        Path aotFilePath = Path.of(aotFileValue);
        if (!Files.exists(aotFilePath)) {
            getLogger().warn("AOT file '{}' not found", aotFilePath);
            return;
        }

        String originalContainerImage = properties.getProperty("original-container-image");
        String containerWorkingDirectory = properties.getProperty("container-working-directory");

        getLogger().debug("Found AOT file '{}'; proceeding to build AOT enhanced container image", aotFilePath);

        ApplicationModel appModel = resolveAppModelForBuild();
        Map<String, String> quarkusProperties = extension().buildEffectiveConfiguration(appModel).getValues();

        WorkQueue workQueue = workQueue(quarkusProperties, getExtensionView().getBuildForkOptions().get());

        workQueue.submit(BuildAotEnhancedImageWorker.class, params -> {
            params.getBuildSystemProperties().putAll(buildSystemProperties(appModel.getAppArtifact(), quarkusProperties));
            params.getBaseName().set(getExtensionView().getFinalName());
            params.getTargetDirectory().set(buildDirectory);
            params.getAppModel().set(appModel);
            params.getGradleVersion().set(GradleVersion.current().getVersion());
            params.getOriginalContainerImage().set(originalContainerImage);
            params.getContainerWorkingDirectory().set(containerWorkingDirectory);
            params.getAotFile().set(aotFilePath.toFile());
        });

        workQueue.await();
    }
}
