package io.quarkus.docs.generation;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;
import com.fasterxml.jackson.dataformat.yaml.YAMLGenerator;

// Generated by Claude Code
public class NavigationYamlTest {

    @TempDir
    Path tempDir;

    @BeforeEach
    void setUp() throws Exception {
        // Initialize the static messages field so DocMetadata construction works.
        // The Messages class is private, so reflection is needed.
        Field messagesField = YamlMetadataGenerator.class.getDeclaredField("messages");
        messagesField.setAccessible(true);
        Object messages = messagesField.get(null);

        Method setRoot = messages.getClass().getDeclaredMethod("setRoot", Path.class);
        setRoot.setAccessible(true);
        setRoot.invoke(messages, tempDir);

        Method setLenient = messages.getClass().getDeclaredMethod("setLenient", boolean.class);
        setLenient.setAccessible(true);
        setLenient.invoke(messages, true);
    }

    private NavigationConfig loadConfig(String yaml) throws IOException {
        Path configFile = tempDir.resolve(NavigationConfig.CONFIG_FILENAME);
        Files.writeString(configFile, yaml);
        return NavigationConfig.load(configFile);
    }

    private YamlMetadataGenerator.DocMetadata createDoc(String title, String filename,
            String categories, String subcategories, String navTitle,
            NavigationConfig config) {
        Path path = tempDir.resolve(filename);
        return new YamlMetadataGenerator.DocMetadata(
                title, path, "Summary for " + title,
                categories, null, null, null, navTitle, subcategories,
                "howto", null, filename.replace(".adoc", ""), config);
    }

    @SuppressWarnings("unchecked")
    private Map<String, Object> generateNavigation(NavigationConfig config,
            Map<String, YamlMetadataGenerator.DocMetadata> docs) throws Exception {
        YamlMetadataGenerator generator = new YamlMetadataGenerator();

        Field navConfigField = YamlMetadataGenerator.class.getDeclaredField("navConfig");
        navConfigField.setAccessible(true);
        navConfigField.set(generator, config);

        Field targetDirField = YamlMetadataGenerator.class.getDeclaredField("targetDir");
        targetDirField.setAccessible(true);
        targetDirField.set(generator, tempDir);

        ObjectMapper om = new ObjectMapper(
                new YAMLFactory().enable(YAMLGenerator.Feature.MINIMIZE_QUOTES));

        generator.writeNavigationYaml(om, docs);

        Path outputFile = tempDir.resolve("navigation.yaml");
        assertTrue(Files.exists(outputFile), "navigation.yaml should be generated");

        return new ObjectMapper(new YAMLFactory()).readValue(outputFile.toFile(), Map.class);
    }

    @SuppressWarnings("unchecked")
    private List<Map<String, Object>> getNavigation(Map<String, Object> root) {
        return (List<Map<String, Object>>) root.get("navigation");
    }

    @SuppressWarnings("unchecked")
    private List<Object> getGuides(Map<String, Object> category) {
        return (List<Object>) category.get("guides");
    }

    @Test
    public void flatPlacement() throws Exception {
        NavigationConfig config = loadConfig("""
                categories:
                  - category: web
                    cat-title: Web
                  - category: data
                    cat-title: Data
                """);

        YamlMetadataGenerator.DocMetadata doc = createDoc(
                "REST Guide", "rest.adoc", "web", null, "REST Guide", config);

        Map<String, YamlMetadataGenerator.DocMetadata> docs = new LinkedHashMap<>();
        docs.put(doc.filename, doc);

        Map<String, Object> root = generateNavigation(config, docs);
        List<Map<String, Object>> nav = getNavigation(root);

        // Only web category should appear (data is empty and skipped)
        assertEquals(1, nav.size());
        assertEquals("web", nav.get(0).get("category"));
        assertEquals("Web", nav.get(0).get("cat-title"));

        List<Object> guides = getGuides(nav.get(0));
        assertEquals(1, guides.size());

        @SuppressWarnings("unchecked")
        Map<String, Object> guideEntry = (Map<String, Object>) guides.get(0);
        assertEquals("/guides/rest", guideEntry.get("url"));
        assertEquals("REST Guide", guideEntry.get("title"));
        assertEquals("REST Guide", guideEntry.get("nav-title"));
        assertEquals("howto", guideEntry.get("diataxis-type"));
    }

    @Test
    public void subcategoryPlacement() throws Exception {
        NavigationConfig config = loadConfig("""
                categories:
                  - category: cloud
                    cat-title: Cloud
                    subcategories:
                      - subcategory: openshift
                        subcat-title: Deploy to OpenShift
                """);

        // Guide with category=cloud and subcategory=openshift (openshift is under cloud)
        // Should appear ONLY under cloud/openshift, not flat under cloud
        YamlMetadataGenerator.DocMetadata doc = createDoc(
                "OpenShift Deploy", "deploy-openshift.adoc",
                "cloud", "openshift", "Deploy to OpenShift", config);

        Map<String, YamlMetadataGenerator.DocMetadata> docs = new LinkedHashMap<>();
        docs.put(doc.filename, doc);

        Map<String, Object> root = generateNavigation(config, docs);
        List<Map<String, Object>> nav = getNavigation(root);

        assertEquals(1, nav.size());
        assertEquals("cloud", nav.get(0).get("category"));

        List<Object> guides = getGuides(nav.get(0));
        // Should have one entry: the subcategory group (not a flat guide)
        assertEquals(1, guides.size());

        @SuppressWarnings("unchecked")
        Map<String, Object> subcatGroup = (Map<String, Object>) guides.get(0);
        assertEquals("openshift", subcatGroup.get("subcategory"));
        assertEquals("Deploy to OpenShift", subcatGroup.get("subcat-title"));

        @SuppressWarnings("unchecked")
        List<Map<String, Object>> subcatGuides = (List<Map<String, Object>>) subcatGroup.get("guides");
        assertEquals(1, subcatGuides.size());
        assertEquals("/guides/deploy-openshift", subcatGuides.get(0).get("url"));
    }

    @Test
    public void crossCuttingPlacement() throws Exception {
        NavigationConfig config = loadConfig("""
                categories:
                  - category: cloud
                    cat-title: Cloud
                    subcategories:
                      - subcategory: openshift
                        subcat-title: Deploy to OpenShift
                  - category: native
                    cat-title: Native
                """);

        // Guide with category=native and subcategory=openshift (openshift is under cloud, not native)
        // Should appear: flat under native AND under cloud/openshift
        YamlMetadataGenerator.DocMetadata doc = createDoc(
                "Native OpenShift", "native-openshift.adoc",
                "native", "openshift", "Native on OpenShift", config);

        Map<String, YamlMetadataGenerator.DocMetadata> docs = new LinkedHashMap<>();
        docs.put(doc.filename, doc);

        Map<String, Object> root = generateNavigation(config, docs);
        List<Map<String, Object>> nav = getNavigation(root);

        // Both cloud and native categories should appear
        assertEquals(2, nav.size());

        // Find each category
        Map<String, Object> cloudCat = nav.stream()
                .filter(c -> "cloud".equals(c.get("category")))
                .findFirst().orElse(null);
        Map<String, Object> nativeCat = nav.stream()
                .filter(c -> "native".equals(c.get("category")))
                .findFirst().orElse(null);

        assertNotNull(cloudCat, "Cloud category should be present");
        assertNotNull(nativeCat, "Native category should be present");

        // Under cloud: should be in openshift subcategory group
        List<Object> cloudGuides = getGuides(cloudCat);
        assertEquals(1, cloudGuides.size());
        @SuppressWarnings("unchecked")
        Map<String, Object> subcatGroup = (Map<String, Object>) cloudGuides.get(0);
        assertEquals("openshift", subcatGroup.get("subcategory"));

        // Under native: should be flat
        List<Object> nativeGuides = getGuides(nativeCat);
        assertEquals(1, nativeGuides.size());
        @SuppressWarnings("unchecked")
        Map<String, Object> flatGuide = (Map<String, Object>) nativeGuides.get(0);
        assertEquals("/guides/native-openshift", flatGuide.get("url"));
        // Flat guides have "url" directly, not "subcategory"
        assertFalse(flatGuide.containsKey("subcategory"));
    }

    @Test
    public void featuredMarking() throws Exception {
        NavigationConfig config = loadConfig("""
                categories:
                  - category: getting-started
                    cat-title: Getting Started

                featured:
                  - file: getting-started.adoc
                    featured-summary: Build a hello-world app in 10 minutes
                """);

        YamlMetadataGenerator.DocMetadata doc = createDoc(
                "Getting Started", "getting-started.adoc",
                "getting-started", null, "Get started", config);

        Map<String, YamlMetadataGenerator.DocMetadata> docs = new LinkedHashMap<>();
        docs.put(doc.filename, doc);

        Map<String, Object> root = generateNavigation(config, docs);
        List<Map<String, Object>> nav = getNavigation(root);

        @SuppressWarnings("unchecked")
        Map<String, Object> guide = (Map<String, Object>) getGuides(nav.get(0)).get(0);
        assertEquals(true, guide.get("featured"));
        assertEquals("Build a hello-world app in 10 minutes", guide.get("featured-summary"));
    }

    @Test
    public void guidesAreSortedByNavTitle() throws Exception {
        NavigationConfig config = loadConfig("""
                categories:
                  - category: web
                    cat-title: Web
                """);

        YamlMetadataGenerator.DocMetadata docZ = createDoc(
                "Zzz Guide", "zzz.adoc", "web", null, "Zzz Guide", config);
        YamlMetadataGenerator.DocMetadata docA = createDoc(
                "Aaa Guide", "aaa.adoc", "web", null, "Aaa Guide", config);
        YamlMetadataGenerator.DocMetadata docM = createDoc(
                "Mmm Guide", "mmm.adoc", "web", null, "Mmm Guide", config);

        Map<String, YamlMetadataGenerator.DocMetadata> docs = new LinkedHashMap<>();
        docs.put(docZ.filename, docZ);
        docs.put(docA.filename, docA);
        docs.put(docM.filename, docM);

        Map<String, Object> root = generateNavigation(config, docs);
        List<Map<String, Object>> nav = getNavigation(root);

        List<Object> guides = getGuides(nav.get(0));
        assertEquals(3, guides.size());

        @SuppressWarnings("unchecked")
        Map<String, Object> first = (Map<String, Object>) guides.get(0);
        @SuppressWarnings("unchecked")
        Map<String, Object> second = (Map<String, Object>) guides.get(1);
        @SuppressWarnings("unchecked")
        Map<String, Object> third = (Map<String, Object>) guides.get(2);

        assertEquals("Aaa Guide", first.get("nav-title"));
        assertEquals("Mmm Guide", second.get("nav-title"));
        assertEquals("Zzz Guide", third.get("nav-title"));
    }

    @Test
    public void emptyCategoriesSkipped() throws Exception {
        NavigationConfig config = loadConfig("""
                categories:
                  - category: web
                    cat-title: Web
                  - category: data
                    cat-title: Data
                  - category: cloud
                    cat-title: Cloud
                """);

        // Only add a guide for web — data and cloud should be skipped
        YamlMetadataGenerator.DocMetadata doc = createDoc(
                "REST Guide", "rest.adoc", "web", null, "REST APIs", config);

        Map<String, YamlMetadataGenerator.DocMetadata> docs = new LinkedHashMap<>();
        docs.put(doc.filename, doc);

        Map<String, Object> root = generateNavigation(config, docs);
        List<Map<String, Object>> nav = getNavigation(root);

        assertEquals(1, nav.size());
        assertEquals("web", nav.get(0).get("category"));
    }

    @SuppressWarnings("unchecked")
    @Test
    public void learningPathOutput() throws Exception {
        NavigationConfig config = loadConfig("""
                categories:
                  - category: web
                    cat-title: Web
                  - category: data
                    cat-title: Data

                learning-paths:
                  - path: rest-crud
                    path-title: Build a RESTful CRUD application
                    path-summary: Build a complete REST API with database access.
                    guides:
                      - hibernate-orm-panache.adoc
                      - rest.adoc
                """);

        YamlMetadataGenerator.DocMetadata restDoc = createDoc(
                "REST Guide", "rest.adoc", "web", null, "REST APIs", config);
        YamlMetadataGenerator.DocMetadata panacheDoc = createDoc(
                "Panache Guide", "hibernate-orm-panache.adoc", "data", null, "Panache", config);

        Map<String, YamlMetadataGenerator.DocMetadata> docs = new LinkedHashMap<>();
        docs.put(restDoc.filename, restDoc);
        docs.put(panacheDoc.filename, panacheDoc);

        Map<String, Object> root = generateNavigation(config, docs);

        // Verify learning-paths section exists
        assertTrue(root.containsKey("learning-paths"), "Should have learning-paths key");
        List<Map<String, Object>> paths = (List<Map<String, Object>>) root.get("learning-paths");
        assertEquals(1, paths.size());

        Map<String, Object> path = paths.get(0);
        assertEquals("rest-crud", path.get("path"));
        assertEquals("Build a RESTful CRUD application", path.get("path-title"));
        assertEquals("Build a complete REST API with database access.", path.get("path-summary"));

        // Guides should be in the config-specified order (panache first, rest second)
        List<Map<String, Object>> pathGuides = (List<Map<String, Object>>) path.get("guides");
        assertEquals(2, pathGuides.size());
        assertEquals("/guides/hibernate-orm-panache", pathGuides.get(0).get("url"));
        assertEquals("Panache", pathGuides.get(0).get("nav-title"));
        assertEquals("/guides/rest", pathGuides.get(1).get("url"));
        assertEquals("REST APIs", pathGuides.get(1).get("nav-title"));
    }

    @SuppressWarnings("unchecked")
    @Test
    public void learningPathOmittedWhenEmpty() throws Exception {
        NavigationConfig config = loadConfig("""
                categories:
                  - category: web
                    cat-title: Web

                learning-paths: []
                """);

        YamlMetadataGenerator.DocMetadata doc = createDoc(
                "REST Guide", "rest.adoc", "web", null, "REST APIs", config);

        Map<String, YamlMetadataGenerator.DocMetadata> docs = new LinkedHashMap<>();
        docs.put(doc.filename, doc);

        Map<String, Object> root = generateNavigation(config, docs);

        // learning-paths should not appear in output when empty
        assertFalse(root.containsKey("learning-paths"),
                "Empty learning-paths should not be in output");
    }

    @Test
    public void multiCategoryGuideAppearsInBoth() throws Exception {
        NavigationConfig config = loadConfig("""
                categories:
                  - category: web
                    cat-title: Web
                  - category: data
                    cat-title: Data
                """);

        // Guide with two categories
        YamlMetadataGenerator.DocMetadata doc = createDoc(
                "REST with DB", "rest-db.adoc", "web, data", null, "REST with database", config);

        Map<String, YamlMetadataGenerator.DocMetadata> docs = new LinkedHashMap<>();
        docs.put(doc.filename, doc);

        Map<String, Object> root = generateNavigation(config, docs);
        List<Map<String, Object>> nav = getNavigation(root);

        assertEquals(2, nav.size());

        // Guide should appear in both categories
        for (Map<String, Object> category : nav) {
            List<Object> guides = getGuides(category);
            assertEquals(1, guides.size());
            @SuppressWarnings("unchecked")
            Map<String, Object> guide = (Map<String, Object>) guides.get(0);
            assertEquals("/guides/rest-db", guide.get("url"));
        }
    }
}
