quarkus.oidc.devservices.enabled=true
quarkus.oidc.devservices.roles.Ronald=admin

quarkus.oidc-client.auth-server-url=${quarkus.oidc.auth-server-url}
quarkus.oidc-client.client-id=${quarkus.oidc.client-id}
quarkus.oidc-client.credentials.secret=${quarkus.oidc.credentials.secret}
quarkus.oidc-client.grant.type=password
quarkus.oidc-client.grant-options.password.username=alice
quarkus.oidc-client.grant-options.password.password=alice

quarkus.oidc-client.graphql-oidc-client.auth-server-url=${quarkus.oidc.auth-server-url}
quarkus.oidc-client.graphql-oidc-client.client-id=${quarkus.oidc.client-id}
quarkus.oidc-client.graphql-oidc-client.credentials.secret=${quarkus.oidc.credentials.secret}
quarkus.oidc-client.graphql-oidc-client.grant.type=password
quarkus.oidc-client.graphql-oidc-client.grant-options.password.username=alice
quarkus.oidc-client.graphql-oidc-client.grant-options.password.password=alice

quarkus.smallrye-graphql-client.typesafe-oidc-client.url=http://localhost:${quarkus.http.test-port:8081}/graphql
quarkus.smallrye-graphql-client.typesafe-named-oidc-client.url=http://localhost:${quarkus.http.test-port:8081}/graphql

quarkus.websockets-next.server.supported-subprotocols=quarkus
quarkus.websockets-next.server.propagate-subprotocol-headers=true

%code-flow.quarkus.oidc.devservices.roles.alice=admin,user
%code-flow.quarkus.oidc.devservices.roles.bob=user
%code-flow.quarkus.oidc.application-type=web-app
