[id="security-overview"]
= Quarkus Security overview
include::_attributes.adoc[]
:diataxis-type: concept
:categories: security

{product-name-first} Security is a framework that provides the architecture, multiple authentication and authorization mechanisms, and other tools for you to build secure and production-quality Java applications.

Before building security into your {product-name} applications, learn about the xref:security-architecture.adoc[{product-name} Security architecture] and the different authentication mechanisms and features that you can use.

== Key features of Quarkus Security

The {product-name} Security framework provides built-in security authentication mechanisms for Basic, Form-based, and mutual TLS (mTLS) authentication.
You can also use other well-known xref:security-authentication-mechanisms.adoc#other-supported-authentication-mechanisms[authentication mechanisms], such as OpenID Connect (OIDC) and WebAuthn.

Authentication mechanisms depend on xref:security-identity-providers.adoc[Identity providers] to verify the authentication credentials and map them to a `SecurityIdentity` instance, which has the username, roles, original authentication credentials, and other attributes.

{project-name} also includes built-in security to allow for role-based access control (RBAC) based on the common security annotations @RolesAllowed, @DenyAll, @PermitAll on REST endpoints, and CDI beans.
For more information, see the {product-name} xref:security-authorize-web-endpoints-reference.adoc[Authorization of web endpoints] guide.

{product-name} Security also supports the following features:

* xref:security-proactive-authentication.adoc[Proactive authentication]
* xref:http-reference.adoc#ssl[Secure connections with SSL/TLS]
* <<cross-origin-resource-sharing>>
* <<csrf-prevention>>
* <<samesite-cookies>>
* <<secrets-engines>>
* <<rest-data-panache>>
* <<secure-serialization>>
* xref:security-vulnerability-detection.adoc[Security vulnerability detection and National Vulnerability Database (NVD) registration]

{product-name} Security is also highly customizable.
For more information, see the {product-name} xref:security-customization.adoc[Security tips and tricks] guide.

== Getting started with Quarkus Security

To get started with security in {product-name}, consider combining the {product-name} built-in xref:security-basic-authentication.adoc[Basic authentication] with the Jakarta Persistence identity provider to enable role-based access control (RBAC).
Complete the steps in the xref:security-basic-authentication-tutorial.adoc[Secure a {product-name} application with Basic authentication] tutorial.

After successfully securing your {product-name} application with Basic authentication, you can increase the security further by adding more advanced authentication mechanisms, for example, the xref:security-oidc-code-flow-authentication.adoc[OpenID Connect (OIDC) authorization code flow mechanism].

== Quarkus Security testing

Guidance for testing {product-name} Security features and ensuring that your {product-name} applications are securely protected is provided in the {product-name} xref:security-testing.adoc[Security testing] guide.

== More about security features in Quarkus

[[cross-origin-resource-sharing]]
=== Cross-origin resource sharing

To make your {product-name} application accessible to another application running on a different domain, you need to configure cross-origin resource sharing (CORS).
For more information about the CORS filter that {product-name} provides, see the {product-name} xref:http-reference.adoc#cors-filter[CORS filter] section of the "HTTP reference" guide.

[[csrf-prevention]]
=== Cross-Site Request Forgery (CSRF) prevention

{product-name} Security provides a RESTEasy Reactive filter that can protect your applications against a https://owasp.org/www-community/attacks/csrf[Cross-Site Request Forgery] attack.
For more information, see the {product-name} xref:security-csrf-prevention.adoc[Cross-Site Request Forgery Prevention] guide.

[[samesite-cookies]]
=== SameSite cookies

You can add a link:https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite[SameSite] cookie property to any of the cookies set by a {product-name} endpoint.
For more information, see the {product-name} xref:http-reference.adoc#same-site-cookie[SameSite cookies] guide.

[[secrets-engines]]
=== Secrets engines
Secrets engines are components that store, generate, or encrypt data.

{product-name} provides comprehensive HashiCorp Vault support.
For more information, see the link:{vault-guide}[{product-name} and HashiCorp Vault] documentation.

[[secure-serialization]]
=== Secure serialization

If your {product-name} Security architecture includes RESTEasy Reactive and Jackson, {product-name} can limit the fields that are included in JSON serialization based on the configured security.
For more information, see the {product-name} xref:resteasy-reactive.adoc#secure-serialization[Writing REST services with RESTEasy Reactive] guide.

[[rest-data-panache]]
=== Secure auto-generated resources by REST Data with Panache

If you use the REST Data with Panache extension to auto-generate your resources, you can still use security annotations within the package `jakarta.annotation.security`.
For more information, see the xref:rest-data-panache.adoc#securing-endpoints[Securing auto-generated resources] section of the {product-name} "Generating Jakarta REST resources with Panache" guide.

== Security vulnerability detection

Most {product-name} tags get reported in the US link:https://nvd.nist.gov[National Vulnerability Database (NVD)].
For information about security vulnerabilities, see the xref:security-vulnerability-detection.adoc[Security vulnerability detection and reporting in {product-name}] guide.

== References

* xref:security-basic-authentication-tutorial.adoc[Secure a {product-name} application with Basic authentication and Jakarta Persistence]
* xref:security-oidc-code-flow-authentication-tutorial.adoc[Protect a web application by using OIDC authorization code flow]
* xref:security-oidc-bearer-token-authentication-tutorial.adoc[Protect a service application by using OIDC Bearer token authentication]
