package org.jboss.shamrock.deployment;

import java.io.IOException;

/**
 * Interface that represents a target for generated bytecode
 */
public interface ClassOutput {

    /**
     * Writes some generate bytecode to an output target
     *
     * @param className The class name
     * @param data      The bytecode bytes
     * @throws IOException If the class cannot be written
     */
    void writeClass(String className, byte[] data) throws IOException;

}
