//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.09.12 at 03:00:35 PM CEST
//

package io.quarkus.it.jaxb.mapper.codegen.feed;

import java.util.ArrayList;
import java.util.List;

import javax.xml.datatype.XMLGregorianCalendar;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="link" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="updated" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="subtitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="generator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="entry" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="link">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="updated" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="summary">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="author">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="category">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="term" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="scheme" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                             &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="content" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}lang"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "id",
        "title",
        "link",
        "updated",
        "subtitle",
        "generator",
        "entry"
})
@XmlRootElement(name = "feed")
public class Feed {

    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String id;
    @XmlElement(required = true)
    protected String title;
    protected List<Link> link;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar updated;
    @XmlElement(required = true)
    protected String subtitle;
    @XmlElement(required = true)
    protected String generator;
    protected List<Entry> entry;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    protected String lang;

    /**
     * Gets the value of the id property.
     *
     * @return
     *         possible object is
     *         {@link String }
     *
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *        allowed object is
     *        {@link String }
     *
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the title property.
     *
     * @return
     *         possible object is
     *         {@link String }
     *
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     *
     * @param value
     *        allowed object is
     *        {@link String }
     *
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the link property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the link property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getLink().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Feed.Link }
     *
     *
     */
    public List<Link> getLink() {
        if (link == null) {
            link = new ArrayList<Link>();
        }
        return this.link;
    }

    /**
     * Gets the value of the updated property.
     *
     * @return
     *         possible object is
     *         {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getUpdated() {
        return updated;
    }

    /**
     * Sets the value of the updated property.
     *
     * @param value
     *        allowed object is
     *        {@link XMLGregorianCalendar }
     *
     */
    public void setUpdated(XMLGregorianCalendar value) {
        this.updated = value;
    }

    /**
     * Gets the value of the subtitle property.
     *
     * @return
     *         possible object is
     *         {@link String }
     *
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * Sets the value of the subtitle property.
     *
     * @param value
     *        allowed object is
     *        {@link String }
     *
     */
    public void setSubtitle(String value) {
        this.subtitle = value;
    }

    /**
     * Gets the value of the generator property.
     *
     * @return
     *         possible object is
     *         {@link String }
     *
     */
    public String getGenerator() {
        return generator;
    }

    /**
     * Sets the value of the generator property.
     *
     * @param value
     *        allowed object is
     *        {@link String }
     *
     */
    public void setGenerator(String value) {
        this.generator = value;
    }

    /**
     * Gets the value of the entry property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entry property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getEntry().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Feed.Entry }
     *
     *
     */
    public List<Entry> getEntry() {
        if (entry == null) {
            entry = new ArrayList<Entry>();
        }
        return this.entry;
    }

    /**
     * Gets the value of the lang property.
     *
     * @return
     *         possible object is
     *         {@link String }
     *
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     *
     * @param value
     *        allowed object is
     *        {@link String }
     *
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="link">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="updated" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="summary">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="author">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="category">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="term" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="scheme" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *                   &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="content" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "id",
            "title",
            "link",
            "updated",
            "summary",
            "author",
            "category",
            "content"
    })
    public static class Entry {

        @XmlElement(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String id;
        @XmlElement(required = true)
        protected String title;
        @XmlElement(required = true)
        protected Feed.Entry.Link link;
        @XmlElement(required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar updated;
        @XmlElement(required = true)
        protected Feed.Entry.Summary summary;
        @XmlElement(required = true)
        protected Feed.Entry.Author author;
        @XmlElement(required = true)
        protected Feed.Entry.Category category;
        @XmlElement(required = true)
        protected String content;

        /**
         * Gets the value of the id property.
         *
         * @return
         *         possible object is
         *         {@link String }
         *
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         *
         * @param value
         *        allowed object is
         *        {@link String }
         *
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the title property.
         *
         * @return
         *         possible object is
         *         {@link String }
         *
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         *
         * @param value
         *        allowed object is
         *        {@link String }
         *
         */
        public void setTitle(String value) {
            this.title = value;
        }

        /**
         * Gets the value of the link property.
         *
         * @return
         *         possible object is
         *         {@link Feed.Entry.Link }
         *
         */
        public Feed.Entry.Link getLink() {
            return link;
        }

        /**
         * Sets the value of the link property.
         *
         * @param value
         *        allowed object is
         *        {@link Feed.Entry.Link }
         *
         */
        public void setLink(Feed.Entry.Link value) {
            this.link = value;
        }

        /**
         * Gets the value of the updated property.
         *
         * @return
         *         possible object is
         *         {@link XMLGregorianCalendar }
         *
         */
        public XMLGregorianCalendar getUpdated() {
            return updated;
        }

        /**
         * Sets the value of the updated property.
         *
         * @param value
         *        allowed object is
         *        {@link XMLGregorianCalendar }
         *
         */
        public void setUpdated(XMLGregorianCalendar value) {
            this.updated = value;
        }

        /**
         * Gets the value of the summary property.
         *
         * @return
         *         possible object is
         *         {@link Feed.Entry.Summary }
         *
         */
        public Feed.Entry.Summary getSummary() {
            return summary;
        }

        /**
         * Sets the value of the summary property.
         *
         * @param value
         *        allowed object is
         *        {@link Feed.Entry.Summary }
         *
         */
        public void setSummary(Feed.Entry.Summary value) {
            this.summary = value;
        }

        /**
         * Gets the value of the author property.
         *
         * @return
         *         possible object is
         *         {@link Feed.Entry.Author }
         *
         */
        public Feed.Entry.Author getAuthor() {
            return author;
        }

        /**
         * Sets the value of the author property.
         *
         * @param value
         *        allowed object is
         *        {@link Feed.Entry.Author }
         *
         */
        public void setAuthor(Feed.Entry.Author value) {
            this.author = value;
        }

        /**
         * Gets the value of the category property.
         *
         * @return
         *         possible object is
         *         {@link Feed.Entry.Category }
         *
         */
        public Feed.Entry.Category getCategory() {
            return category;
        }

        /**
         * Sets the value of the category property.
         *
         * @param value
         *        allowed object is
         *        {@link Feed.Entry.Category }
         *
         */
        public void setCategory(Feed.Entry.Category value) {
            this.category = value;
        }

        /**
         * Gets the value of the content property.
         *
         * @return
         *         possible object is
         *         {@link String }
         *
         */
        public String getContent() {
            return content;
        }

        /**
         * Sets the value of the content property.
         *
         * @param value
         *        allowed object is
         *        {@link String }
         *
         */
        public void setContent(String value) {
            this.content = value;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         *
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "name"
        })
        public static class Author {

            @XmlElement(required = true)
            protected String name;

            /**
             * Gets the value of the name property.
             *
             * @return
             *         possible object is
             *         {@link String }
             *
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             *
             * @param value
             *        allowed object is
             *        {@link String }
             *
             */
            public void setName(String value) {
                this.name = value;
            }

        }

        /**
         * <p>
         * Java class for anonymous complex type.
         *
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="term" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="scheme" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
         *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "term",
                "scheme",
                "label"
        })
        public static class Category {

            @XmlElement(required = true)
            protected String term;
            @XmlElement(required = true)
            @XmlSchemaType(name = "anyURI")
            protected String scheme;
            @XmlElement(required = true)
            protected String label;

            /**
             * Gets the value of the term property.
             *
             * @return
             *         possible object is
             *         {@link String }
             *
             */
            public String getTerm() {
                return term;
            }

            /**
             * Sets the value of the term property.
             *
             * @param value
             *        allowed object is
             *        {@link String }
             *
             */
            public void setTerm(String value) {
                this.term = value;
            }

            /**
             * Gets the value of the scheme property.
             *
             * @return
             *         possible object is
             *         {@link String }
             *
             */
            public String getScheme() {
                return scheme;
            }

            /**
             * Sets the value of the scheme property.
             *
             * @param value
             *        allowed object is
             *        {@link String }
             *
             */
            public void setScheme(String value) {
                this.scheme = value;
            }

            /**
             * Gets the value of the label property.
             *
             * @return
             *         possible object is
             *         {@link String }
             *
             */
            public String getLabel() {
                return label;
            }

            /**
             * Sets the value of the label property.
             *
             * @param value
             *        allowed object is
             *        {@link String }
             *
             */
            public void setLabel(String value) {
                this.label = value;
            }

        }

        /**
         * <p>
         * Java class for anonymous complex type.
         *
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "value"
        })
        public static class Link {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "rel")
            protected String rel;
            @XmlAttribute(name = "type")
            protected String type;
            @XmlAttribute(name = "href")
            @XmlSchemaType(name = "anyURI")
            protected String href;

            /**
             * Gets the value of the value property.
             *
             * @return
             *         possible object is
             *         {@link String }
             *
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             *
             * @param value
             *        allowed object is
             *        {@link String }
             *
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the rel property.
             *
             * @return
             *         possible object is
             *         {@link String }
             *
             */
            public String getRel() {
                return rel;
            }

            /**
             * Sets the value of the rel property.
             *
             * @param value
             *        allowed object is
             *        {@link String }
             *
             */
            public void setRel(String value) {
                this.rel = value;
            }

            /**
             * Gets the value of the type property.
             *
             * @return
             *         possible object is
             *         {@link String }
             *
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             *
             * @param value
             *        allowed object is
             *        {@link String }
             *
             */
            public void setType(String value) {
                this.type = value;
            }

            /**
             * Gets the value of the href property.
             *
             * @return
             *         possible object is
             *         {@link String }
             *
             */
            public String getHref() {
                return href;
            }

            /**
             * Sets the value of the href property.
             *
             * @param value
             *        allowed object is
             *        {@link String }
             *
             */
            public void setHref(String value) {
                this.href = value;
            }

        }

        /**
         * <p>
         * Java class for anonymous complex type.
         *
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "value"
        })
        public static class Summary {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "type")
            protected String type;

            /**
             * Gets the value of the value property.
             *
             * @return
             *         possible object is
             *         {@link String }
             *
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             *
             * @param value
             *        allowed object is
             *        {@link String }
             *
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the type property.
             *
             * @return
             *         possible object is
             *         {@link String }
             *
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             *
             * @param value
             *        allowed object is
             *        {@link String }
             *
             */
            public void setType(String value) {
                this.type = value;
            }

        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "value"
    })
    public static class Link {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "rel")
        protected String rel;
        @XmlAttribute(name = "type")
        protected String type;
        @XmlAttribute(name = "href")
        @XmlSchemaType(name = "anyURI")
        protected String href;

        /**
         * Gets the value of the value property.
         *
         * @return
         *         possible object is
         *         {@link String }
         *
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         *
         * @param value
         *        allowed object is
         *        {@link String }
         *
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the rel property.
         *
         * @return
         *         possible object is
         *         {@link String }
         *
         */
        public String getRel() {
            return rel;
        }

        /**
         * Sets the value of the rel property.
         *
         * @param value
         *        allowed object is
         *        {@link String }
         *
         */
        public void setRel(String value) {
            this.rel = value;
        }

        /**
         * Gets the value of the type property.
         *
         * @return
         *         possible object is
         *         {@link String }
         *
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         *
         * @param value
         *        allowed object is
         *        {@link String }
         *
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the href property.
         *
         * @return
         *         possible object is
         *         {@link String }
         *
         */
        public String getHref() {
            return href;
        }

        /**
         * Sets the value of the href property.
         *
         * @param value
         *        allowed object is
         *        {@link String }
         *
         */
        public void setHref(String value) {
            this.href = value;
        }

    }

}
