plugins {
    id 'io.quarkus.extension'
}

group = 'org.acme.model'
version = '1.0.0-SNAPSHOT'

dependencies {
    implementation platform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    implementation 'io.quarkus:quarkus-core'
}

quarkusExtension {
    deploymentModule = 'support-extension-deployment'
}
