{
 "title": "Quarkus OpenTelemetry Logging",
 "description": "Universal and flexible dashboard for logging",
 "tags": [
  "Quarkus",
  "OpenTelemetry",
  "logging"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "Service",
    "query": {}
   },
   {
    "name": "log_level",
    "label": "Log Level",
    "query": "FATAL,ERROR,WARN,INFO,DEBUG,TRACE"
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)" }
  ]
 },
 "panels": [
  {
   "title": "Total  Count of logs",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({service_name=~\"$service_name\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count of \"$searchable_pattern\"",
   "type": "stat",
   "description": "Total Count of \"$searchable_pattern\" in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({service_name=~\"$service_name\"} |~ \"(?i)$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{service_name=~\"$service_name\"} | severity_text=~\"$log_level\" |~ \"(?i)$searchable_pattern\" | line_format \"{{date \\\"2006-01-02 15:04:05.000\\\" .__time__ | alignLeft 24}} {{alignLeft 30 .service_name}} {{upper .detected_level | alignLeft 9}} {{__line__}}\""
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total count of stderr / stdout pie",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (count_over_time(({service_name=~\"$service_name\"} | label_format level=detected_level)[$__interval])) by (level)",
     "legendFormat": "{{stream}}"
    }
   ]
  },
  {
   "title": "Matched word \"$searchable_pattern\" donut",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 7, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (count_over_time(({service_name=~\"$service_name\"} | label_format level=detected_level |~ \"(?i)$searchable_pattern\")[$__interval])) by (level)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" Percentage for specified time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({service_name=~\"$service_name\"} |~ \"(?i)$searchable_pattern\")[$__interval])) * 100 / sum(count_over_time(({service_name=~\"$service_name\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Matched word \"$searchable_pattern\" historical",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({service_name=~\"$service_name\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (service_name)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" Rate per Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(({service_name=~\"$service_name\"} |~ \"(?i)$searchable_pattern\")[30s])) by (service_name)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Count of stderr / stdout historical",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({service_name=~\"$service_name\"})[$__interval])) by (service_name)",
     "legendFormat": "{{stream}}"
    }
   ]
  }
 ]
}