{
 "title": "Quarkus - Micrometer Metrics",
 "description": "Dashboard for Micrometer instrumented applications",
 "tags": [
  "jvm",
  "micrometer",
  "prometheus",
  "quarkus",
  "jdbc",
  "http"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_memory_used_bytes{)"
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": "label_values(jvm_memory_used_bytes{  area=\"heap\"},id)"
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": "label_values(jvm_memory_used_bytes{  area=\"nonheap\"},id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Quick Facts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_uptime_seconds" }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds * 1000"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"})*100/sum(jvm_memory_max_bytes{area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{area=\"nonheap\"})"
    }
   ]
  },
  { "title": "JDBC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "JDBC Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    { "expr": "agroal_active_count", "legendFormat": "Active Connections" },
    { "expr": "agroal_available_count", "legendFormat": "Available Connections" },
    {
     "expr": "rate(agroal_leak_detection_count_total[$__rate_interval])",
     "legendFormat": "Leaked Connections"
    }
   ]
  },
  {
   "title": "JDBC Blocking Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "agroal_blocking_time_average_milliseconds",
     "legendFormat": "Average (ms)"
    },
    {
     "expr": "agroal_blocking_time_max_milliseconds",
     "legendFormat": "Max (ms)"
    }
   ]
  },
  {
   "title": "I/O Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{ }[2m]))",
     "legendFormat": "HTTP"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{  status!~\"5..\"}[2m]))/sum(rate(http_server_requests_seconds_count{  status!~\"5..\"}[2m]))",
     "legendFormat": "HTTP - AVG"
    },
    {
     "expr": "max(http_server_requests_seconds_max{  status!~\"5..\"})",
     "legendFormat": "HTTP - MAX"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{  status=~\"5..\"}[5m]))",
     "legendFormat": "HTTP - 5xx"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{  area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{  area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{  area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{  area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{  area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{  area=\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "sum(jvm_memory_used_bytes{ })", "legendFormat": "used" },
    {
     "expr": "sum(jvm_memory_committed_bytes{ })",
     "legendFormat": "committed"
    },
    { "expr": "sum(jvm_memory_max_bytes{ })", "legendFormat": "max" }
   ]
  },
  {
   "title": "JVM Process Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_memory_rss_bytes{ }", "legendFormat": "rss" },
    { "expr": "process_memory_swap_bytes{ }", "legendFormat": "swap" },
    {
     "expr": "process_memory_rss_bytes{ } + process_memory_swap_bytes{ }",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "JVM Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "system_cpu_usage{ }", "legendFormat": "system" },
    { "expr": "process_cpu_usage{ }", "legendFormat": "process" },
    {
     "expr": "avg_over_time(process_cpu_usage{ }[1h])",
     "legendFormat": "process-1h"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "system_load_average_1m{ }", "legendFormat": "system-1m" },
    { "expr": "system_cpu_count{ }", "legendFormat": "cpus" }
   ]
  },
  {
   "title": "Thread States",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "jvm_threads_states_threads{ }", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "jvm_threads_live_threads{ }", "legendFormat": "live" },
    { "expr": "jvm_threads_daemon_threads{ }", "legendFormat": "daemon" },
    { "expr": "jvm_threads_peak_threads{ }", "legendFormat": "peak" },
    { "expr": "process_threads{ }", "legendFormat": "process" }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "process_files_open_files{ }", "legendFormat": "open" },
    { "expr": "process_files_max_files{ }", "legendFormat": "max" }
   ]
  },
  {
   "title": "HTTP Edpoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total number of requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{ }[2m])",
     "legendFormat": "{{method}} - {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "Average inbound request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{ }[4m]) / rate(http_server_requests_seconds_count{ }[4m])",
     "legendFormat": "{{method}} - {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "Maximum inbound request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{ }",
     "legendFormat": "{{method}} - {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "Sum of the duration of every request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{ }[2m])",
     "legendFormat": "{{method}} - {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "repeat": "persistence_counts",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$jvm_memory_pool_heap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 56 },
     "repeat": "jvm_memory_pool_heap",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{  id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{  id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{  id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
     "repeat": "jvm_memory_pool_nonheap",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{  id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{  id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{  id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Collections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_count{ }[2m])",
       "legendFormat": "{{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Pause Durations",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_sum{ }[1m])/rate(jvm_gc_pause_seconds_count{ }[1m])",
       "legendFormat": "avg {{action}} ({{cause}})"
      },
      { "expr": "jvm_gc_pause_seconds_max{ }", "legendFormat": "max {{action}} ({{cause}})" }
     ]
    },
    {
     "title": "Allocated/Promoted",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_memory_allocated_bytes_total{ }[2m])",
       "legendFormat": "allocated"
      },
      {
       "expr": "rate(jvm_gc_memory_promoted_bytes_total{ }[2m])",
       "legendFormat": "promoted"
      }
     ]
    }
   ]
  },
  {
   "title": "Classloading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Classes loaded",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "jvm_classes_loaded_classes{ }", "legendFormat": "loaded" }
     ]
    },
    {
     "title": "Class delta",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "delta(jvm_classes_loaded_classes{}[2m])",
       "legendFormat": "delta-1m"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Direct Buffers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{  id=\"direct\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{  id=\"direct\"}",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "Direct Buffers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_buffer_count_buffers{  id=\"direct\"}",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{  id=\"mapped\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{  id=\"mapped\"}",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_buffer_count_buffers{  id=\"mapped\"}",
       "legendFormat": "count"
      }
     ]
    }
   ]
  },
  {
   "title": "GraphQL requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total number of GraphQL requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(mp_graphql_seconds_count{ }[2m])",
       "legendFormat": "{{type}} {{name}}"
      }
     ]
    },
    {
     "title": "Average inbound request duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(mp_graphql_seconds_sum{ }[4m]) / rate(mp_graphql_seconds_count{ }[4m])",
       "legendFormat": "{{type}} {{name}}"
      }
     ]
    },
    {
     "title": "Maximum inbound GraphQL request duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "mp_graphql_seconds_max{ }", "legendFormat": "{{type}} {{name}}" }
     ]
    },
    {
     "title": "Sum of the duration of every GraphQL request",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(mp_graphql_seconds_sum{ }[2m])",
       "legendFormat": "{{type}} {{name}}"
      }
     ]
    }
   ]
  }
 ]
}