package org.acme;

import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;

@Path("/hello")
public class HelloResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "Hello from Quarkus REST";
    }

    @GET
    @Path("/entity")
    @Produces(MediaType.TEXT_PLAIN)
    public String entity() {
        // This verifies that the metamodel was generated by hibernate-processor
        // If processor didn't run, MyEntity_.class wouldn't exist and this would fail to compile
        return "Entity metamodel: " + MyEntity_.class.getSimpleName();
    }
}
