

ENV LANGUAGE='en_US:en'

EXPOSE 8080
USER 185
{#if java.version == '11'}
ENV AB_JOLOKIA_OFF=""
{/if}
ENV JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"
