quarkus.oidc.devservices.enabled=true
quarkus.keycloak.devservices.enabled=false

quarkus.websockets-next.server.supported-subprotocols=quarkus
quarkus.websockets-next.server.propagate-subprotocol-headers=true
