// Source: {{source}}

pluginManagement {
    plugins {
        id 'io.quarkus.application' version "${quarkusPluginVersion}"
    }
}

// tag::package-consumer-settings[]
rootProject.name = 'standalone-application-plugin-package-consumer'
include 'app', 'distribution'
// end::package-consumer-settings[]
