name: Surge.sh Preview

on:
  workflow_run:
    workflows: ["Quarkus Documentation CI"]
    types:
      - completed

defaults:
  run:
    shell: bash

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      issues: write
      # this is unfortunately needed to be able to write comments on pull requests
      pull-requests: write
      packages: read
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          repository: quarkusio/quarkusio.github.io
          fetch-depth: 5000
          fetch-tags: false
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          repository: quarkusio/quarkus
          path: quarkus-main

      - name: Install git-restore-time
        run: sudo apt-get install -y git-restore-mtime

      - name: Restore mtime
        run: git restore-mtime

      - name: Download PR Artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          run-id: ${{ github.event.workflow_run.id }}
          name: documentation
          path: documentation-temp
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Store PR id as variable
        id: pr
        run: |
          pr=$(<documentation-temp/pr-id.txt)
          if ! [[ $pr =~ ^[0-9]+$ ]] ; then
            echo "PR id extracted from documentation-temp/pr-id.txt is not a number: $pr"
            exit 1
          fi
          echo "id=$(<documentation-temp/pr-id.txt)" >> $GITHUB_OUTPUT
      - name: Sync documentation
        shell: bash
        # make sure we override the script coming from the artifact with the version from the main repository
        run: |
          rm ./documentation-temp/docs/sync-web-site.sh
          cp -a ./quarkus-main/docs/sync-web-site.sh ./documentation-temp/docs/
          chmod 755 ./documentation-temp/docs/sync-web-site.sh
          ./documentation-temp/docs/sync-web-site.sh main ../../
          rm -rf documentation-temp
          rm -rf quarkus-main
      - name: Set up ruby
        uses: ruby/setup-ruby@e65c17d16e57e481586a6a5a0282698790062f92 # v1.300.0
        with:
          ruby-version: 3.2.3
      - name: Cache Ruby gems
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-
      - name: Install dependencies
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Build Jekyll site
        run: bundle exec jekyll build --config _config.yml,_only_latest_guides_config.yml

      - name: Reduce the size of the website to be compatible with surge
        run: |
          rm -rf _site/assets/images/posts/
          rm -rf _site/assets/images/books/
          rm -rf _site/assets/images/events/
          rm -rf _site/assets/images/quarkus2/
          rm -rf _site/assets/images/quarkus3/
          rm -rf _site/assets/images/worldtour/
          rm -rf _site/assets/stickers
          rm -rf _site/assets/images/desktopwallpapers
          rm -rf _site/assets/images/stickers
          rm -rf _site/newsletter/
          # we only need the images from the main version
          rm -rf _site/guides/images/
          rm -rf _site/blog/
      - name: Publishing to surge for preview
        id: deploy
        run: npx surge@0.23.1 ./_site --domain https://quarkus-pr-main-${PR_ID}-preview.surge.sh --token ${{ secrets.SURGE_TOKEN }}
        env:
          PR_ID: ${{ steps.pr.outputs.id }}

      - name: Update PR status comment on success
        uses: quarkusio/action-helpers@main
        with:
          action: maintain-one-comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ steps.pr.outputs.id }}
          body: |
            🎊 PR Preview ${{ github.sha }} has been successfully built and deployed to https://quarkus-pr-main-${{ steps.pr.outputs.id }}-preview.surge.sh/version/main/guides/

            - Images of blog posts older than 3 months are not available.
            - Newsletters older than 3 months are not available.

            <img width="300" src="https://user-images.githubusercontent.com/507615/90250366-88233900-de6e-11ea-95a5-84f0762ffd39.png">
          body-marker: <!-- Preview status comment marker -->
      - name: Update PR status comment on failure
        uses: quarkusio/action-helpers@main
        if: ${{ failure() }}
        with:
          action: maintain-one-comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ steps.pr.outputs.id }}
          body: |
            😭 Deploy PR Preview failed.
            <img width="300" src="https://user-images.githubusercontent.com/507615/90250824-4e066700-de6f-11ea-8230-600ecc3d6a6b.png">
          body-marker: <!-- Preview status comment marker -->
