package io.quarkus.quartz.runtime;

public enum QuartzMisfirePolicy {
    SMART_POLICY,
    IGNORE_MISFIRE_POLICY,
    FIRE_NOW,
    SIMPLE_TRIGGER_RESCHEDULE_NOW_WITH_EXISTING_REPEAT_COUNT,
    SIMPLE_TRIGGER_RESCHEDULE_NOW_WITH_REMAINING_REPEAT_COUNT,
    SIMPLE_TRIGGER_RESCHEDULE_NEXT_WITH_REMAINING_COUNT,
    SIMPLE_TRIGGER_RESCHEDULE_NEXT_WITH_EXISTING_COUNT,
    CRON_TRIGGER_DO_NOTHING
}
